### ISSUE TITLE
[bug] update killing featureOver bindings

### ISSUE THREAD

**Issue by johnHackworth** [CartoDB/cartodb.js#1]
When you have a featureOver method in you model data, leaflet.js is creating a function that calls both the function passed in the model data and the featureOver from the view. BUT when you update the view, you lose the native one

**Comment by javisantana** [comment]
not sure what actually is but after 2 years I think this can be closed

**Comment by johnHackworth** [comment]
I will explain it, but frankly, after all this time I have no idea about what his were about :dancers:  

So I approve the closing :D

**Comment by javisantana** [comment]
haha you know, this is the first bug ever :)
