### ISSUE TITLE
Remove interactiveLayers from public API

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#1009]
Derived from https://github.com/CartoDB/cartodb.js/pull/1008/files#r50673410 we need to solve the issues with `interactiveLayers`:

- Duplicating layers collection
- Out-of-sync with layers as soon as a layer is added/removed

I think we need another mechanism to connect layers<->WindshaftMap, e.g. that each layer to know that it should register (and unregister on deletion) itself to Windshaft.

AFAIK `map.layers` is already "public" so DI could just use that for it's mapping, and listen in on changes on that collection to make its parts are relevant/up-to-date.

**Comment by alonsogarciapablo** [comment]
This was removed as part of #1018.
