### ISSUE TITLE
add a method to the layer to get infowindow/legends

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#101]

**Comment by knownasilya** [comment]
Yes please! I want to get the legend image or data (to build a component). I can do this with arcgis and geoserver, but not here so it's kind of a bummer.

**Comment by rowanwins** [comment]
I would also second this, particularly the legend. If you could provide an update on progress towards this @javisantana that would be appreciated. Thanks

**Comment by javisantana** [comment]
we will be working on infowindow and legends soon

**Comment by alonsogarciapablo** [comment]
It would be very helpful if you could provide some use cases of how you're planning to use infowindows and legends. We are currently [providing access to a cdb.geo.ui.InfowindowModel](http://docs.cartodb.com/cartodb-platform/cartodb-js.html#sublayerinfowindow) to work with infowindows on sublayers. We could do something similar with legends.

**Comment by knownasilya** [comment]
Mainly I'm looking to get the data necessary to build custom UI, since I have many types of layers in my app, and cartodb layers are only some of those. I already have infowindows/modals that handle the other layers, I just need to pull out that information from the carto layers.

**Comment by knownasilya** [comment]
Other times I just need to have more control over the default legend, so if I can have access to it as a view, that would help a lot.

**Comment by alonsogarciapablo** [comment]
Thanks for your input @knownasilya! What other things would you do if you had access to the view?

**Comment by alonsogarciapablo** [comment]
Closing this issue since part of it was already done. Will open a separate issue for next sprint since we're still discussing about the new Infowindow API.
