### ISSUE TITLE
Associate filters directly to map.layers

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1020]
Right now filters "belong" to dataviews, which are related to layers. So we're doing things like:

```
   var filtersFromVisibleLayers = [];
    if (dataviews) {
      filtersFromVisibleLayers = dataviews.chain()
        .filter(function (dataview) { return dataview.layer.isVisible(); })
        .map(function (dataview) { return dataview.filter; })
        .compact() // not all dataviews have filters
        .value();
    }
```

We're also having to [set a `layerIndex` on filters](https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/dataviews-factory.js#L56) so they can be grouped together when [we serialize them to send them to Windshaft](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/filters/collection.js#L12-L21).

All this would be easier if filters were associated to layers directly. Plus, it conceptually makes more sense IMO.

cc: @viddo

**Comment by viddo** [comment]
:kissing_heart: :bow:
