### ISSUE TITLE
Dataviews should fetch from the dataProvider when present

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1068]
Right now dataviews provide some methods that cause the data to be fetched from Windshaft. For example, category widgets use the `forceFetch` method on the category dataview model. This is making the Lock feature not work properly when layers have a GeoJSONDataProvider (because it's fetching data from Windshaft):

![locking](https://cloud.githubusercontent.com/assets/390398/12920556/66edf4ca-cf49-11e5-9f83-dbbbc81d7e80.gif)

cc: @javisantana

**Comment by javisantana** [comment]
hey, we just did a change to test it cc @fdansv could you paste the diff here?

**Comment by alonsogarciapablo** [comment]
Also, the dataview should be able to fetch the data from the dataprovider without the filter being applied.

**Comment by alonsogarciapablo** [comment]
Closed by #1076.
