### ISSUE TITLE
Windshaft map should not be refreshed when histogram is zoomed in

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1069]
The widget histogram is [changing some attributes](https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/histogram/content-view.js#L420) on its internal histogram dataview model after the first fetch, and when the user zooms in and out. The problem is that dataviews are now [listening to changes on some internal attributes (like bins)](https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/histogram-dataview-model.js#L51) to refresh the map when the dataview changes. This binding is causing the map to be refreshed when the internal state of the dataview changes (more specifically, when the `bins` property is changed).

cc: @javisantana @fdansv @viddo @javierarce

**Comment by alonsogarciapablo** [comment]
This also brings up another interesting question... Since the `bins` attribute of the histogram dataview is being changed by the Histogram widget ([here](https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/histogram/content-view.js#L420) and [here](https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/histogram/content-view.js#L436)). What's going to happen to an Histogram widget if someone (for example: the editor), changes the value of that `bins` attribute while the histogram is zoomed? We probably need to "reset" de widget in that case, right?

**Comment by alonsogarciapablo** [comment]
@javierarce I've been looking into this but I think you have more info about how this is implemented so I figured you could have some better ideas on how to fix this....

We basically need to avoid changing the `bins` property internally, cause that's somehow part of the "configuration" of the dataview. Could we just use an extra property instead of "re-using" `bins`? Can you think of a better way of fixing this?

**Comment by acanimal** [comment]
Related with this, while working on CartoD1B I found the need to know which histogram was selected (the "main" or the "zoomed" chart) to make the queries for later fill the chart.

Histogram widget model is the only way to communicate/interact with the widget so IMO it would need to have this properties:

- `start/end`: always contains the range of the main histogram.
- `minMain/maxMain`: the filter values for the selected bin on the main chart. Note sometimes the "main" chart is the green one and sometimes the black one.
- `binsMain`: the number of bins for the main chart
- `minZoomed/maxZoomed`: the filter values for the selected bin on the zoomed chart.
- `binsZoomed`: the number of bins for the zoomed chart.
- `chart` (main, zoomed): indicates on which chart the last modification has made. For example, if you change bins range on a zoomed histogram it must value `zoomed`.

I know the last property (`chart`) adds some state to the model, but from cartod1b I need to know if when widget must load data it belongs to filtered range on the main or on the zoomed chart.

I think differentiating between `binsMain` and `binsZoomed` will solve the issue Pablo is asking for.

**Comment by javisantana** [comment]
this requires a better fix guys

**Comment by alonsogarciapablo** [comment]
:+1: Agree that we can find a better solution, so thanks @javisantana for pushing ourselves a bit more! :)

> So it's much better to go to the end of the chain and remove the binding to those attributes. Specially in this case where start, end and bins are attributes that don't require to update the map.

Changing the number of "bins" should trigger a request to get the information for the histogram again (i.e: when the user changes the number of bins of a histogram using the editor). So I don't think we can remove that binding, can we?

What it's true is that deep-insights.js shouldn't know so much about the internals of the histogram dataview and do things like:

```
this._dataviewModel.set({ start: this.start, end: this.end, bins: this.binsCount }, { silent: true });
this._dataviewModel.fetch();
```

I will think about a better solution.

**Comment by javisantana** [comment]
> So I don't think we can remove that binding, can we?

No, binding to fetch data is ok for that concrete widget but not to reload the full map which is not needed.
