### ISSUE TITLE
Category Legend Key Colors Are White if No Content-Type Included - CreateLayer

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb.js#1072]
S/B 8068221
@alonsogarciapablo 
### Context

Category legend colors become white when create map using createLayer and viz.json if don't include content-type in HTML
### Process

Create a Category map in the Editor with category legends
Add map to HTML page using createLayer, don't include content-type in the file
Legend colors will not apply, legend key colors will all be white
![screen shot 2016-02-09 at 12 33 21 pm](https://cloud.githubusercontent.com/assets/5423288/12924707/5b227dfc-cf29-11e5-806c-e347345fc542.png)
This only applies to category visualizations made in the Editor
### Expected Result

Legend key colors should be shown
![screen shot 2016-02-09 at 12 34 02 pm](https://cloud.githubusercontent.com/assets/5423288/12924858/71c2802a-cf29-11e5-9dce-031bb26c4f87.png)
### Current Result

Legend key colors are white
![screen shot 2016-02-09 at 12 33 21 pm](https://cloud.githubusercontent.com/assets/5423288/12924707/5b227dfc-cf29-11e5-806c-e347345fc542.png)

Example code:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Legend Test</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
     <!-- <meta http-equiv="content-type" content="text/html; charset=UTF-8"/> -->
    <link rel="shortcut icon" href="http://cartodb.com/assets/favicon.ico" />
    <link rel="stylesheet" href="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/themes/css/cartodb.css" />
     <script src="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/cartodb.js"></script>

    <style>
      html, body, #map {
        height: 100%;
        padding: 0;
        margin: 0;
      }
    </style>

  </head>
  <body>
    <div id="map"></div>

      <script>

      function main() {
        var map = L.map('map', { 
          zoomControl: true,
          center: [0, 0],
          zoom: 2,
          search: true
        });
        L.tileLayer('http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.png', {
          attribution: 'Stamen'
        }).addTo(map);
        cartodb.createLayer(map, 'https://team.cartodb.com/u/chandra/api/v2/viz/df041f7c-d19b-11e4-b48b-0e43f3deba5a/viz.json')
         .addTo(map)
         .on('done', function(layer) {

          }).on('error', function() {
            console.log("some error occurred");
          });
      }
      window.onload = main;
    </script>

  </body>
</html>
```

**Comment by alonsogarciapablo** [comment]
@ernesmb, this is the same issue you reported, right?

**Comment by ernesmb** [comment]
yes, this is the same one we discussed on #platform. This was the answer from @rochoa 

>rochoa 
the problem it's related to the charset
[17:08] 
just place that html within a directory and ...
[17:09] 
`python -m SimpleHTTPServer`
[17:09] 
go to http://localhost:8000/untitled.html
[17:09] 
you will have the same issue
[17:09] 
check response headers for the html file
[17:10] 
stop the server and start it but adding the utf-8 charset(edited)
[17:10] 
```python -c "import SimpleHTTPServer; m = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map; m[''] = 'text/plain'; m.update(dict([(k, v + ';charset=UTF-8') for k, v in m.items()])); SimpleHTTPServer.test();"```
[17:10] 
check again response headers
[17:10] 
legends are ok now
[17:11] 
I don't know why it's that way
[17:11] 
we need to dig into cartodb.js to know why

**Comment by inigomedina** [comment]
@ivanmalagon, is this issue ready to be closed?

**Comment by ivanmalagon** [comment]
This issue is related to editor times. I'd close it.
