### ISSUE TITLE
interactivity not working for hover in deep insights

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#1128]
from https://github.com/CartoDB/deep-insights.js/issues/238

tried to replicate populated places interactivity, couldn't manage

vizjson is as follows:
https://gist.github.com/matallo/2836a8aca5cde2131bbc

no errors or further info appear in the console

let me know if you need more info

**Comment by alonsogarciapablo** [comment]
Fixed in #1132. I tested out the provided example and tooltips for the airports are now working :ok_hand:

**Comment by matallo** [comment]
el puto amo, thanks!
