### ISSUE TITLE
[vector] Labels on top are blocking events from the svg features

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb.js#1131]
As discussed @javisantana, for now we should just add a `pointer-events: none` CSS property to each of the `<img>` elements of the labels layer on leaflet. That should make those tiles let svg events through.

More info: https://developer.mozilla.org/en/docs/Web/CSS/pointer-events

**Comment by alonsogarciapablo** [comment]
Fixed in [31db61ac5fb461bf49db2709321da31bbfbf0710](https://github.com/CartoDB/cartodb.js/commit/31db61ac5fb461bf49db2709321da31bbfbf0710)

**Comment by alonsogarciapablo** [comment]
Fixed in [a8885a73bb7f49b37dbf1213a2878252920acbdd](https://github.com/CartoDB/cartodb.js/commit/a8885a73bb7f49b37dbf1213a2878252920acbdd#commitcomment-16321398).
