### ISSUE TITLE
[bug] featureClick with ctrl key down doesn't fire in Firefox

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#1163]
http://jsfiddle.net/9ddLa/65/

Open in Firefox and hold down ctrl and click a feature. You should see an alert, but you don't. This works fine in chrome or in firefox on osx.

**Comment by knownasilya** [comment]
Could someone have a look at this?

**Comment by jsanz** [comment]
@knownasilya that fiddle uses a normal event attachment that works (at least on my side) equally on Chrome and Firefox.

```js
layer.on('featureClick', function () {
  alert('clicked');
});
```

Where are you setting any behavior related with the `Control` key?

**Comment by knownasilya** [comment]
I'm testing this on Windows and Mac with Firefox 44.0.2. I hold down the `ctrl` and then clicking a feature. This works just fine in Chrome both on Windows and Mac, but not in Firefox.

**Comment by jsanz** [comment]
On Mon, Mar 14, 2016 at 4:15 PM, Ilya Radchenko <notifications@github.com>
wrote:

> I'm testing this on Windows and Mac with Firefox 44.0.2. I hold down the
> ctrl and then clicking a feature. This works just fine in Chrome both on
> Windows and Mac, but not in Firefox.
>
>
Sorry but I'm a bit lost, you don't need to use the Control key at all to
fire the event, why you want the user to push that key?

**Comment by knownasilya** [comment]
I'm trying to implement advanced features where ctrl+click selects a feature in a different mode. This works fine elsewhere, except for Firefox.

**Comment by jsanz** [comment]
On Mon, Mar 14, 2016 at 4:31 PM, Ilya Radchenko <notifications@github.com>
wrote:

> I'm trying to implement advanced features where ctrl+click selects a
> feature in a different mode. This works fine elsewhere, except for Firefox.
>
>
And where in your code are you setting up the logic of a different
behaviour with the Control key?


-- 
Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Comment by knownasilya** [comment]
The problem is that the `featureClick` event doesn't even fire when holding down the ctrl key, and since my branching code is within that event, it doesn't work.

**Comment by jsanz** [comment]
Can you share a minimal example with that code that sets up logic for the Control key?

**Comment by knownasilya** [comment]
Ok, seems like this isn't just with cartodb layers, but with google maps as well, so I'm going to close this and do more research.
