### ISSUE TITLE
ramp( ) doesn't work with vector tiles

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#1168]
First of all, I'm aware this might be the wrong repo to report this, sorry in advance, feel free to reassign or ping me in the proper direction.

when using turbocartocss (i.e. `ramp([mrr_for_display], 2, 16, quantiles)` with vector tiles) these seem to fail as they are not supported yet.

I can provide further info if needed.

**Comment by fdansv** [comment]
Possible duplicate of https://github.com/CartoDB/d3.cartodb/issues/117

**Comment by matallo** [comment]
closing then!
