### ISSUE TITLE
Layers API

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1169]
**WARNING: This is a WIP. I will remove this comment once I complete the description based on the feedback from @viddo @javierarce  @xavijam**

Here's an initial proposal for the API that the editor needs to work with CartoDB.js layers:

**Creation of new layers**
```
var layer = map.createCartoDBLayer(attrs);
var layer = map.createTorqueLayer(attrs);
var layer = map.createTileLayer(attrs);
// ... (we probably have more types (color, wms, etc.))
```

**Deletion of an existing layer**

```
layer.remove();
```

**Update of an existing layer**

```
// Update a layer
layer.update(attrs)
```

**Showing/hiding a layer**

```
layer.show();
layer.hide();
```

**Comment by viddo** [comment]
LGTM (so far) :+1:

**Comment by alonsogarciapablo** [comment]
I'm not sure if it makes to provide `map.createTorqueLayer({ ... })` since layers created using the editor are initially regular layers. CartoDBLayers become TorqueLayers when they are animated (there's a checkbox to do so in the new editor). From the editor's POV I think it'd make sense to create a regular layer and then update it... Not sure how this problem is being currently solved in the current editor though.

cc: @javisantana

**Comment by javisantana** [comment]
cc @viddo you can answer that, I think @alonsogarciapablo didn't get the way you want the editor <-> cartodb.js comm work

**Comment by alonsogarciapablo** [comment]
I do understand that the editor will need different methods to create different types of layers. For example, the editor should be able to `vis.map.createTileLayer({...})`. What I'm saying in my previous comment is that, in the context of the editor, you create a layer from a dataset and then you animate it. The editor doesn't know if the layer is going to be animated when it creates the layer.

```
// The modal that creates layer would trigger
var layer = map.createCartoDBLayer({
  sql: 'SELECT * FROM people',
  cartocss: '#people { }'
});

// The form to edit the style of the layer would trigger
layer.update({
  animated: true,
  duration: 60,
  steps: 30
});
```

IMO, CartoDB.js should then detect that the layer is animated and do whatever is necessary to render the layers correctly (i.e: create a new instance of the map and add new layer view for the torque layer).

**Comment by viddo** [comment]
> since layers created using the editor are initially regular layers.

Why do you assume that? Why shouldn't a user be able to create an torque layer directly?

**Comment by alonsogarciapablo** [comment]
> Why do you assume that? Why shouldn't a user be able to create an torque layer directly?

Because we don't currently have that option in the editor AFAIK and I don't see that option in the new designs.

**Comment by alonsogarciapablo** [comment]
The alternative (if we really need `map.createTorqueLayer`) would be something like:

```
// The modal that creates layer would trigger
var cartodbLayer = map.createCartoDBLayer({
  sql: 'SELECT * FROM people',
  cartocss: '#people { }'
});

// User enables "animate" on the Style form and changes some parameters:
cartodbLayer.remove({ silent: true });
var torqueLayer = map.createTorqueLayer(_.extend(cartodbLayer.attributes, {
  duration: 60,
  steps: 10
}));

// User disables "animate" on the Style form and changes some parameters:
torqueLayer.remove({ silent: true });
var cartoDBLayer = map.createTorqueLayer(_.pick(torqueLayer.attributes, 'sql', 'cartocss'));
```

**Comment by viddo** [comment]
I see. My initial thought was to handle the type changes in the [same way we do for widgets](https://github.com/CartoDB/cartodb/blob/5906b7c2ebc7a70c9a34dcac4829d7d280b7ca4d/lib/assets/javascripts/cartodb3/data/widget-definitions-collection.js#L102-L104). The editor models are just _definitions_, not the actual layers, thus there's only one model (`LayerDefinition`) that holds a set of data (e.g. `{ type: 'tiled', name: 'my plain layer', …}`).

**Comment by viddo** [comment]
Looking at your prev proposal of:
```
// The modal that creates layer would trigger
var layer = map.createCartoDBLayer({
  sql: 'SELECT * FROM people',
  cartocss: '#people { }'
});

// The form to edit the style of the layer would trigger
layer.update({
  animated: true,
  duration: 60,
  steps: 30
});
```
Not sure how that update would work technically, wouldn't a change like this (tile->torque) require to create a new layer model of type torque? This is why I proposed the same approach as for widgets (delete existing layer, create the layer of the new type).

**Comment by javisantana** [comment]
I'm really into what @viddo proposes, I'll explain my reasons:

- in current editor (2.0) cartodb.js and the editor share the layer models. Those models are used both for changing the map and managing all the editing features (infowindows, sql, cartocss). 

One of the problems appears when you need to switch from a cartodb layer to a torque one. You can not change the model because it's being used everywhere but in reality you would want to change so the map renders a torque layer.

In order to avoid that we need to use CartoDBLayer model everywhere, no mater if is a torque layer or a CartoDBLayer. That is confusing.

- The @viddo proposal fixes that. Having different models allow to have a LayerDefinition in the editor that deals with all the editing stuff (no mater what is the layer type) and the cartodb.js models deal with the map changes. 

From my experience, switching from one layer type to another is a pain, it's much clean and clear to have explicit layer types and not try to be smart at cartodb.js level

**Comment by javisantana** [comment]
Anyways, if we want to follow the dataviews rules we should go with createTorqueLayer or createWhateverLayer.

**Comment by alonsogarciapablo** [comment]
What I was suggesting is to use the same model (CartoDBLayer) and then decide how to render that model at the map-view level (i.e: when the layer triggers `change:animated` we create a new windshaft map passing the layer as torque now and we remove/re-add layerviews accordingly).

But, let's keep going and see how we solve this problem once we encounter it. I will create `map.createTorqueLayer` for now and we can figure this out when we work on the style form :+1:

**Comment by javisantana** [comment]
and another really important thing, do not confuse an animated layer with a torque layer.

Having an "animated:true" does not make a layer a torque layer. Torque is a really special kind of layer and should be managed in a totally different way

**Comment by alonsogarciapablo** [comment]
Do you guys think `map.createTorqueLayer()` should check if there's already a torque layer and throw an error in that case due to the limitation we have (only one torque layer per map)?

**Comment by javisantana** [comment]
That's a editor limitation actually so I'd say no

**Comment by alonsogarciapablo** [comment]
Can CartoDB.js handle more than one torque layer? Because in that case it's not  a limitation of the editor IMO, but a limitation of CartoDB.js itself... Again, it's not a big deal at this point but I'm just throwing out questions that pop up in my mind as I implement this...

**Comment by javisantana** [comment]
you can add more than one torque layer to cartodb.js, you can try it

**Comment by alonsogarciapablo** [comment]
Closed by #1175

**Comment by alonsogarciapablo** [comment]
@javisantana This issue is now closed, but I'm trying to understand the following assertion:

> Torque is a really special kind of layer and should be managed in a totally different way

I'm trying to understand why we need TorqueLayer model instead of having a CartoDBLayer that has an `animated` attribute that can be enabled, and that CartoDB.js can take into account when rendering that layer, etc (as suggested [here](https://github.com/CartoDB/cartodb.js/issues/1169#issuecomment-192192315)). 

Here's my current understanding of CartoDB vs Torque layers:

**Similarities:**

- Both types of layers share the `sql`, `cartocss` and `cartocss_version` attributes.
- Both types of layers are serialized the same way in the MapConfig that is sent to Windshaft.
- Right now, CartoDB and TorqueLayer models share some methods (`hasInteraction`, `getInfowindowData`, `getTooltipData`, `fetchAttributes`, etc.).

**Differences:**

- The TorqueLayer model provides some methods to control the animation (`play`, `pause`, etc.).
- Torque layers include some metadata in the response that comes from Windshaft that is then set in the TorqueLayer (`{ start: 2000, end: 6000, steps: 256, data_steps: 5, column_type: "number"}`) and used 
- Torque layers are now rendered using the [torque library](https://github.com/CartoDB/torque).

@javisantana any other difference that makes Torque layers so different than regular CartoDB layers? thanks!

**Comment by javisantana** [comment]
torque layers are special because:

- They don't provide row per row visualization, it's aggregated
- You can render them properly client side (cartodb layers can be rendered server side)
- They need to know about the whole dataset before being rendered
- The most important: the restrictions are really high and are not present in cartodb layers. You need to have a "time" column, the geometry type is really specific (which can be aggregated and do not need special maths to be animated, no grouping)

You could answer yourself asking this question: How would I merge a cartodb animated layer and a torque layer.
