### ISSUE TITLE
An interactivity object is always being passed in the layer configuration

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb.js#1182]
https://team.cartodb.com/u/saleiva/editor/ff2dddfa-03bf-11e5-a4d8-0e43f3deba5a/embed?vector=true
vs
https://team.cartodb.com/u/saleiva/viz/ff2dddfa-03bf-11e5-a4d8-0e43f3deba5a/public_map

If you open both mapconfigs being sent to the tiler, you'll notice that in a few layers we are "automatically" adding an `interactivity` array only containing `cartodb_id`. The SQL query<sup>1</sup> being applied to that layer doesn't return a cartodb_id column, so the instance fails, as it's trying to get a column that doesn't exist.

This comes from https://github.com/CartoDB/d3.cartodb/issues/134

@xavijam @alonsogarciapablo 

1 - `SELECT ST_Transform(ST_Segmentize(ST_MakeLine(a.the_geom, b.the_geom)::geography, 100000)::geometry,3857) as the_geom_webmercator FROM saleiva.tuenti_employees_locations_2015 a, populated_places b WHERE b.name = 'Madrid'`

**Comment by xavijam** [comment]
Those are different maps, one is old version (v3 viz.json) and the other is the new one (v4 viz.json).

**Comment by fdansv** [comment]
Yeah but there seems to be something wrong with the interactivity field in the new one right?

**Comment by javisantana** [comment]
I see this:

```
sql: "SELECT ST_Transform(ST_Segmentize(ST_MakeLine(a.the_geom, b.the_geom)::geography, 100000)::geometry,3857) as the_geom_webmercator FROM saleiva.tuenti_employees_locations_2015 a, populated_places b WHERE b.name = 'Madrid'",
layer_name: "Lines",
cartocss: "/** simple visualization */ #tuenti_employees_locations_2015{ line-color: #FFFFFF; line-width: 0.5; line-opacity: 0.3; line-smooth: 1; } ",
cartocss_version: "2.1.1",
interactivity: null,
table_name: """."
```

Other layers have `cartodb_id` both in the interactivity and the sql, could you point to the place where this is failing?

**Comment by fdansv** [comment]
Take a look at the mapconfig being sent at the first example (vector or not doesn't matter). At the `lines` layer...
```json
{
  "type": "cartodb",
  "options": {
    "sql": "SELECT ST_Transform(ST_Segmentize(ST_MakeLine(a.the_geom, b.the_geom)::geography, 100000)::geometry,3857) as the_geom_webmercator FROM saleiva.tuenti_employees_locations_2015 a, populated_places b WHERE b.name = 'Madrid'",
    "cartocss": "/** simple visualization */\n\n#tuenti_employees_locations_2015{\n  line-color: #FFFFFF;\n  line-width: 0.5;\n  line-opacity: 0.3;\n  line-smooth: 1;\n}\n",
    "cartocss_version": "2.1.1",
    "interactivity": [
      "cartodb_id"
    ],
    "widgets": {}
  }
}
```

It's including an interactivity array with only cartodb_id, which doesn't exists as a column in that SQL query.

**Comment by xavijam** [comment]
Seems like a problem with the mapconfig definition sent from CartoDB.js, yep :+1:

**Comment by xavijam** [comment]
The problem could be here:

https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/layergroup-config.js#L18
https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map/cartodb-layer.js#L76
