### ISSUE TITLE
Heatmap layer does not show up in IE10

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb.js#1188]
I have found the following bug. Those are the steps I have followed:

- I created a heatmap with the Editor.
- The problem consist in that the heatmap layer does not show up in IE10:

![capturica](https://cloud.githubusercontent.com/assets/5215798/13707707/30a6937a-e7ab-11e5-9185-d7517a97af1b.png)

- On the other hand, in Chrome and Firefox works. It shows a warning but the heatmap layer shows up:

![iechromeerror](https://cloud.githubusercontent.com/assets/5215798/13707751/700e2df2-e7ab-11e5-8b60-260fb9f9615f.png)

- Finally, **in IE11 works**. The heatmap layer is shown.

**Comment by fdansv** [comment]
Heatmaps require CORS to be available with images. IE10 doesn't support that, so heatmaps don't work with IE10.

http://stackoverflow.com/a/17012551
