### ISSUE TITLE
Simplify layers API (remove unnecessary method)

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#1202]
While working on integrating the new layers API on the [new editor](https://github.com/CartoDB/cartodb/pull/6917) I discovered that there's only one type of "plain" layer, the [background type does't exist](https://github.com/CartoDB/cartodb/pull/6917/commits/8ec2e2d4a0e35c62cf277d13540f6532e3703acf), it's only a plain layer with either color or an image set.

To KISS the code (both here and in the editor) I'd suggest to [remove the createBackgroundLayer method](https://github.com/CartoDB/cartodb.js/blob/11437811119b7f06c73ecf4a7f7e21cc3ab5cf9c/src/geo/map.js#L83-L91), and change the assertion to check for either color _or_ image.

**Comment by alonsogarciapablo** [comment]
Solved in #1205.
