### ISSUE TITLE
Create new example using Leaflet layer control

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#121]
It would be useful to have an example showing how to include several CartoDB layers with Leaflet.

**Comment by javisantana** [comment]
assign it whoever you want

**Comment by namessanti** [comment]
@andrewxhill

**Comment by iriberri** [comment]
Actually: http://bl.ocks.org/iriberri/074a71940dc606d98079

On Tuesday, May 26, 2015, Santiago Giraldo Anduaga <notifications@github.com>
wrote:

> @andrewxhill <https://github.com/andrewxhill>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb.js/issues/121#issuecomment-105661358>.
>


-- 

Carla Iriberri
*CartoDB*

**Comment by andrewxhill** [comment]
boom

On Tue, May 26, 2015 at 5:09 PM, Carla <notifications@github.com> wrote:

> Actually: http://bl.ocks.org/iriberri/074a71940dc606d98079
>
> On Tuesday, May 26, 2015, Santiago Giraldo Anduaga <
> notifications@github.com>
> wrote:
>
> > @andrewxhill <https://github.com/andrewxhill>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CartoDB/cartodb.js/issues/121#issuecomment-105661358
> >.
> >
>
>
> --
>
> Carla Iriberri
> *CartoDB*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb.js/issues/121#issuecomment-105665388>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by javisantana** [comment]
@iriberri why don't you add that example to examples folder?
