### ISSUE TITLE
cartocss should have precedence over tile_style when layer model is created

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#1210]
Not entirely sure how it should be handled internally, but in the layers data set in the editor the layer has both `tile_style` and `cartocss`, but inspecting the model it only has `cartocss` set with the value of `tile_style`, so I guess there is some internal parsing of the data that causes it to not have the expected value.

**Comment by alonsogarciapablo** [comment]
Here's some testing I did:
```
> var layer = vis.map.createCartoDBLayer({
  sql: 'something',
  cartocss: 'cartocss',
  tile_style: 'tile_style'
}, {
  silent: true
})
> console.log(layer.get('cartocss'), layer.get('tile_style')
=> cartocss tile_style
```
This seems to work fine...
@viddo can you provide some code to reproduce what you're describing? Thx

**Comment by viddo** [comment]
Found the culprit, it's actually the data on the vizJSON that's not correct (overriding the cartocss with the tile_style value instead)… so closing this one, sorry for the inconvenience

**Comment by alonsogarciapablo** [comment]
:+1:
