### ISSUE TITLE
"no data available" shown in tooltips

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#122]
like http://webdocc.cartodb.com/viz/760b4f46-ebef-11e3-a5c6-0e10bcd91c2b/embed_map

**Comment by knownasilya** [comment]
I'm having this issue. The situation is I have a viz with 3 sublayers, one of which is setup for tooltips. When I hover over features from that sublayer nothing happens, but when I hover over features of a layer that doesn't have tooltip data, it shows the "No data available" tooltip.

**Comment by knownasilya** [comment]
I have a feeling it has something to do with layer order, so the layer number is incorrect.

**Comment by alonsogarciapablo** [comment]
This might be related to #713.

**Comment by knownasilya** [comment]
Yeah, I would have expected it to get the layers by name/id, not by index.

**Comment by acanimal** [comment]
Hi @knownasilya, I saw you are using cartodb.js version 3.14.5.
Please could you update to the latest version3.15.3 and check if problem persists? Some bugs has been solved related to that issue in newer versions.
