### ISSUE TITLE
Integrate analysis statuses/urls from Maps API

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1229]
Windshaft is now returning the ~statuses~ and URLs to get the actual status of each of the analysis nodes present in a visualization (*). This issue captures all the changes that we need to do in CartoDB.js.

**Requirements:**

- [x] If all nodes are ready -> proceed normally (fetch tiles, update URLs of dataviews, update analysis queries...).
- ~~If any of the nodes of the analyses is not ready yet (waiting, running, failed), CartoDB.js **should NOT**~~:
  - [ ] ~~fetch the new tiles (cause they won't be ready yet) (@saleiva: have you thought about this state? tiles won't be ready because analyses are being processed and new tiles cannot be fetched yet... should we display some sort of global loader?)~~.
  - [ ] ~~set the URLs of dataviews (widgets should change to "loading" state)~~.
- [x] CartoDB.js should use the URLs of each of the analysis nodes, to check periodically if "everything" is ready. Each analysis model should pull and update it's state from the Maps API.
- [ ] ~~Dataviews associated to an analysis node should listen to their state and update their URLs as soon as the associated analysis is ready (analysis of type "source" are always ready)~~.
- [x] CartoDB.js should fetch the tiles once all analyses are ready again.

cc: @javisantana @rochoa 

(*) Example of a response with analyses:

```
{
  "layergroupid": "7357a96cb13323a64251f93f15649572:0",
  "metadata": {
    "layers": [
      {
        "type": "mapnik",
        "meta": {
          "stats": [],
          "cartocss": "#points['mapnik::geometry_type'=1] {\n  marker-fill-opacity: 1;\n  marker-line-color: #FFF;\n  marker-line-width: 0.5;\n  marker-line-opacity: 1;\n  marker-placement: point;\n  marker-type: ellipse;\n  marker-width: 8;\n  marker-fill: #FABADA;\n  marker-allow-overlap: true;\n}\n#lines['mapnik::geometry_type'=2] {\n  line-color: #000000;\n  line-width: 2;\n  line-opacity: 1;\n}\n#polygons['mapnik::geometry_type'=3] {\n  polygon-fill: #FABADA;\n  polygon-opacity: 1;\n  line-color: #FFF;\n  line-width: 0.5;\n  line-opacity: 1;\n}"
        }
      }
    ],
    "dataviews": {},
    "analyses": [
      {
        "nodes": {
          "a1": {
            "query": "select * from analysis_trade_area_5eeaad22776ff8936767c173f4f92f8aa17c8ebc",
            "url": {
              "http": "http://cdb.localhost.lan:8181/api/v1/map/7357a96cb13323a64251f93f15649572:0/analysis/0/node/a1"
            },
            "status": "running"
          },
          "a0": {
            "query": "select * from arboles limit 10",
            "url": {
              "http": "http://cdb.localhost.lan:8181/api/v1/map/7357a96cb13323a64251f93f15649572:0/analysis/0/node/a0"
            },
            "status": "ready"
          }
        }
      }
    ]
  },
  "last_updated": "1970-01-01T00:00:00.000Z"
}
```

**Comment by rochoa** [comment]
About:

> - If any of the nodes of the analyses is not ready yet (waiting, running, failed), CartoDB.js **should NOT**:
>  - [ ] fetch the new tiles (cause they won't be ready yet) (@saleiva: have you thought about this state? tiles won't be ready because analyses are being processed and new tiles cannot be fetched yet... should we display some sort of global loader?).

That not totally true, nodes might produce intermediate results so it's possible to retrieve tiles even if the analysis didn't finish but keep looking for the ready state to know when to retrieve them again.

Imagine that within the response you can receive also a "last_updated" field so you can know if the node has been updated since your last check and retrieve a fresh set of tiles.

**Comment by alonsogarciapablo** [comment]
> nodes might produce intermediate results so it's possible to retrieve tiles even if the analysis didn't finish

From the "new" Maps API response (:point_up)... how can CartoDB.js know that?

**Comment by alonsogarciapablo** [comment]
And... would it make sense to render some "incomplete" tiles (i.e: features from one layer are visible but features from other layers are not ready yet, so they won't be displayed)? How will the user know that tiles are still incomplete and analyses are still running?

**Comment by saleiva** [comment]
There is a loader indicating which step of the proccess is im progress + a
global loader in the bottom, yeah.

**Comment by alonsogarciapablo** [comment]
Talked to @rochoa offline. CartoDB.js will do polling of analysis nodes that are not `ready` and are (back)linked to a layer or dataview. If a node changes it's state to `ready`, a new instance of the map will be created and tiles will be fetched again at that point.

As for the loader, we'll start by showing the existing CartoDB.js loader (blue bar at the top) until all analyses are ready. I'll open a separate issue to discuss how we can improve to give a better feeback to the users (particularly for analyses that take several minutes).
