### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by kennynaoh** [CartoDB/cartodb.js#1249]
Hello @javisantana ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a version problem.
The latest version in git tag is v3.15.9
But the latest version in npm is v3.15.1
Maybe should publish the latest version on [npm](https://www.npmjs.com/package/cartodb.js).
Thanks

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by alonsogarciapablo** [comment]
Done!

**Comment by kennynaoh** [comment]
Thanks.
