### ISSUE TITLE
duplicated tutorials in examples

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#1275]
adapting some of the examples to https, I realized some of them are duplicated (inside the tutorials folder)

https://github.com/CartoDB/cartodb.js/tree/gh-pages/examples
https://github.com/CartoDB/cartodb.js/tree/gh-pages/examples/tutorials

please remove if necessary

**Comment by csobier** [comment]
I noticed this too but am hesitant to delete them. Since I am not the original owner, and this is not a content management system, I don't know if someone is using this links somewhere else?

**Comment by matallo** [comment]
it's true, but having them duplicate will make the problem worse (and a pain to maintain)

I don't know how to find those external links, I just can think of a https://www.google.es/#q=%22cartodb.github.com%22 search

In any case, I'd contact the owner and make them know we're consolidating those examples, for any complain it can always be addressed via an issue, or something

**Comment by csobier** [comment]
Agreed to remove them, but how can we tell who the original owner is?

**Comment by matallo** [comment]
https://github.com/CartoDB/cartodb.js/commits/gh-pages/examples/tutorial-1.html
