### ISSUE TITLE
Ensure requests to the Maps API are not queued up

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1310]
Ensure no requests are pending, before sending a new request to the Maps API... CartoDB.js should cancel any pending requests (there should only be one) before sending a new requests to create an instance of a map.

cc: @rochoa.

**Comment by alonsogarciapablo** [comment]
Closed via https://github.com/CartoDB/cartodb.js/pull/1315.

**Comment by rochoa** [comment]
Quick question: does cartodb.js handles the error from the cancelled request?

**Comment by alonsogarciapablo** [comment]
Quick response: no, it just aborts the previous request and, since there's no response, nothing changes internally.
