### ISSUE TITLE
[ANALYSIS] After changing the parameters of an analysis forcing widgets recalculation

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#1322]
@saleiva commented on [Tue Jun 14 2016](https://github.com/CartoDB/cartodb/issues/7838)

the map gets refreshed but the widgets don't

---

@saleiva commented on [Fri Jun 24 2016](https://github.com/CartoDB/cartodb/issues/7838#issuecomment-228326178)

it should do the same when a query is being applied

**Comment by viddo** [comment]
I believe this is something that should be updated internally on the dataviews when there are analysis changes, right?

**Comment by alonsogarciapablo** [comment]
When the map is reloaded and Windshaft returns a new `layergroupid`, dataviews will get a new URLs and they [might fetch the data again](https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/dataview-model-base.js#L166-L169).

**Comment by alonsogarciapablo** [comment]
Soved in https://github.com/CartoDB/cartodb.js/issues/1323.
