### ISSUE TITLE
Logo aligment in embeds

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1342]
@carlostallon commented on [Fri Jul 08 2016](https://github.com/CartoDB/cartodb/issues/8694)

![image](https://cloud.githubusercontent.com/assets/1712650/16684286/8de269e0-4504-11e6-9ea4-7f2a5b045ca1.png)

Hi guys, can you move down 8px the logo?

---

@xavijam commented on [Fri Jul 08 2016](https://github.com/CartoDB/cartodb/issues/8694#issuecomment-231324599)

This is for CartoDB.js

**Comment by alonsogarciapablo** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/commit/342857d7c0c27d63aa3b162e1b7c7c33e14acb3b!

**Comment by carlostallon** [comment]
thanks guys!
