### ISSUE TITLE
Add a way to expose the native map object

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb.js#1353]
In v3 we had `.getNativeMap()` function, but it's now deprecated. We need to access the native map object in order to allow partners and final users to integrate CARTO within their existing frontend, with added features like [this](https://carto.com/blog/read-and-write-to-cartodb-with-the-leaflet-draw-plugin/)

**Comment by alonsogarciapablo** [comment]
I'm tracking this in https://github.com/CartoDB/cartodb.js/issues/1280. Thanks @AbelVM.
