### ISSUE TITLE
It's redundant to ask for layer type when creating a layer

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1354]
@AbelVM commented on [Thu Jul 14 2016](https://github.com/CartoDB/deep-insights.js/issues/422)

It's compulsory to add `type` attrib as parameter when creating a layer, but the type is implicit in the function name:

```javascript
createCartoDBLayer({...type:'CartoDB'...})
createTorqueLayer({ ...type: 'Torque', ...})
...
```

It would be way simpler if the type is defined only once as a parameter instead of having 6 different functions:

```javascript
createLayer({...type:'CartoDB'...})
createLayer({ ...type: 'Torque', ...})
...
```

**Comment by viddo** [comment]
On this topic I recall @javisantana wrote [this comment](https://github.com/CartoDB/cartodb.js/pull/962#discussion_r48164450) motivating why he thought it was better to have separate methods over a generic one.

**Comment by alonsogarciapablo** [comment]
There's [this bug](https://github.com/CartoDB/cartodb.js/issues/1297#issue-158677097).  You will not need to set the type once this is fixed.

**Comment by AbelVM** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
Closing this issue then. I will fix https://github.com/CartoDB/cartodb.js/issues/1297 now and we won't need the layer types anymore.
