### ISSUE TITLE
Layer interaction in IE10/IE11 not working when dragging a leaflet marker

### ISSUE THREAD

**Issue by dvail** [CartoDB/cartodb.js#139]
Hi all, the featureOver/Out events do not fire in recent versions of internet explorer when you drag a leaflet marker over the layer.

The problem stems from this line: https://github.com/CartoDB/cartodb.js/blob/develop/vendor/wax.cartodb.js#L3163

Commenting the line out fixes the issue for our use case without causing other obvious problems, but I'm sure this isn't ideal.

I have a minimal test case set up at http://jsfiddle.net/wdr0qx5o/1/

**Comment by Xatpy** [comment]
Line that he comments (with history revision) is: 
> bean.add(parent(), 'MSPointerDown', onDown);

https://github.com/CartoDB/cartodb.js/blob/a6e19b8caf9de2b86a5a6470ddfee95e14c401ce/vendor/wax.cartodb.js#L3163

**Comment by Xatpy** [comment]
I'm testing with this [link](http://bl.ocks.org/xatpy/1d681598113c8e756d27)

**Comment by Xatpy** [comment]
[Fix](https://github.com/Xatpy/wax/commit/66873dc93754d140748890bfaef3a0d9a2a93837#diff-aef87864d96cd9c13dba9f346d915238R137)

> Reason: Internet Explorer is triggering pointerdown when you click on the marker, and other browsers don't. Because of that, _downLock was active and it believed that you're dragging the map, instead of dragging the marker

**Comment by Xatpy** [comment]
Fixed in **3.12.6**
[Test](http://bl.ocks.org/xatpy/1d681598113c8e756d27)
