### ISSUE TITLE
vector=true maps broken

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb.js#1399]
I guess mostly related to [show/hide layer](https://github.com/CartoDB/cartodb.js/pull/1376) changes.

![screen shot 2016-09-01 at 14 35 10](https://cloud.githubusercontent.com/assets/45346/18167551/78b451fa-7051-11e6-83b4-574203747c0f.png)

**Comment by alonsogarciapablo** [comment]
Yes. We'll need to do someting like [this](https://github.com/CartoDB/cartodb.js/pull/1376/files#diff-c06a872d1984ab3706e2d674ecae85c3R132).

**Comment by alonsogarciapablo** [comment]
Closed via https://github.com/CartoDB/cartodb.js/pull/1400
