### ISSUE TITLE
Check mapzen geocoder implementation in search input

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb.js#1408]
It seems specially bad now...
If you go to 201 Moore st, Brooklyn it points you to the middle of nowhere for example.

**Comment by alonsogarciapablo** [comment]
I checked this (using 210 Moore St, Brooklyn) and it seems to be working fine now. CartoDB.js is basically triggering a request (https://search.mapzen.com/v1/search?text=201%20moore%20st%2C%20brooklyn&api_key=XXXX) to MapZen's API, so there's little we can do to improve this on our side AFAIK 😞 .
