### ISSUE TITLE
Legend layer name margin

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1427]
All layer selector titles have a margin top that makes the legends box to be taller than expected.

<img width="380" alt="screen shot 2016-10-05 at 16 38 13" src="https://cloud.githubusercontent.com/assets/132146/19117730/544f3dd2-8b1a-11e6-9ad0-ab35f534b388.png">

**Comment by xavijam** [comment]
I feel it is already fixed by @nobuti, right?

**Comment by piensaenpixel** [comment]
it's fixed
