### ISSUE TITLE
For an long item in the legends, it uses as many lines as it needs and the color gets stretched

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1439]
<img width="274" alt="screen shot 2016-10-11 at 12 09 27" src="https://cloud.githubusercontent.com/assets/132146/19266823/b2466916-8fab-11e6-9cd7-5ae53cb869ef.png">

**Comment by xavijam** [comment]
Should the text by cut off? what do you think @CartoDB/design?

**Comment by arianaescobar** [comment]
My 2 cents: I wouldn't cut the text. The whole point of the legends is to give information about the map, right?

**Comment by xavijam** [comment]
Ok, question, if the text is a paragraph like this:

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

What do you think? :)

**Comment by arianaescobar** [comment]
hahaha good point, well... that's too much 😂

**Comment by josecruz** [comment]
IMHO we should cut that text off, just as widgets does

**Comment by saleiva** [comment]
+1 to @josecruz comment

**Comment by carlostallon** [comment]
+1 to cut that text

**Comment by piensaenpixel** [comment]
my turn +1 to cut the text :P

**Comment by xavijam** [comment]
Could you take a look @nobuti please? It should be easy.

**Comment by nobuti** [comment]
Closed by #1455.
