### ISSUE TITLE
Minimize precission on numbers on legends.

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1444]
@saleiva commented on [Tue Oct 11 2016](https://github.com/CartoDB/cartodb/issues/10145)

We should use the same approach than in the widgets. Numbers with decimal look very bad,

---

@xavijam commented on [Wed Oct 12 2016](https://github.com/CartoDB/cartodb/issues/10145#issuecomment-253274045)

Moving to cartodb.js.

**Comment by nobuti** [comment]
Closed by #1449.
