### ISSUE TITLE
Bubble legends not correctly styled in Firefox

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb.js#1452]
![screenshot_20161019_140324](https://cloud.githubusercontent.com/assets/7569673/19518001/dd180f14-9604-11e6-8718-33a0052efcd6.png)

STR:
 1. Create a map
 2. Style the fill size by value
 3. Create legend by size

In Firefox, the bubble legend is not correctly aligned at the center.

Please cc me in the PR, as we also may need to do some changes to legend migration.

**Comment by xavijam** [comment]
Hey, this is kind of important @piensaenpixel, if there is no possibility to take a look, @nobuti, please, check it in any of your legends PR please.

**Comment by nobuti** [comment]
Closed by #1457
