### ISSUE TITLE
Legends showing pretty small values seem broken

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1456]
@saleiva commented on [Tue Oct 18 2016](https://github.com/CartoDB/cartodb/issues/10225)

![screen shot 2016-10-18 at 08 47 01](https://cloud.githubusercontent.com/assets/132149/19467087/88173486-950f-11e6-82b8-914519e098dc.png)

Easy to reproduce when aggregating by provinces (on the style options) and showing the legend for the agg_value_density

cc/ @xavijam 

---

@xavijam commented on [Tue Oct 18 2016](https://github.com/CartoDB/cartodb/issues/10225#issuecomment-254551562)

And what do you propose @saleiva? 0 to 0? 0 to 0.1?

---

@saleiva commented on [Wed Oct 19 2016](https://github.com/CartoDB/cartodb/issues/10225#issuecomment-254872104)

Like we do in widgets, we should round, yeah.

---

@xavijam commented on [Thu Oct 20 2016](https://github.com/CartoDB/cartodb/issues/10225#issuecomment-255029291)

Moving to CartoDB.js, where labels are generated.

**Comment by nobuti** [comment]
Closed by #1461
