### ISSUE TITLE
Logo appears over search input

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1458]
![screen shot 2016-10-20 at 16 15 49](https://cloud.githubusercontent.com/assets/132146/19564376/a9589704-96e3-11e6-89b7-8e5e60bfe156.png)

**Comment by alonsogarciapablo** [comment]
Related with https://github.com/CartoDB/cartodb.js/issues/1404?

**Comment by xavijam** [comment]
It could be, but it it appears over an infowindow is not that "buggy".

**Comment by piensaenpixel** [comment]
it's fixed
