### ISSUE TITLE
Infowindow template only appears and replaces values if fields are previously selected

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1475]
@juanignaciosl commented on [Thu Oct 27 2016](https://github.com/CartoDB/cartodb/issues/10423)

This works in the Editor, not in the Builder. Appeared here but it's a different problem: #10407.

STR
1. Create a new map with the builder.
2. Select "light" infowindow without fields.
3. Edit the HTML and add a field (`{{my_column}}`).

^ **Infowindows should be enabled, but they're not**.
1. Go back and select light infowindow and one field.
2. Edit the HTML and add a second column (not previously selected.

^ *\* Infowindow won't display the value of the second column

cc @matallo @alonsogarciapablo  @javisantana @piensaenpixel @xavijam

**Comment by javisantana** [comment]
and why does it work in the editor, what is the difference? AFAIK we only fetch values in the `infowindow.fields` list, right?

**Comment by alonsogarciapablo** [comment]
The problem is that we're only showing the infowindow (click popups) ONLY when some fields have been selected. That's the reason why custom infowindows are only working when some fields are selected. We must show these popups if the infowindow has a template. Pretty easy to fix.

**Comment by alonsogarciapablo** [comment]
Closed via https://github.com/CartoDB/cartodb.js/pull/1476.
