### ISSUE TITLE
Creating viz.json in carto ui so featureClick works

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#1483]
I'm having a hard time getting featureClick to work on a viz. It's created in the ui and is clickable there, but once I get it in the app, the featureClick doesn't work. I'm trying to do the click on the overall layer, since I don't know which specific sublayer it is. I did `layer.setInteraction(true)` and I only need the `cartodb_id` which should be in by default, no?

Example viz https://mapgeo.carto.com/u/mapgeoprod/api/v2/viz/724465d2-9931-11e5-ab0f-42010a14800c/viz.json

For that viz, it seems like the featureClick only works when done through another feature that has an infowindow...

**Comment by jsanz** [comment]
Hi @knownasilya the vizjson shows only infowindow configured for one of the layers of the map (`newtonma_cityfacilities`).

If you check the named map template that backs your visualization you'll see that only that layer has configured an interactivity. You can retrieve the template with 

```
curl -X GET "https://mapgeoprod.carto.com/api/v1/map/named/tpl_724465d2_9931_11e5_ab0f_42010a14800c?api_key=YOUR_API_KEY"
```

And you'll see that the editor is only setting on the template the interactivity for the facilities layer so when instantiated it only allows interaction to that layer. You can see this working [here](http://plnkr.co/edit/2Oq1hDugVP4DWOfsl0Rg?p=preview). Templates cannot be overriden by client code obviously so your map has that limited interaction.

You can fix this with two approaches:

- Set up interactivity of your map using the editor and probably later at your app change the default behavior overriding standard tooltip/infowindow interaction
- Create a new named map template manually and set up interactivity.

Hope this helps

**Comment by knownasilya** [comment]
For approach 1, how do I set up interactivity in the editor? Is that just adding an infowindow for the layer (and then hiding the infowindow in my app)?

**Comment by michellechandra** [comment]
Hi @knownasilya - you are correct, to enable interactivity you would need to add an infowindow to the layer. Let us know if you have additional questions.

**Comment by knownasilya** [comment]
Would also like to see an example of creating a named map template programmatically. Is it possible to use a viz as a starting point for that?

**Comment by jsanz** [comment]
On Sat, Nov 5, 2016 at 12:48 AM, Ilya Radchenko <notifications@github.com>
wrote:

> Would also like to see an example of creating a named map template
> programmatically. Is it possible to use a viz as a starting point for that?
>
>
We don't have any example of backend code to create templates but from a
viz is straightforward to take the template name (search
for tpl_724465d2_9931_11e5_ab0f_42010a14800c on your viz.json for the JSON
path). Once you have the template you can create a new one just changing
the name and any other modifications you want to perform like adding new
placeholders or interactivity. Please refere to the named maps API
documentation for details

https://carto.com/docs/carto-engine/maps-api/named-maps/

Hope it helps
Jorge

**Comment by knownasilya** [comment]
Having a similar issue with another viz for a client, not sure what's up. I tried using @jsanz example by setting the event on each sublayer (even though there is only one), and still not getting any results.

https://dnainfo.carto.com/u/lisadoi/api/v2/viz/ab027a5e-c2f1-11e6-8998-0ee66e2c9693/viz.json

**Comment by jsanz** [comment]
@knownasilya not sure what can be wrong on your code, I've tried to simplify to the maximum your plunkr [here](http://plnkr.co/edit/zagvQbgXJd4pBzhKC7IV?p=preview) 

* Removed google and leaflet scripts
* Using `addToMap` instead of adding it inside the callback
* Tried calling the `featureClick` both on layer and sublayer. Both work.

One thing I see is that your infowindow is using BUILDER markup, that's strange since you shouldn't have that markup (`CDB-...` CSS classes) on a Editor viz.json. Probably not related with your issue but worth mentioning.

Unfortunately Leaflet 1.0 is still not supported by carto.js 3, have you tried your code with the leaflet code that comes with carto.js ??

**Comment by knownasilya** [comment]
So yeah it does have to do with Leaflet 1.0 compat, since https://github.com/CartoDB/cartodb.js/issues/1503#issuecomment-267677446 doesn't help completely in this case. Setting the version back to 0.7.7 fixed the `featureClick`.
