### ISSUE TITLE
Migrate leaflet to 1.x series

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb.js#1503]
Hi there, are there any plans to update cartodb.js to use leaflet 1.0.1? I tried using `https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/cartodb_noleaflet.js` today with leaflet v1.0.1 with an existing cartodb.js map and got the error:

`cartodb_noleaflet.js:16 Uncaught TypeError: this._adjustTilePoint is not a function(…)`

I would really like to use `map.flyTo()` and the new tooltips in my carto projects.

Thanks!

**Comment by knownasilya** [comment]
Ping

**Comment by knownasilya** [comment]
FYI if to work around the layer not working at all, just add a blank function, e.g.

```js
layer._adjustTilePoint = () => {};
```

**Comment by allthesignals** [comment]
I would say this compatibility is pretty important for CartoDB.js users who need to use other Leaflet plugins that often require Leaflet 1+.
