### ISSUE TITLE
[Google Map Support] Implement mechanism to switch provider when base layer is changed

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1527]
# Background

CartoDB.js doesn't currently provide a specific mechanism to switch the base layer (which might have an associated layer for labels on top) of a map. This is currently done "manually" in the context of the BUILDER (i.e: [base and labels layers are added/removed/replaced](https://github.com/CartoDB/cartodb/blob/5a9e83f5fa367985dbc60356c96b0ceb9ac59612/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L252-L297) when a new basemap is selected.)

### Existing types of base layers:

We currently have the following types of layers in our DB:

```
# SELECT DISTINCT(kind) FROM layers group by kind;
    kind
------------
 tiled
 gmapsbase
 torque
 carto
 background
 wms
(6 rows)
```

From those, `tiled`, `gmapsbase`, `background`, and `wms` can be used as base layers. And, there's a different implementation for each type of layer and provider ([Leaflet](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/geo/leaflet/leaflet-layer-view-factory.js#L24-L31) and [Google Maps](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/geo/gmaps/gmaps-layer-view-factory.js#L17-L25)):

### Current implementation in CartoDB.js:

- Leaflet:
  - leaflet-gmaps-tiled-layer-view.js (fallback gmaps -> leaflet (stamen, nokia) (*)
  - leaflet-plain-layer-view.js
  - leaflet-tiled-layer-view.js (also used as labels layer)
  - leaflet-wms-layer-view.js

(*) Not being used at the moment AFAIK.

- Google Maps:

  - gmaps-base-layer-view.js (roadmap, gray_roadmap, dark_roadmap, hybrid, satellite, terrain)
  - gmaps-plain-layer-view.js
  - gmaps-tiled-layer-view.js

**CAUTION:** WMS layers doesn't seem to be currently supported when using Google Maps ([this](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/geo/gmaps/gmaps-layer-view-factory.js#L19) doesn't seem right).

### Current basemap providers:

The BUILDER currently supports the following basemap providers: 

- CARTO (*) -> Tiled layer
- Stamen (*) -> Tiled layer
- Here (NOKIA) -> Tiled layer
- Custom:
  - XYZ -> Tiled layer
  - MAPBOX -> Tiled layer
  - WMS/WMTS -> WMS layer
  - TILEJSON -> Tiled layer
  - NASA -> Tiled layer
- Color -> Plain/Background layer

(*) Some basemaps support labels on top.

Basemaps are defined [here](https://github.com/CartoDB/cartodb-platform/blob/develop/cookbooks/cartodb_app/attributes/basemaps.rb) (internal only).

#### Leaflet

A Leaflet map with a tiled base layer and some labels on top:

```
{
  ...,
  'map_provider': 'leaflet',
  ...
  'layers': [
    {
      ...
      'type': 'tiled',
      'options': {
        urlTemplate: '....',
        ...
      }
      ...
    },
    {
      ...
      'type': 'CartoDB',
      'options': { ... }
      ...
    },
    {
      ...
      'type': 'tiled',
      'options': {
        urlTemplate: '....',
        ...
      }
      ...
    },
  ],
  ...
}
```
### Some interesting guides from the Google Maps JavaScript API docs:

- [Map Types](https://developers.google.com/maps/documentation/javascript/maptypes)
- [Custom Overlays](https://developers.google.com/maps/documentation/javascript/customoverlays)

#### Google Map

A Google Maps map with a "roadmap" base layer and a torque layer on top:

```
{
  ...,
  'map_provider': 'googlemaps',
  ...
  'layers': [
    {
      ...
      'type': 'gmapsbase',
      'options': {
        base_type: 'roadmap',
        style: [ { ... }, ... ]
      }
      ...
    },
    {
      ...
      'type': 'CartoDB',
      'options': { ... }
      ...
    },
    {
      ...
      'type': 'torque',
      'options': { ... }
      ...
    }
  ],
  ...
}

```

The `map_provider` that is received in the viz.json [is set as an attribute of the Map object](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/vis/vis.js#L157).

# Example, using the actual API:

This is how someone would switch to a Google Maps basemap, using what we have today (not working  #yet):

```
cartodb.createVis('map', function (vis, layers) {
  var baseLayer = vis.getLayer(0);
  var map = vis.map;

  // Remove the current baseLayer
  map.layers.remove(baseLayer);

  // Create a GMapsBase layer at position 0, silently
  map.createGMapsBaseLayer({
    base_type: 'roadmap',
    style: ''
  }, { at: 0, silent: true });

  // Change the map provider
  map.set({ provider: 'googlemaps' });
});
```

# Tasks

- [x] Review test suite and make sure map views and layer views are well tested.
- [x] Re-render visView when map provider changes.

**Comment by javisantana** [comment]
why do we want to move this to cartodb.js?

**Comment by alonsogarciapablo** [comment]
## Acceptance

This is deployed to staging (ded03).

1. Login to https://carto-staging.com/superadmin.
2. Find a user in ded03.
3. Edit the user and enter a valid google-maps-api-key.
4. Login as that user.
5. Verify that you can switch between from and to Google Maps basemap. Test other types (eg: plain color).
6. Test with one and multiple layers.
7. Ensure infowindows and tooltips work properly after switching basemaps (specially to and from Google Maps).
8. Test that you can draw geometries before and after switching basemaps .
9. Test that you can edit geometries before and after switching basemaps.

**Comment by dgaubert** [comment]
I can set Google Basemaps but I couldn't edit any feature, there is no button set to edit, in staging:
![screen shot 2017-02-14 at 18 39 40](https://cloud.githubusercontent.com/assets/1936888/22941233/fb3ae4a2-f2e4-11e6-8ee1-d462f0e723a6.png)

In prod:
![screen shot 2017-02-14 at 18 38 12](https://cloud.githubusercontent.com/assets/1936888/22941217/eee3beae-f2e4-11e6-934e-3dafb94b0166.png)

Alse there is a problem while setting zoom: `InvalidValueError: setZoom: not a number`

**Comment by dgaubert** [comment]
Also, every time I change basemaps zoom is automatically set to 18.

**Comment by alonsogarciapablo** [comment]
Moving this back to development. I'm taking a look at the problem with the zoom changing automagically. Thanks for reporting it @dgaubert!

**Comment by alonsogarciapablo** [comment]
I fixed the issues with the zoom (hopefully). I re-deployed this to staging. @dgaubert could you please verify that zoom errors are gone? Thanks a lot! cc: @rochoa

**Comment by dgaubert** [comment]
Sure thing! 

I'll back here to give some feedback! ❤️

**Comment by dgaubert** [comment]
I've found a little issue, when I add a pop-up to a layer for click event, the pop-up shows `null` values: 

![screen shot 2017-02-17 at 11 37 19](https://cloud.githubusercontent.com/assets/1936888/23062374/d04ce060-f505-11e6-9db2-7693032f5ba9.png)

After a hard refreshing, it works as expected: 

![screen shot 2017-02-17 at 11 37 40](https://cloud.githubusercontent.com/assets/1936888/23062407/e9604254-f505-11e6-8d1b-8396978bfed7.png)

Not sure if it is related to basemaps, but I've checked it in prod and pop-up works without refreshing.

Apart from that, everything else works like a charm!!

Hope this helps!

**Comment by alonsogarciapablo** [comment]
Thanks @dgaubert! Opening a separate issue with this.

**Comment by dgaubert** [comment]
> Not sure if it is related to basemaps

If not, then 🇨🇭
