### ISSUE TITLE
[Google Map Support] Review UI and fix minor UI issues

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1529]
http://localhost:9001/examples/v4/gmaps-layergroup.html

- [x] Attribution button is not position correctly
- ~[ ] Attribution: not showing the openstreetmap copyright defined in the vizjson~
- [x] ~Infowindows (click pop-ups) are not being displayed due to a z-index problem.~

**Comment by donflopez** [comment]
@alonsogarciapablo, I have a question here, being the map a gmaps base layer, do we need the openstreet map attribution?

**Comment by alonsogarciapablo** [comment]
Good point @donflopez. That task is actually wrong. I just removed it.

**Comment by donflopez** [comment]
Perfect, I'll do a PR then :)

**Comment by ethervoid** [comment]
What are the acceptance steps for this issue?

**Comment by donflopez** [comment]
I only did the first point, I'll put the acceptance for that one, @alonsogarciapablo can help us with the third one.

**Prerequisites:**

- clone and checkout to switch-to-gmaps branch
- npm i
- grunt dev
- go to `http://localhost:9001/examples/v4/gmaps-layergroup.html`

**Criteria:**
- Look at the search button, it has to be aligned with the others.

**Comment by alonsogarciapablo** [comment]
## Acceptance

This is deployed to staging (ded03).

- Login to https://carto-staging.com/superadmin.
- Find a user in ded03.
- Edit the user and enter a valid google-maps-api-key (you can get one [here](https://developers.google.com/maps/documentation/javascript/get-api-key))
- Login as that user.
- Verify that map looks 👌  (only thing that was not looking good was the attribution/info control)

Thanks!

**Comment by ethervoid** [comment]
@donflopez is your change deployed in ded03 too?

**Comment by donflopez** [comment]
yep!

**Comment by alonsogarciapablo** [comment]
Whatever it's easier for your @ethervoid. Another thing to verify:

- Click & hover popups (a.k.a. infowindows and tooltips) should work like a charm.

**Comment by ethervoid** [comment]
Cool. Thank you, on it!

**Comment by ethervoid** [comment]
### Acceptance results

### Leaflet

- [x] Attribution button is correctly positioned
- [x] Attribution text showed correctly
- [x] Added attribution to metada and check it appears correctly
   -  If we're using Google basemaps why do we have Openstreetmaps attribution?
- [x] Infowindows
    - [x] Infowindow
    - [x] Tooltips
- [x] Search button is aligned with others
- [x] Search button working properly

#### Issues:

- At some point the zoom went crazy, doing zoom in and zoom out forever
- When dragging around the map, in CARTO basemap, the zoom do something strange:

  ![zoom_weird](https://cloud.githubusercontent.com/assets/741240/22972782/6a5a2dfc-f37b-11e6-884c-60eb283c0059.gif)

### GMaps

- [ ] Attribution button is correctly positioned
- [x] Attribution text showed correctly
- [x] Added attribution to metada and check it appears correctly
   -  If we're using Google basemaps why do we have Openstreetmaps attribution?
- [x] Infowindows
    - [x] Infowindow
    - [x] Tooltips
- [x] Search button is aligned with others
- [x] Search button working properly

#### Warning:

```
util.js:210 Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

#### Issues:

- Attribution button is not correctly aligned

  ![captura de pantalla 2017-02-15 13 10 04](https://cloud.githubusercontent.com/assets/741240/22974265/cedcbad2-f381-11e6-897b-223fac3c1b18.png)



### Common issues

- Everytime I zoom in or out with the -/+ controlls I get this error in the console:
  ```
  InvalidValueError: setZoom: not a number
  _createNativeMap    @   gmaps-map-view.js:18
  ```
- If I'm at zoom level 18 and reload the map I get a debug? message: `the tiler does not support non-torque layers just yet…`

**Comment by donflopez** [comment]
It seems that the styling over the gmaps attribution button is in deep-insight too, I'll make a PR there.

Thank you @ethervoid!

**Comment by alonsogarciapablo** [comment]
Yes, that's something form cartodb.js. I'll make sure deps are updated.

**Comment by alonsogarciapablo** [comment]
Thanks for the thorough acceptance @ethervoid. I just re-deployed to staging and it's now looking good.

![screen shot 2017-02-15 at 16 25 57](https://cloud.githubusercontent.com/assets/390398/22981026/77e51f84-f39b-11e6-9686-cbfd9f9d5645.png)

I'm investigating some issues with zooming.

About the error message: `the tiler does not support non-torque layers just yet`. I haven't seen that one before. Perhaps @rochoa knows something about this?

**Comment by ethervoid** [comment]
Do we include this issues in this PR or just the attribution button positioning? To move to deploy or wait

**Comment by alonsogarciapablo** [comment]
@ethervoid since this issue is only about UI issues, we can probably open new issues for the other things you found. I just deployed to staging (ded-03) and some issues might be fixed now. I'd be great if you can try to reproduce the "common issues" you described now and, if so, open new issues with the steps to reproduce.

We're also taking care of the following console message (in https://github.com/CartoDB/cartodb/pull/11547/commits/94b6483e56555a4b8fab897d76e22802e69e3fb5):

```
util.js:210 Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

Thanks a lot!

**Comment by ethervoid** [comment]
- UI changes are ok
- Common problem with `InvalidValueError: setZoom: not a number` seems to be solved
- [Created issue](https://github.com/CartoDB/deep-insights.js/issues/522) for the time series component which looks like the culprit

So 🚀
