### ISSUE TITLE
HTML rendered in legends

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb.js#1533]
@ivanmalagon commented on [Mon Dec 12 2016](https://github.com/CartoDB/cartodb/issues/11014)

### Context
While editing a label in an admin aggregated layer, some HTML is rendered under certain circumstances.

![screen shot 2016-12-12 at 15 17 05](https://cloud.githubusercontent.com/assets/1078228/21102342/178107de-c07e-11e6-9b00-474801a76f47.png)

 

### Steps to Reproduce

1. Aggregate a layer in admin. regions.
2. Go to LEGEND tab.
3. Check TITLE and LEFT LABEL.
4. Write something only in LEFT LABEL.
5. Some HTML is shown in the legend.

### Additional info
#SMOKE_MG30

CC @luisbosque @xavijam 

---

@luisbosque commented on [Mon Dec 12 2016](https://github.com/CartoDB/cartodb/issues/11014#issuecomment-266467278)

Reproduced

**Comment by nobuti** [comment]
Closed by https://github.com/CartoDB/cartodb.js/issues/1535
