### ISSUE TITLE
Carto embedded does not show on IE11

### ISSUE THREAD

**Issue by coquiaspiazu** [CartoDB/cartodb.js#1536]
I get the screen error below on IE 11.

What I find surprising is that it was working until yesterday. And I can still see the embed on Edge, Chrome, etc. Is this a bug? or was something upgraded between yesterday and today?

![error screen](https://cloud.githubusercontent.com/assets/8021492/21155983/2d34cbc8-c142-11e6-963b-4934bfe8989d.png)

**Comment by alonsogarciapablo** [comment]
Issue moved to [CartoDB/cartodb #11038](https://github.com/CartoDB/cartodb/issues/11038) via [**ZenHub**](https://www.zenhub.com/)
