### ISSUE TITLE
[Google Map Support] Prep work for #1527

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1537]
Some prep work that I identified when doing a little prototype for #1527. This work can and should be mergeable/releasable at any given point, and should make implementing #1527 easier:

- [x] Extract view for overlays so that MapView's `el` only contains the map. Ensure infowindow and tooltip overlays are now longer managed by the MapView.

There's a follow up issue -> https://github.com/CartoDB/cartodb.js/issues/1539.

cc: @rochoa @jorgesancha

**Comment by jorgesancha** [comment]
Are you suggesting we break them up in different issues and prioritise independently? I'm all for that 👍  but I defer to @rochoa of course.

**Comment by alonsogarciapablo** [comment]
> Are you suggesting we break them up in different issues and prioritise independently?
No, I think that'd add a lot of noise to the board, so I think I will "ship" this in one PR.
