### ISSUE TITLE
[Google Maps Support] Prevent library from fetching tiles that are out of bounds

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1540]
CartoDB.js is fetching tiles for invalid coords and zoom.

The example in http://localhost:9001/examples/v4/gmaps-layergroup.html has this problem: 

![screen shot 2016-12-29 at 13 22 47](https://cloud.githubusercontent.com/assets/390398/21546438/0ed1058a-cddf-11e6-8f85-3743e26b34ad.png)

CartoDB.js is requesting some invalid tiles, such as http://2.ashbu.cartocdn.com/documentation/api/v1/map/90e64f1b9145961af7ba36d71b887dd2:0/0/2/2/4.png

And Windshaft is returning:

```
{
  "errors": [
    "Coordinates out of range: 2/2/4"
  ],
  "errors_with_context": [
    {
      "type": "unknown",
      "message": "Coordinates out of range: 2/2/4"
    }
  ]
}
```

**Comment by donflopez** [comment]
## Acceptance Criteria:

**Prerequisites:**
- clone this repo `v4` branch
- npm i
- npm run start

**Go to load the example!**
- run grunt dev
- go to [http://localhost:9001/examples/v4/gmaps-layergroup.html](http://localhost:9001/examples/v4/gmaps-layergroup.html)
- check that the tiles out of the map are blank images in base64

**Comment by jgoizueta** [comment]
Acceptance Check: 👍 

Before:
![screen shot 2017-02-08 at 14 12 00](https://cloud.githubusercontent.com/assets/5909/22738733/eff5e000-ee08-11e6-9d9e-e0245327df88.png)

After:
![screen shot 2017-02-08 at 14 13 16](https://cloud.githubusercontent.com/assets/5909/22738740/f40b614c-ee08-11e6-9fe0-8a0f65272028.png)

**Comment by donflopez** [comment]
Thanks @jgoizueta! :)
