### ISSUE TITLE
[Google Map Support] Prep work for #1527 (IV)

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1544]
- [x] Interactivity (featureClick, featureOver, featureOut events) work properly when mapViews are cleaned and re-rendered (eg: a mapView is removed and re-rendered and infowindows, tooltips, geometry management still work)

**Acceptance:**

1. Checkout `prep-work-for-gmaps-basemaps-4` and run `grunt dev`.
2. Visit http://localhost:9001/examples/v4/leaflet-layergroup.html
3. Verify that:
  - Infowindows and tooltips are working as expected.
  - Mouse cursor changes as features are overed/"un-overed".
  - You can draw on the map:
    ```
    // type this in the console and click on the map
    vis.map.drawPolygon() 
    ```
4. Replace the existing MapView (this is what will happen when basemap changes from Leaflet to Google Maps and viceversa):
```
mapView.clean();
var mapView = new cdb.geo.LeafletMapView({
  mapModel: vis.map,
  visModel: vis,
  layerGroupModel: vis.layerGroupModel
})
jQuery('#map').append(mapView.el);
mapView.render();
```
5. Check point 3 again (infowindows, tooltips, mouse cursor, drawing...).

Thanks!

**Comment by ethervoid** [comment]
Doing the acceptance tests I've found some weird behavior after rendering the new map view:

- Sometimes the Info window shows blank:

![captura de pantalla 2017-01-18 12 49 22 2](https://cloud.githubusercontent.com/assets/741240/22063142/8ccfeb38-dd7d-11e6-8553-11eba1d8cc7e.png)

- When I'm drawing the polygon:
  - First time all went fine, without any issue
  - After the rendering sometimes I have to click twice to draw a point of the polygon

**Comment by alonsogarciapablo** [comment]
Thanks for you comments @ethervoid! My thoughts....

> Sometimes the Info window shows blank:
The infowindow is probably blank because there's a pending request to the attributes service. If you wait a bit the infowindow should probably be filled with the data.

> When I'm drawing the polygon, after the rendering almost all the time, I have to click twice to draw a point of the polygon
I've noticed that too, but not only when the map is re-rendered. I think that this happens when you click and pan the map a bit. If you make sure you just click (making sure the mouse is not moving), it should work.

@ethervoid could you please try ☝️ ? Thanks!

**Comment by ethervoid** [comment]
Checked:

- Blank infowindow are waiting for response
- I've tested what you said about the polygon and seems to be that the reason why you have to do multiple clicks to draw a point for the polygon. 

In summary it seems to work as intended

**Comment by alonsogarciapablo** [comment]
Thanks!

**Comment by alonsogarciapablo** [comment]
I (luckily) found some issues when testing this in the context of the BUILDER:

- Tooltips where not being displayed correctly when they were multiple layers.
- Tooltip was not being displayed for features whose cartodb_id matched the cartodb_id of a feature from a different layer which had been clicked before (i.e: infowindow was visible).
- LeafletCartoLayerGroupView and GMapsCartoDBLayerGroupView were triggering events between the moment a layer was removed and interactivity was reloaded.
- InfowindowManager and TooltipManager were not managing infowindows/tooltips correctly when a layer was removed.

**Comment by alonsogarciapablo** [comment]
Hey! This ready for CR again!

@rochoa I basically added one commit (https://github.com/CartoDB/cartodb.js/pull/1549/commits/38667cb5db901c62e245606e0e9e7e8ae48fb4ad) to the code that we reviewed together. Do you mind taking a quick look? Thanks!

**Comment by alonsogarciapablo** [comment]
This is ready for acceptance again.

Easiest way to test this is to link BUILDER <=> deep-insights.js <=> cartodb.js and test it through the BUILDER. Steps:

1. Checkout all projects:
  - http://github.com/cartodb/cartodb
  - http://github.com/cartodb/cartodb.js
  - http://github.com/cartodb/deep-insights.js

2. Link all projects. Go to your projects folder and...
```
cd cartodb.js 
git checkout prep-work-for-gmaps-basemaps-4
npm link

cd ../deep-insights.js
git checkout master
git pull origin master
npm link
npm link cartodb.js

cd ../builder
git checkout master
git pull origin master
npm install
npm link cartodb-deep-insights.js cartodb.js
```

If you type `ls -l node_modules` in the `cartodb` project you should see something like:
```
...
lrwxr-xr-x   1 paul  staff   89 Jan 27 18:10 cartodb-deep-insights.js -> /usr/local/Cellar/node@0.10/0.10.48/libexec/npm/lib/node_modules/cartodb-deep-insights.js
drwxr-xr-x  11 paul  staff  374 Jan 27 17:49 cartodb-pecan
lrwxr-xr-x   1 paul  staff   75 Jan 27 18:10 cartodb.js -> /usr/local/Cellar/node@0.10/0.10.48/libexec/npm/lib/node_modules/cartodb.js
...
```
Notice that both `cartodb.js` and `cartodb-deep-insights.js` are links to the local projects.
Another way to make sure things are linked properly is to `cd node_modules/cartodb.js ` and make sure the `prep-work-for-gmaps-basemaps-4` branch is checked out.

3. Start BUILDER

```
// in your cartodb folder
grunt && grunt dev
```
Start the VM and restart the Rails server.

4. Acceptance:

- Make sure interactivity works as expected:
  - Setup some click/hover pop-ups in several layers. Make sure they work as expected:
    - Map cursor should change as you hover/out features.
    - It should work with multiple layers.
    - It should work properly when some layers are hidden.
  - Try to draw/edit existing features in different layers.

**Comment by jgoizueta** [comment]
Everything seems to be working fine.

Only thing I've noticed is that hover behaviour is slightly erratic for polygon layers with other visible layers on top, but it's exactly the same behaviour I've observed in production. (I think hover should only be effective for the top layer, but occasionally I've seen hover infowindows from polygon layers  below).
