### ISSUE TITLE
[Google Map Support] Layer selector is not working

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1548]
**STR:**

- Open the following example: http://localhost:9001/examples/v4/gmaps-layergroup.html.
- Hide the layer using the layer selector, by clicking on the layer name (european_countries_e).

**Expected results:**
- Layer is hidden.

**Actual results:**
- Blue bar appears and it stays there forever.
- Layer is not hidden.

Extracted from https://github.com/CartoDB/cartodb.js/pull/1538.

**Comment by dgaubert** [comment]
# Acceptance criteria:

- clone repo
- checkout `switch-to-gmaps`
- npm install
- bower install
- bundle install
- grunt dev
- open in your browser: http://localhost:9001/examples/v4/gmaps-layergroup.html:
![screen shot 2017-02-14 at 11 30 32](https://cloud.githubusercontent.com/assets/1936888/22925586/936ae7ea-f2a9-11e6-80a9-6a465a3f1811.png)
- Hide the layer using the layer selector:
![screen shot 2017-02-14 at 11 30 48](https://cloud.githubusercontent.com/assets/1936888/22925591/992fd3b6-f2a9-11e6-9cea-1aea73f16b6d.png)

Hope this help

**Comment by dgaubert** [comment]
@alonsogarciapablo I'm doing acceptance and I've just updated to the lasts changes and I got the following error:
```
Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at GMapsBaseLayerView._updateNativeMapOptions (gmaps-base-layer-view.js:34)
    at GMapsBaseLayerView.addToMap (gmaps-base-layer-view.js:22)
    at child._addLayerToMap (gmaps-map-view.js:110)
    at child._addLayer (map-view.js:204)
    at map-view.js:184
    at Function._.each._.forEach (underscore.js:153)
    at child.each (backbone.js:87)
    at child._addLayers (map-view.js:183)
    at child.render (map-view.js:118)
```
I'm getting `undefined` from: https://github.com/CartoDB/cartodb.js/blob/switch-to-gmaps/src/geo/gmaps/gmaps-base-layer-view.js#L34

Any clue??

**Comment by dgaubert** [comment]
It's working now:
![screen shot 2017-02-14 at 16 44 27](https://cloud.githubusercontent.com/assets/1936888/22936192/0556cccc-f2d5-11e6-9993-8b1c720d4bcf.png)
Hide:
![screen shot 2017-02-14 at 16 44 38](https://cloud.githubusercontent.com/assets/1936888/22936211/1365985c-f2d5-11e6-9722-325253dc3687.png)

That’s it! Can I do something extra to approve acceptance step?

**Comment by alonsogarciapablo** [comment]
I think we're good. Thanks @dgaubert!
