### ISSUE TITLE
sublayer.setInteraction() stop working after zoom/pan

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb.js#1559]
### Context
Trying to disable interaction for some sublayers fails after zoom/pan

CARTO.js v3.15.10

### Steps to reproduce
1. Open attached HTML file with the map.
1. **Move the map center**.
1. Click on _disable interaction_.
1. Click on features.

### Current result
Interaction works.

### Expected result
Interaction should stop working.

### Additional info

- Map: [set_interaction_with_two_sublayers.html.zip](https://github.com/CartoDB/cartodb.js/files/723891/set_interaction_with_two_sublayers.html.zip)

**Comment by alonsogarciapablo** [comment]
Hey! I removed myself from this issue since we should not assign issues to individuals. @rochoa we should instead prioritise it so that it gets into Our New Workflow:tm:

**Comment by donflopez** [comment]
It's an events thing, the bug area is very extense, wax, leaflet.js and cartodb.js. So is going to take time to have a conclusion and a fix.

**Comment by ernesmb** [comment]
closing here, I guess this is not going to be fixed in cartodb.js v3

cc/@donflopez
