### ISSUE TITLE
[Google Map Support] Zoom changes automatically after basemap provider changes and window is resized

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1571]
**STR:**

- Open a map.
- Change the basemap (Leaflet -> Google Maps or viceversa).
- Resize the window.

**Expected results:**
- Zoom should not change.

**Actual results:**
- Zoom is changed (to a very hight number).

**Comment by xavijam** [comment]
Yeah, I've already suffered this one. And if you try to change the zoom with the buttons, map starts to zoom in, then zoom out, then zoom it... ∞.

**Comment by donflopez** [comment]
Thanks for the tip!

**Comment by donflopez** [comment]
Fixed both behaviours, both of them caused for events, but different ones!

**Comment by donflopez** [comment]
Updated with a better event handling and an [explanation](https://github.com/CartoDB/cartodb.js/pull/1573#issuecomment-279369804) of the strange behaviour
