### ISSUE TITLE
Prep work for Leaflet 1.x migration

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1593]
Prep work for https://github.com/CartoDB/cartodb.js/issues/1503.

**Comment by rochoa** [comment]
This, along https://github.com/CartoDB/Leaflet.CanvasLayer/pull/24, https://github.com/CartoDB/torque/pull/284, and https://github.com/CartoDB/cartodb.js/pull/1594 will require passing the smoke tests.

So please, add anything relevant for the acceptance criteria.
