### ISSUE TITLE
Provide a method to get the URL of a static map image

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1595]
Related to https://github.com/CartoDB/cartodb/issues/10822.

CartoDB.js should provide a way to get the URL of an static image of the map. The Static Maps API provides [this functionality](https://carto.com/docs/carto-engine/maps-api/static-maps-api#zoom--center). We'll basically need to generate something like:

```
.../api/v1/map/static/center/{token}/{z}/{lat}/{lng}/{width}/{height}.{format}
```

The new method should accept the following arguments:

- Center (lat and lng)
- Zoom
- Format (.png or .jpg)
- Size in pixels (width x height).

We can provide some default values to make some of them optional.

Tasks/requirements:

- [x] Base (tiled and plain) and labels layers should be sent to the Maps API so that they can be included in the image.
- [x] When tiled/plain layers change, map should be instantiated again.
- [x] When tiled/plain layers are added/removed from the map, it should be instantiated again.
- [x] Image url must include authentication params (api_key / auth_token)
- [x] Image should not include hidden layers

cc: @javierarce

**Comment by alonsogarciapablo** [comment]
As part of this issue, the Static Maps API should accept a parameter to specify the layers that are included in the image (by index). CartoDB.js needs this so that the URL points to an image that only includes visible layers (cc: @rochoa).

**Comment by xavijam** [comment]
Passed to acceptance, being tested in cartodb/cartodb#10822-export-image branch.

**Comment by xavijam** [comment]
Acceptance passed! 💃 . Moved to deploy, and it will be done when it is deployed [here](https://github.com/CartoDB/cartodb/pull/11789#issuecomment-289392734).

**Comment by xavijam** [comment]
💃
