### ISSUE TITLE
URGENT: Strict MIME type checking breaks usage

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#1597]
See this post for details/reproduction (not by me) http://gis.stackexchange.com/q/232159/14129

Basically most vizs break in Chrome. See stocktonca.mapgeo.io, see the console log:

> Refused to execute script from 'https://stocktonca.carto.com/u/stockton-admin/api/v2/viz/d2f12b14-871f-11e5-bd1f-0ecfd53eb7d3/viz.json?callback=vizjson' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by alonsogarciapablo** [comment]
Thanks for reporting this @knownasilya! We're fixing it now.
