### ISSUE TITLE
Use subdomains on tiles requests

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1603]
At the moment we are using one subdomain to request the tiles so we are reaching the limit of request per subdomain easily.

Improve the way that we are using the URLs to use the new property template sent by maps api.

**Comment by donflopez** [comment]
Loading metrics in the builder with the use of subdomains vs without.

To make the "benchmark" I used:

- Incognito mode Chrome 59
- Storm points dataset
- One category widget

| *Case* | *Time Before* | *Time After* |
|--------|----------------|-------------|
| Initial load | 25.2s | 10.5s |
| Only user tiles avg | 12.8s | 2,3 |

**Comment by saleiva** [comment]
yay! I've been doing some tests. Some notes:
- I cannot reproduce the horrible effect that we had before when no tiles were loaded, and then after a while, everything loaded at the same time. Right now, even when there are blockings on the load, a few tiles are initially loaded so the feeling is way better.
- Blocks now are in less tiles, and less frequent. When they happen, the time looks to be spent in the waiting state and not in the stalled state.
