### ISSUE TITLE
getStaticImageURL method is not providing the valid URL with the subdomain

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1606]
We have checked in production the behaviour of the image-export doesn't work because we are not replacing in the cdn url the subdomain, so image url that is provided is, for example:

`https://ourcdn_%7Bs%7D.morefromourcdn/xavijam/api/v1/map/static/center/xxxxxxxxxxxxx:xxxxxxxxxx/3/37.57941251343841/-35.68359375000001/300/200.png?layer=0,1,2,3&api_key=heymiapikey`

**Comment by xavijam** [comment]
@alonsogarciapablo @donflopez

**Comment by alonsogarciapablo** [comment]
:(

**Comment by jorgesancha** [comment]
assigned to @alonsogarciapablo per @rochoa's request

**Comment by alonsogarciapablo** [comment]
I'm fixing it already 👍

**Comment by alonsogarciapablo** [comment]
## Acceptance

- Checkout the code in this branch
- Run `grunt dev` and visit: `localhost:9001/examples/v4/leaflet-layergroup.html`
- Open the console in your browser
- Type: `window.open(vis.getStaticImageURL())`
- You should see a static image of the map (and the URL should point to a valid subdomain)

**Comment by xavijam** [comment]
Acceptance passed!

**Comment by xavijam** [comment]
MERGED!
