### ISSUE TITLE
Using google maps provider, widget dataview first petition could request an invalid bbox

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1610]
Basically, fixing the bug related to https://github.com/CartoDB/cartodb/issues/11894, I have checked that sometimes widgets are not working properly due to they request the data using the not correct bbox, check image below:

![screen shot 2017-03-31 at 14 12 52](https://cloud.githubusercontent.com/assets/132146/24550035/8b335666-161c-11e7-8f75-c8d24b9b9c07.png)

Seems like Google Map is not ready and it returns `[[0, 0], [0, 0]]` for the current bounding box, and return data for that is empty, that's why the widget appears without anything :(:

```js
…
  _getBoundingBoxFilterParam: function () {
    var result = '';
    var boundingBoxFilter;

    if (this.get('sync_on_bbox_change')) {
      boundingBoxFilter = new WindshaftFiltersBoundingBoxFilter(this._map.getViewBounds());
      result = 'bbox=' + boundingBoxFilter.toString();
    }

    return result;
  },
…
```

It is likely we will need to "wait" until map provider is ready before requesting data from dataview models.

This bug is related to https://github.com/CartoDB/cartodb/issues/11894.

cc @rochoa @jorgesancha

**Comment by xavijam** [comment]
It is a bit random, because sometimes it works. Depends on if GMaps initialization is fast or slow.

**Comment by alonsogarciapablo** [comment]
This is hopefully fixed by https://github.com/CartoDB/cartodb.js/pull/1653. Let's reopen it if we see this problem again.

**Comment by xavijam** [comment]
🤞
