### ISSUE TITLE
Use of flyto for having the animation in vector with tangram

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1617]
As we talked offline, we prefer a bad performance with the zoom that looks broken.

cc/ @saleiva

**Comment by alonsogarciapablo** [comment]
I checked this in stating and found a couple of issues:

1. When the map is first loaded, CartoDB.js is setting the new zoom and now the map is being animated, which is something we're not doing before. It's kind of cool, but not sure everyone will like this.
2. Zoom is way slower with this change when rendering the map using good old raster tiles. It works perfectly fine for vector.

We should be able to tune this a bit more IMO. Perhaps we can keep things as they are for raster, and only use flyTo when using vector...

cc: @saleiva

**Comment by donflopez** [comment]
After a talk with @saleiva offline, we'll use flyto instead of setView, the animation is cool.

**Comment by alonsogarciapablo** [comment]
ok!
