### ISSUE TITLE
MapType is not a constructor when using createLayer with Google Map

### ISSUE THREAD

**Issue by voltagex** [CartoDB/cartodb.js#1622]
It appears I can't load a Carto layer over a Google Map any more.

https://codepen.io/voltagex/pen/QvLRjE

```
Uncaught TypeError: MapType is not a constructor
    at cartodb.uncompressed.js:41362
    at cartodb.uncompressed.js:41247
    at cartodb.uncompressed.js:27
```

I have tested Carto JS versions 3.15.8 and 3.15.11, plus Google Maps versions 3.27 and 3.25.

Edit: I've got an awful feeling that I'm doing something very silly.

**Comment by voltagex** [comment]
Uploaded file as requested via email [codepen_QvLRjE.zip](https://github.com/CartoDB/cartodb.js/files/916349/codepen_QvLRjE.zip)

**Comment by oriolbx** [comment]
Answering in SupportBee.
