### ISSUE TITLE
[CARTO Milestone] Improve our testing tools

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1649]
Avoid the use of [Phantom.js as a dead project](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), we have to improve our testing tools changing them for a fast alternative.

With Phantom.js dead, we have to use another alternative... I propose use karma with his Chrome launcher (using chrome driver) and other browsers allowing us to make the process faster and cross browser testing.

See [tangram-carto](https://github.com/CartoDB/tangram-carto/blob/master/package.json)

**Comment by xavijam** [comment]
I agree it would be a nice move.

**Comment by xavijam** [comment]
@rubenmoya and @rjimenezda are checking the Jest option @donflopez.
