### ISSUE TITLE
[CARTO Milestone] Remove jQuery

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1651]
I don't know why are we using jQuery, I'd study remove it.

**Comment by xavijam** [comment]
Take into account backbone needs/adds jQuery by default.

**Comment by donflopez** [comment]
I'm not sure about that, I think that the unique dep of backbone is underscore.

**Comment by donflopez** [comment]
underscore is his unique dep https://github.com/jashkenas/backbone/blob/master/package.json#L16

**Comment by xavijam** [comment]
:+1:

**Comment by nobuti** [comment]
I think jquery IS a dependency according to our use case.

> Backbone's only hard dependency is Underscore.js ( >= 1.8.3). For RESTful persistence and DOM manipulation with Backbone.View, include jQuery ( >= 1.11.0), and json2.js for older Internet Explorer support. (Mimics of the Underscore and jQuery APIs, such as Lodash and Zepto, will also tend to work, with varying degrees of compatibility.)

**Comment by donflopez** [comment]
ups, so we can't get rid of jQuery?

**Comment by nobuti** [comment]
AFAIK no, we can replace it with some lighter alternative with the same API, like zepto o dash, but even with that some flaws should be expected. Apart from that: https://github.com/jashkenas/backbone/wiki/using-backbone-without-jquery

**Comment by donflopez** [comment]
I see... we have to think about it, thank you @nobuti!
