### ISSUE TITLE
Infowindow Scroll Causes Map Panning

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1655]
@michellechandra commented on [Tue Apr 04 2017](https://github.com/CartoDB/support/issues/612)

### Context

* [SupportBee ticket](https://cartodb.supportbee.com/tickets/11647655)

The user opens a long click infowindow on her map. When attempting to scroll down to see the rest of the click infowindow, the map pans around moving position.

### Steps to Reproduce

Please see the user's map [here](https://chldcrezone.carto.com/builder/57c1552e-0e7b-11e7-b972-0ecd1babdde5/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.669441587473884%2C-73.91567230224611%5D%2C%22sw%22%3A%5B40.70471701226029%2C-73.84314537048341%5D%7D%2C%22widgets%22%3A%7B%22a242718c-47d4-44e4-af12-b6689e7ddcb4%22%3A%7B%22normalized%22%3Atrue%7D%2C%2224171563-b8e7-4df0-b657-7b5b42fe426f%22%3A%7B%22acceptedCategories%22%3A%5B%22Yes%22%2C%22No%22%5D%7D%2C%22705d46e7-2b84-414b-aafb-52a77c4ddc19%22%3A%7B%22normalized%22%3Atrue%7D%2C%2249f1953f-e125-4a2c-9beb-970f9b0069e3%22%3A%7B%22normalized%22%3Atrue%7D%7D%7D).

Create a click infowindow that has many columns causing the scroll bar to appear on the click infowindow.
Open the map in the latest Chrome browser and Mac OS.
Click on the click infowindow, hover over the scrollbar and attempt to scroll. The map will pan around as you attempt to see more of the click infowindow.

### Expected result

Map should not pan when user scrolls through contents of infowindow.

---

@xavijam commented on [Tue Apr 04 2017](https://github.com/CartoDB/support/issues/612#issuecomment-291615532)

Hey, I feel it is related with the last changes of Leaflet 1.0. We should stop the propagation of the move event within the infowindow content.

cc @alonsogarciapablo @donflopez @rochoa 

---

@michellechandra commented on [Wed Apr 26 2017](https://github.com/CartoDB/support/issues/612#issuecomment-297551536)

Hey @rochoa - is there any update on this issue? Thank you!

---

@alonsogarciapablo commented on [Thu Apr 27 2017](https://github.com/CartoDB/support/issues/612#issuecomment-297650387)

@michellechandra I just tried to reproduced this and it looks like it's working fine now.

![infowindow](https://cloud.githubusercontent.com/assets/390398/25474944/5be4496e-2b35-11e7-85ae-62bd4d0ef408.gif)

Could you please check it? Thanks!

---

@alonsogarciapablo commented on [Thu Apr 27 2017](https://github.com/CartoDB/support/issues/612#issuecomment-297650800)

I see. It only fails when you try to scroll by clicking on the scrollbar.

---

@michellechandra commented on [Thu Apr 27 2017](https://github.com/CartoDB/support/issues/612#issuecomment-297748906)

Yes, it fails when clicking on the scrollbar of the click infowindow...

---

@michellechandra commented on [Tue May 23 2017](https://github.com/CartoDB/support/issues/612#issuecomment-303529569)

Any update on this issue? :)

**Comment by alonsogarciapablo** [comment]
@michellechandra this issue has been prioritised and we'll fix it in the following days. Thanks for your patience!

**Comment by alonsogarciapablo** [comment]
Closed by https://github.com/CartoDB/cartodb.js/pull/1664. Deploying! 🚀

**Comment by alonsogarciapablo** [comment]
@michellechandra should be working now 😉 !

**Comment by xavijam** [comment]
Closing ok?

**Comment by alonsogarciapablo** [comment]
👍  Thanks!
