### ISSUE TITLE
Handle the load event

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1661]
Actually we are not supporting the loading bar, to support it we have to handle the load event properly.

**Comment by donflopez** [comment]
The changes are [here](https://github.com/CartoDB/cartodb.js/pull/1624/commits/7c18975801524eaaae18eeb57cfbed8cf8fc5375)

**Comment by alonsogarciapablo** [comment]
👍

**Comment by dgaubert** [comment]
Can I help with acceptance phase?

**Comment by alonsogarciapablo** [comment]
I think we can close this since it's released already, right @donflopez?

**Comment by donflopez** [comment]
Yes @alonsogarciapablo!
