### ISSUE TITLE
[Vector] Remove default styling properties for polygons that aren't supported for vector

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb.js#1670]
After talking with @donflopez and understanding the constraints of all default properties for polygon features blocking vector rendering, we decided, let's go ahead and remove them. 

These properties are specifically for smoother rendering between polygons and lines and are more important for things like choropleth maps. 

But with vector rendering, we are noticing better lines on the published map than with raster:

<img width="537" alt="screen shot 2017-06-12 at 8 47 02 am" src="https://user-images.githubusercontent.com/1566273/27039441-2e7a31b6-4f4b-11e7-9bf9-e2a86e245e1a.png">

In addition, anytime you change styling in the forms the `polygon-gamma` and `line-comp-op` properties are reset and no longer persist through to the users styling.

We can go ahead and remove the properties that are blocking and default to the CartoCSS below for polygon fills:

```
#layer {
  polygon-fill: #374C70;
  polygon-opacity: 0.9;
  line-color: #FFF;
  line-width: 1;
  line-opacity: 0.5;
}
```
Which with vector will look like this:
<img width="533" alt="screen shot 2017-06-12 at 8 45 08 am" src="https://user-images.githubusercontent.com/1566273/27039454-3b3be08e-4f4b-11e7-935d-952e09be74d1.png">

cc @saleiva

**Comment by makella** [comment]
And as mentioned in this issue (#1624) we should remove it from Auto-Style as well. 

I can do the PR if you need, just let me know!

thanks

**Comment by rochoa** [comment]
This is already done.
