### ISSUE TITLE
[Vector] Create console.log to show rendering method and stats

### ISSUE THREAD

**Issue by donflopez** [CartoDB/cartodb.js#1674]
To have a direct feedback about what rendering mode are we using, we'll use a console.log to show Vector or Raster text plus the number of features rendered if vector.

**Comment by donflopez** [comment]
PR -> https://github.com/CartoDB/cartodb.js/pull/1676

**Comment by dgaubert** [comment]
Hey! 

I wanna help with acceptance, could someone provide steps to validate it?

**Comment by dgaubert** [comment]
Nevermid!

I'm going to follow https://github.com/CartoDB/cartodb.js#how-to-build

**Comment by dgaubert** [comment]
Got it!

![screen shot 2017-06-27 at 15 47 09](https://user-images.githubusercontent.com/1936888/27590798-142ba392-5b50-11e7-8c05-b819fd6807b2.png)

![screen shot 2017-06-27 at 15 50 14](https://user-images.githubusercontent.com/1936888/27590888-6318aee6-5b50-11e7-927e-4dd8bbf734aa.png)

![screen shot 2017-06-27 at 15 51 08](https://user-images.githubusercontent.com/1936888/27590922-7cfb585e-5b50-11e7-9425-86418ff8363f.png)

![screen shot 2017-06-27 at 15 52 20](https://user-images.githubusercontent.com/1936888/27590979-a910ddce-5b50-11e7-973c-f53dc224a2ed.png)

It's ok, isn't it?
