### ISSUE TITLE
Cannot create a static map from a viz.json with a Torque layer

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1679]
@iaindillingham commented on [Mon Jun 12 2017](https://github.com/CartoDB/cartodb/issues/12306)

### Context
Cannot create a [static map][] from a viz.json with a Torque layer.

[static map]: https://carto.com/docs/carto-engine/carto-js/static-maps

### Steps to Reproduce
Paste the following into a new HTML file.
```
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.15/themes/css/cartodb.css">
  </head>
  <body>
    <div id="map"></div>
    <script src="http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>
    <script>
      var url = "https://vm-gis.carto.com/api/v2/viz/bbff1084-146c-11e7-a697-0e3ff518bd15/viz.json";
      cartodb.Image(url).size(256, 256).write();
    </script>
</html>
```
### Current Result
See your browser's developer console. Two requests -- one post, one get -- that originate within _cartodb.js_ 404. The response from the post request reads _layergroup GET needs a "config" parameter_.

### Expected result
I expected the `script` tag to be replaced with an `image` tag.

### Browser and version
Firefox 53.03.

---

@xavijam commented on [Mon Jun 19 2017](https://github.com/CartoDB/cartodb/issues/12306#issuecomment-309488300)

Hi @iaindillingham, but that functionality belongs to our JS library CartoDB.js. Let me move the ticket to the proper repository 🤗 .

**Comment by jsanz** [comment]
@iaindillingham I see on your viz.json that you have two torque layers defined, maybe that's your issue? You should only have one torque layer per CARTO map. I see on your example an error coming back from the Maps API.

![2017-06-20_10 42 58-selection](https://user-images.githubusercontent.com/188264/27324355-42bb76de-55a5-11e7-9338-160b769685fa.png)

I tried with my own torque map [here](http://plnkr.co/edit/ug9GcDBeaMR0jLaNY4Wq?p=preview) and it's apparently working fine.

**Comment by iaindillingham** [comment]
Thank you @jsanz and sorry for taking awhile to get back to you. I've asked our GIS folks to define only one torque later per CARTO map.
