### ISSUE TITLE
Fail to load cartodb.js from bower with Angularjs and Webpack

### ISSUE THREAD

**Issue by caiquexavier** [CartoDB/cartodb.js#1681]
Hi, I'm trying to load cartodb.js module inside my app from the bower install, and getting loading errors.
Google chrome shows me:
cartodb.js?eb95:3 Uncaught TypeError: Cannot read property 'jQuery' of undefined
and Firefox get this error:
typeError: root is undefined
Both came from cartodb.js says the console.

How can i inject cartodb.js as a module in my application? Like i'm doing for every other thirdy part plugins by ES6 import?

Here's my code of importing modules (all modules work fine, justo cartodb.js not):

import angular from 'angular'
import ngRedux from 'ng-redux'
import '../../bower_components/cartodb.js/themes/css/cartodb.css'
import cartodb from '../../bower_components/cartodb.js/cartodb.js'
//   Css Loaders
import '../style/app.css'
import '../../node_modules/angular-material/angular-material.css'
import '../../node_modules/angular-material-data-table/dist/md-data-table.min.css'

//  Import External Dependencies
import '../../node_modules/@uirouter/angularjs/release/angular-ui-router.min.js'
import '../../node_modules/angular-aria/angular-aria.js'
import '../../node_modules/angular-animate/angular-animate.js'
import '../../node_modules/angular-material/angular-material.js'
import '../../node_modules/angularfire/dist/angularfire.min.js'
import '../../node_modules/angular-material-data-table/dist/md-data-table.min.js'
import '../../bower_components/angular-toArrayFilter/toArrayFilter.js'

**Comment by alonsogarciapablo** [comment]
@caiquexavier This version of cartodb.js cannot be imported as a module :(. We're currently working on the next version of the library, and we'll make sure we support this. Sorry for the inconvenience!
