### ISSUE TITLE
util.isWebGLSupported fails to detect disabled hardware acceleration

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb.js#1683]
![screen shot 2017-06-23 at 17 20 51](https://user-images.githubusercontent.com/45346/27488806-a65e1a1c-5838-11e7-9131-3fc13e7db30e.png)

The previous image shows how to disable hardware acceleration in Google Chrome.

In that case, `window.WebGLRenderingContext` will exist. However, it will fail to get a valid context for `webgl`.

**Comment by alonsogarciapablo** [comment]
Fixed in https://github.com/CartoDB/cartodb.js/pull/1684.
