### ISSUE TITLE
[vector] Vector rendering is not working for this map

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1696]
Vector rendering was enabled for @makella's personal account and we discovered that the following map wasn't working:

https://mamataakella.carto.com/builder/e623bb0c-b2fd-11e5-b55f-0ea31932ec1d/embed 

There're [multiple errors in track.js related to this bug](https://my.trackjs.com/search?query=Error%20building%20tile%20CartoDB%2F). It's something related to Tangram.

We disabled vector rendering for that account while until we figure out what the problem is.

cc: @makella @rochoa @xavijam

**Comment by makella** [comment]
@alonsogarciapablo if there is anything i can do to help out testing, etc. please let me know :)

**Comment by javisantana** [comment]
more maps that don't work:

https://javi.carto.com/builder/5e8101bc-76d1-11e6-97f1-0ee66e2c9693/embed

**Comment by ramiroaznar** [comment]
Same issue for a couple of maps: https://github.com/CartoDB/support/issues/857

**Comment by IagoLast** [comment]
Can someone attach the .carto files.

I wanna try to figure out whats happening here

**Comment by ramiroaznar** [comment]
Hey @IagoLast you can find mine here CartoDB/support#857

**Comment by makella** [comment]
here's mine. thanks!!
[cholera blog (on 2017-07-26 at 13.28.24).carto.zip](https://github.com/CartoDB/cartodb.js/files/1176686/cholera.blog.on.2017-07-26.at.13.28.24.carto.zip)

**Comment by ramiroaznar** [comment]
Hey @IagoLast, the same is happening to [this map](src="https://team.carto.com/u/mehak-carto/builder/53a472bc-a03c-11e6-9981-0e8c56e2ffdb/embed) which is shown in [this guide](https://carto.com/learn/guides/styling/style-by-value). A guide btw which is viewed and used by our users a lot.

**Comment by rochoa** [comment]
Hey @ramiroaznar,

That guide should keep working, so, why don't you disable the vector rendering for the user associated with the examples used there?

**Comment by ramiroaznar** [comment]
Going to do that. @mehak-sachdeva is the owner. So I am going to disable the vector feature flag from her account. cc @csobier @namessanti

**Comment by ramiroaznar** [comment]
It is working again.

**Comment by csobier** [comment]
Thank you @ramiroaznar !

**Comment by IagoLast** [comment]
Regarding to @makella 's map https://github.com/CartoDB/tangram-carto/issues/55#issuecomment-321796041

**Comment by alonsogarciapablo** [comment]
Map is working now so closing this issue!
