### ISSUE TITLE
[vector] rendering reporting no estimated rows but the metadata contains full information

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#1697]
- Load this map https://team.carto.com/u/javi/builder/74bb971d-5554-459a-b67d-92834dec63a0/embed
- Check estimatedFeatureCount in instanciation response, all the layers have the estimatedFeatureCount
- rendering is fallback to raster and reports no-estimatedrowcount

**Comment by matallo** [comment]
🚀
