### ISSUE TITLE
vector rendering error with line-offset 

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb.js#1700]
@alonsogarciapablo heyyy

so I am working on some maps for a client and I have the property `line-offset` being used. Previously there wasn't an issue, but the map has been embedded in a custom website and is loading but with errors:

`[Vector] Unable to render due ":318:2 Unrecognized rule: line-offset".`

The weird thing is that this is happening on 2 out of the 4 maps that use `line-offset`.

Since these are client maps that are still in production, can't share publicly but let me know if you have some time to look at this and I can send you the maps and the website link.

thanks!
mamata

cc @isabelgarate @xavijam @rochoa

**Comment by rochoa** [comment]
That only means that `line-offset` is not supported by vector rendering, but the map should render using raster.

For a complete list of supported properties, check https://github.com/CartoDB/tangram-reference/blob/e475d86ec66f778889f25139ef71fda98bb93bc9/1.0.0/reference.json.

**Comment by makella** [comment]
totally but in the website (external) that a map is published inside of, the map draws but their status icon is still thinking... i'll email you the website if that's ok
