### ISSUE TITLE
JS error is being thrown when infowindow is image type

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1703]
## STR
- Create a map of points.
- Go to the layer, and add a string column.
- Add some image urls in those fields.
- Go to Popup tab and select the image type.
- Select all fields, but move the column containing image urls to the top.
- Open the browser console.
- Click over a point and check that the console throws an error.

**Comment by xavijam** [comment]
Work done in ```underscore-problem``` branch.

**Comment by xavijam** [comment]
Related ticket -> https://github.com/CartoDB/cartodb.js/issues/1314

**Comment by rubenmoya** [comment]
In production 🚀

**Comment by xavijam** [comment]
@rubenmoya, don't forget to close the ticket!
