### ISSUE TITLE
Improve legend error state for supporting several error types

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1715]
When there is an error in the Maps API and legends can be rendered (taking into account that legend is "live", not static), we display an error saying "Data not available", or "There has been an error".

From now on we should be more concrete about the problem. We should catalog those by:

- Data error: data or map instantiation returned an error and we should display it.
- Limits error: the user has reached its platform limits, so we should decide if the error message should change or not (**let's not forget this will be public in the embed page**).

## Design

_TDB_ -> @CartoDB/design -> https://github.com/CartoDB/cartodb-platform/issues/3278#issuecomment-321762059

*Related tickets for design purposes: https://github.com/CartoDB/cartodb-platform/issues/3278, https://github.com/CartoDB/cartodb-platform/issues/3279
*We have to do the same with widgets in Deep-Insights.js (https://github.com/CartoDB/deep-insights.js/issues/574).

**Comment by rubenmoya** [comment]
Right now we have a `Something went wrong`, in red, without placeholder. Should we keep that and use the `Legend unavailable` error with placeholder just for limits? or use it for both, generic errors and limits? cc @CartoDB/design

**Comment by arianaescobar** [comment]
`Legend unavailable` in yellow only for limits and `Something went wrong` in red for every other error.

**Comment by rubenmoya** [comment]
Tank you for answering @arianaescobar! I've been doing some research and I found out we can't have limits error in legends because how they work, they can fail only in 2 places:

- **Map instantiation:** The map won't load, so the legend won't load either, no error message needed.
- **CartoCSS parse error:** The widget will show the `Something went wrong` error.

All the legend information is in the `viz.json`, so there are no requests needed to show it, the limits won't affect us here.

So, what should we do? Keep everything as it is, or improve the message/design in some way now that we have more information?

**Comment by arianaescobar** [comment]
Hmm, interesting... 

Just to understand the error, what would "fix" the CartoCSS parse error?

**Comment by rubenmoya** [comment]
We generate it automatically when the user creates/edits the legend, so it shouldn't fail unless the user changes it manually in the `Styles -> CartoCSS` section, and it has a validation, so it's unlikely to happen, so probably the fix will be us fixing our bugs :P

**Comment by arianaescobar** [comment]
Ok so, a few more questions: 

- In the CartoCSS parse error, can we show different error messages whether you're seeing the legend from Builder or from the public page? 
- In the Map Instantiation error, does the legends' white <div> is visible or not?

**Comment by rubenmoya** [comment]
1. No, we can't
2. No, the map won't load at all

**Comment by arianaescobar** [comment]
Ok, thanks. 

Then let's go with "Something went wrong" in red.

**Comment by dgaubert** [comment]
# Acceptance steps (staging)

1. Go to [central](https://carto-staging.com/superadmin) and login as `full-admin`.
2. Search for an existent user or create a new one. 
3. Click `edit user`
4. Change the following properties:
  - `Timeout for user queries`: 500 (0.5 sec), 
  - `Timeout for public queries`: 500 (0.5 sec).
  - `Timeout for authenticated tile-rendering`: 0 (deactivated),
  - `Timeout for public tile-rendering`: 0 (deactivated)
5. Save changes (click `update user`)
6. Open a new browser's tab and login with user's credentials.
7. Create a new map with `populated_places_simple` dataset.
8. Style size/color of points by `pop_max` value:
![screen shot 2017-09-25 at 11 50 48](https://user-images.githubusercontent.com/1936888/30802749-d42ca730-a1e7-11e7-9fa2-717153661d76.png)
9. Edit `sql` for the layer:
  9.1 Go to `data` section of the layer.
  9.2 Open `expert-mode` and edit the sql as follows:
    - `SELECT *, pg_sleep(1) FROM ne_10m_populated_places_simple` =>`SELECT *, pg_sleep(1) FROM ne_10m_populated_places_simple`.
  9.3 Apply query.
10. Check that `No data available` message is displayed in legends.

HTH.

**Comment by piensaenpixel** [comment]
waiting for staging

**Comment by piensaenpixel** [comment]
@dgaubert i can't reproduce it :(
SQL is loading .... and nothing happened

![image](https://user-images.githubusercontent.com/1214201/30829630-a6ec4320-a241-11e7-84b2-5c7dc705f9f6.png)

**Comment by rubenmoya** [comment]
It's not deployed, only the tile overlay is, they are different PRs

**Comment by dgaubert** [comment]
OMG! 😱 

<img width="333" alt="screen shot 2017-09-26 at 08 48 07" src="https://user-images.githubusercontent.com/1936888/30846618-a98dcc78-a298-11e7-88ad-3df7d72f0f93.png">

Sorry, I wasn't as precise as I should. 

The SQL that you have used is actually two queries separated by `=>`. I just wanted to show the transition from default query to the query that we need to throw `timeout errors`.

This is the SQL that you have to use:

`SELECT *, pg_sleep(1) FROM ne_10m_populated_places_simple`.

**Comment by xavijam** [comment]
I'll take this acceptance, let's speed up it!

**Comment by xavijam** [comment]
Deployed in production!
