### ISSUE TITLE
Implement new map overlay for displaying when platform limits have been reached

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1716]
Scenario, the user has reached its platform limits, and data tiles (#XXXX) start to not appear. We need to warn the user that something is happening due to its account.

So, the idea is to create a new "map overlay" for warning him/her. It should be placed close to the search one. There will not be the possibility to disable it from the map options. 

##  Design

![27280402-12fe9e0c-54e8-11e7-9c87-1211a7c44a69](https://user-images.githubusercontent.com/132146/29207126-4b809278-7e85-11e7-8c93-86a584ca2ab5.png)

![27280398-0f9be7f6-54e8-11e7-9f7f-f9e99c93b734](https://user-images.githubusercontent.com/132146/29207139-5844176e-7e85-11e7-95a2-a38b7d8b3e20.png)

**Comment by rubenmoya** [comment]
Hey @CartoDB/design where I can get the warning icon?  It's not available in `CDB-Shape` :(

**Comment by josecruz** [comment]
@rubenmoya Sorry! Here you have:
[icon-alert.svg.zip](https://github.com/CartoDB/cartodb.js/files/1264307/icon-alert.svg.zip)

**Comment by urbanphes** [comment]
@rubenmoya 
is this okay?

**Comment by rubenmoya** [comment]
@urbanphes Yes, it's perfect, thank you!

**Comment by nobuti** [comment]
Closed by #1725
