### ISSUE TITLE
Replace browserify by webpack and fix bundling issues

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1736]
- [x] Migrate from browserify to webpack to be consistent with other projects (eg: http://github.com/cartodb/cartodb)
- [x] Fix bundling issues (eg: bundle depends on window variables like wax). Make sure other projects can require this library easily.
- [x] Add Promise polyfill
- [x] Enable npm publish
- [x] Update the deploy system
- [x] Publish to our cdn

**Comment by Jesus89** [comment]
- [ ] Enable npm publish
- [ ] Update the deploy system
