### ISSUE TITLE
Setup JSDoc

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1741]
The plan is to document public API methods using JSDoc. We should set up a script to generate the documentation at any given time.

See https://github.com/CartoDB/cartodb.js/pull/1640 for some inspiration.

We could "publish" the docs using [Github Pages](https://pages.github.com/) so that we can check them anytime while the library is being changed!

cc: @csubira

**Comment by Jesus89** [comment]
Closed by #1769
