### ISSUE TITLE
Remove support for ListDataviews

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1756]
Part of https://github.com/CartoDB/cartodb/issues/12826.

List Dataviews are being used at the moment so they can safely be removed from the code base:

- [x] Remove https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/list-dataview-model.js and its tests.
- [x] Remove [method to create ListDataviews from Dataviews factory](https://github.com/CartoDB/cartodb.js/blob/v4/src/dataviews/dataviews-factory.js#L83-L94).

**Comment by IagoLast** [comment]
@rochoa is including this changes in https://github.com/CartoDB/cartodb/pull/12835

**Comment by alonsogarciapablo** [comment]
👍
