### ISSUE TITLE
JSDoc: implement mechanism to separate internal docs from public facing docs

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1764]
We should support different levels of privacy and more specifically we need to have a way to specify which classes / methods / functions are part of the public facing API, which ones are "public" and which ones are "private". OpenLayers have solved this by defining their own @api tag (eg: https://github.com/openlayers/openlayers/blob/master/src/ol/map.js#L87).

cc: @Jesus89

**Comment by Jesus89** [comment]
I think we could use this @api tag, so we could have:
```
npm run docs
npm run docs:all
```
