### ISSUE TITLE
Remove analysisCollection from AnalysisService

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb.js#1789]
Analysis models will now be referenced directly by some layer models and dataview models (implemented in `sources-as-references`). That's the reason why we're getting rid of the internal `AnalysisCollection` and it's the reason why [`AnalysisFactory#analyse`](https://github.com/CartoDB/cartodb.js/blob/v4/src/analysis/analysis-factory.js#L27) shouldn't need to add nodes to AnalysisCollection.

For now, we'll keep this method as the public (as in "API" public) way of generating an analysis tree from an analysis definition. We'll rethink the API to manage analysis in the near future.

**Comment by Jesus89** [comment]
Done in https://github.com/CartoDB/cartodb.js/issues/1790
