### ISSUE TITLE
Integrate remove-analysis-collection

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1796]

**Comment by IagoLast** [comment]
We decided to keep using the `engine` internally:
```javascript 
// namespaced under `analysis` 
vis.analysis.findNodeById = function(id){
  return engine.findNodeById(id);
}
```


engine also delegates the call:
```javascript 
engine.findNodeById = function(id){
  return AnalysisService.findNodeById(id, this.layersCollection, this.dataviewsCollection);
}
```

**Comment by Jesus89** [comment]
Integrates #1790, #1763, #1787, #1793, #1788, #1789

Related PRs:
- CARTO.js: https://github.com/CartoDB/cartodb.js/pull/1821
- deep-insights: https://github.com/CartoDB/deep-insights.js/pull/606
- CartoDB: https://github.com/CartoDB/cartodb/pull/12947

**Comment by Jesus89** [comment]
In production! :rocket:
