### ISSUE TITLE
Scroll in image popup is not correct

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#1800]
The problem comes from recent changes over all scrollbars.

![](https://user-images.githubusercontent.com/132146/31110176-638504ea-a805-11e7-8895-f9cb19a4e30e.png)

https://github.com/CartoDB/cartodb/pull/12877

cc @CartoDB/frontend

**Comment by Jesus89** [comment]
Now cartodb points to custom branches: https://github.com/CartoDB/cartodb/blob/411cc625b97c6ed3b447af1237ca92c77a92f122/package.json#L27-L29

Pointing to v4 and master (cartodb.js, deep-insights.js) will solve the issue.
