### ISSUE TITLE
Refactor gmaps fix

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb.js#1816]
Related to: #1798
Merged PR: #1803
Pending PR: #1813

Summary
-----

To handle click events in the maps, we need to provide a way to transform click events into spatial coordinates.

Currently we got a hack, creating a fake [Overlay view](https://developers.google.com/maps/documentation/javascript/3.exp/reference#MapCanvasProjection)  attached to the map.

This overlay view is not initialised until the draw method is called, causing several concurrency problems in our tests (and potentially in the code).

The [PR](#1813) was intended to use two simple functions using a [map projection](https://developers.google.com/maps/documentation/javascript/3.exp/reference) instead an overlay view. This is less error prone and IMO the code is much easy to understand. One function to transform Point into a LatLong object and vice-versa (@IagoLast)

- [x] Confirm both methods are equivalent: NO
- [x] Maybe using this method the tests don't need to wait for the `idle` event: NO

**Comment by IagoLast** [comment]
Maybe using Zera we can make the events to have both pixel and lat-lon coords.

**Comment by Jesus89** [comment]
The current functions:
```js
google.maps.OverlayView()
-> getProjection().fromLatLngToContainerPixel(latlng)
-> getProjection().fromContainerPixelToLatLng(latlng)
```

Are not the same than:
```js
google.maps.Map()
-> getProjection().fromLatLngToPoint(latlng)
-> getProjection().fromPointToLatLng(latlng)
```

Also, the `idle` event is required to ensure that map.getBounds() is not null.

**Comment by IagoLast** [comment]
what the differences are?

**Comment by Jesus89** [comment]
I have tested manually with the same inputs. I don't know the internals but they are different for sure.

**Comment by IagoLast** [comment]
From the doc `fromLatLngToContainerPixel`returns the pixel relative to the map container while fromLatLngToPoint returns the pixel relative to screen. right?

**Comment by Jesus89** [comment]
> Computes the geographical coordinates from pixel coordinates in the map's container.

vs

> Translates from the LatLng cylinder to the Point plane. This interface specifies a function which implements translation from given LatLng values to world coordinates on the map projection. The Maps API calls this method when it needs to plot locations on screen. Projection objects must implement this method.

**Comment by Jesus89** [comment]
Closed here: https://github.com/CartoDB/cartodb.js/pull/1945
