### ISSUE TITLE
Make internal classes public: Layers, Sources, Styles

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1825]
Developers should be able to do something along the lines of:

```
var countriesDataset = new carto.source.Dataset('european_countries_e');
// or countriesDataset = new carto.source.SQLQuery('SELECT * FROM european_countries_e LIMIT 1');

var countriesStyle = new carto.style.CartoCSS([
  '#layer {',
  '  polygon-fill: #333333',
  '}'
].join('\n');

var countriesLayer = new carto.layer.CartoLayer({
  id: 'countries',
  source: countriesDataset,
  style: countriesStyle
});
```

☝️ This is just an initial suggestion and we should discuss it before implementing it.

Things to discuss:

- Is `carto.source` a good "namespace"?
- Declaring CartoCSS styles programmatically using plain strings is a bit painful. Somebody suggested using something like https://github.com/cssinjs/jss#example. We should consider it.
- For the initial release, developers will only be able to use layers of type "CartoDB" ([this model](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map/cartodb-layer.js)). Should we keep others private?
- Right now some of these models are created via factory methods that inject them an instance of the `vis` / `engine` model. In order to simplify the public API, developers should be able to create these objects without these dependencies and CARTO.js should "complete" these objects on-the-fly.

**Comment by Jesus89** [comment]
https://docs.google.com/document/d/1pzgsWDnKii-7ROwqOQsCln7pz2EAOZkwirzt1vmqTms/edit?ts=59e76da8#heading=h.eilx4ykmr119

**Comment by Jesus89** [comment]
We will use https://github.com/CartoDB/CartoJSS to declare CartoCSS styles programmatically.

**Comment by Jesus89** [comment]
The final API should look like this:

```javascript
var countriesSource = new carto.source.Dataset('european_countries_e');
// countriesSource = new carto.source.SQL('SELECT * FROM european_countries_e LIMIT 1');

var countriesStyle = new carto.style.CartoCSS({
  '#layer': {
    'polygon-fill': '#333333',
  }
});

var countriesLayer = new carto.layer.CartoLayer(countriesSource, countriesStyle, {
  featureClickColumns: ['columnA', 'columnB'],
  featureOverColumns: ['columnB']
});
```

**Comment by IagoLast** [comment]
2 things.

1. Constructors should belong to a "static" object.
`new Carto.foo()` instead `new carto.foo``

2. Maybe we should expose factories instead constructors.
`let foo = Carto.foo()` instead `let foo = new Carto.foo()`

**Comment by Jesus89** [comment]
The capital letter is in the Foo: `new carto.Foo()`. We have talked about Factories but we are going to use by now a factory only in L.cartoLayerGroup.

**Comment by IagoLast** [comment]
This is outdated
