### ISSUE TITLE
Show map overlay when mvt request fails

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb.js#1849]
The overlay is already there, we just have to show it using [this method](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/ui/overlays-view.js#L114)

This depends on https://github.com/CartoDB/tangram.cartodb/issues/18

![screen shot 2017-08-31 at 11 10 31](https://user-images.githubusercontent.com/905225/29915754-0b549ee8-8e3d-11e7-895d-96c12bbda662.png)
![screen shot 2017-10-31 at 13 12 57](https://user-images.githubusercontent.com/905225/32223347-436136e0-be3d-11e7-9bf7-f0b6cafae996.png)

**Comment by rubenmoya** [comment]
So, as we talked yesterday, in raster we're just showing the tile error, no infobox, no overlay. Since we're only showing it with vector right now, and in this case we know 100% sure it's because of limits, should we bring back the link to the documentation and use a more specific message?

![screen shot 2017-08-31 at 11 10 35](https://user-images.githubusercontent.com/905225/29915755-0b58e372-8e3d-11e7-93d3-4f4ce5fe58b7.png)

cc @noguerol

**Comment by noguerol** [comment]
Indeed, vector notifications should include a link to a highlight in the docs that points to the probably origin of the problem and the way to fix it (contacting support)

**Comment by rubenmoya** [comment]
In production! 🚀
