### ISSUE TITLE
Manage internal engine

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb.js#1868]
While Testing the public api some inconsistencies have been discovered.

## Limitations: 

- A style belongs to N layers
- A source belongs to N layers*
- A source belongs to N Dataviews*

- A layer belongs to 1 engine
- A dataview belongs to 1 engine

- An engine has n Layers
- An engine has n datavies

- A layer has 1 source
- A layer has 1 style
- A dataview has 1 source

- A layer and its source must share the same engine instance.
- A dataview and its source must share the same engine instance.

## Adding a source to a layer/dataview

```
IF the Layer has not been instantiated:
  - Add the source to the layer
IF the layer has been instantiated:
  IF the source has no engine:
    - Add the source to the layer
  IF the source has an engine:
    IF source.engine === layer.engine
      - Add the source to the layer
    IF source.engine !== layer.engine
      - Throw an error.
```

## Todo
- [x] Agree on this limitations and pseudocode.
- [x] Test every situation to ensure the api is consistent.

**Comment by IagoLast** [comment]
New case discovered [here](https://github.com/CartoDB/cartodb.js/pull/1864#discussion_r149650056)

**Comment by IagoLast** [comment]
```
IF the Layer has not been instantiated:
  IF the source has no engine:
    - Add the source to the layer
  IF the source an no engine:
    -> new case! Check the engine is the same when the layer is added to a client
IF the layer has been instantiated:
  IF the source has no engine:
    - Add the source to the layer
  IF the source has an engine:
    IF source.engine === layer.engine
      - Add the source to the layer
    IF source.engine !== layer.engine
      - Throw an error.

```

**Comment by IagoLast** [comment]
@Jesus89 we need to revisit and decide what to do before setting the final api.

**Comment by Jesus89** [comment]
Done here: https://github.com/CartoDB/cartodb.js/issues/1907
