### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1869]
- [x] Argument errors (eg: wrong or missing params for API method)
  - [x] Layers
  - [x] Dataviews
  - [x] Sources (Dataset / SQL)
  - [x] Style
- [x] Define a `CartoError` object (only has a message property for now).
- [x] `carto.Client` triggers `error` (with `CartoError`) for:
  - [x] Global Errors (instantiation errors)

**Comment by IagoLast** [comment]
To expose windshaft errors through the client we must change how the engine works.

**Comment by IagoLast** [comment]
### Error list

- [ ] Client initialized with no api key

**Comment by alonsogarciapablo** [comment]
- Methods that trigger an engine reload return promises (Client, Layer, Source, Dataviews). Promises are rejected with a `CartoError`
- Individual objects (Layer, Source, Dataviews) trigger an `error` message with a `CartoError` as argument.
- `carto.Client` triggers `error` event with `CartoError`.
- `CartoError` only has a message property for now.
