### ISSUE TITLE
Error handling 3

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1892]
We should revisit error handling both internally and externally.

### Internally
- [ ] List all possible errors.
  - [ ] Generate a list with all the possible `windshaft`errors: (sources,  cartocss, auth, limits..)
  - [ ] Generate a list with all the possible `network` errors. (server down, connection lost)
  - [ ] Generate a list of potential common `runtime` errors. (not very common, maybe a malformed json?)
  - [ ] Generate a list of `validation` errors.
- [ ] Understand how BUILDER/deep-insights.js are consuming errors from CARTO.js
- [ ] Update the `cartoError` class and create a hierarchy with well defined messages.

### With this hierarchy.

* **Client**
  * Triggers ALL errors.
  * `.addLayer` return a promise with a cartoError when something goes wrong.
  * `.addLayers` return a promise with a cartoError when something goes wrong.
  * `.removeLayer` return a promise with a cartoError when something goes wrong.
  * `.removeLayers` return a promise with a cartoError when something goes wrong.
  * `.addDataview` return a promise with a cartoError when something goes wrong. 
  * `.addDataviews` return a promise with a cartoError when something goes wrong. 
  * `.removeDataview` return a promise with a cartoError when something goes wrong. 
* **Layer**
  * Triggers all `layer_related`errors.
  * `.setSource` return a promise with a cartoError when something goes wrong.
  * `.setStyle` return a promise with a cartoError when something goes wrong.
* **Source**
  * Triggers all `source` related errors.
  * **SQL**
    * `.setQuery` return a promise with a cartoError when something goes wrong.
* **CartoCSS**
  * Triggers all `cartocss`related erros.
* **Dataview**
    * Triggers all `source` related errors.
    * Triggers all errors from Windshaft requests.
    * Triggers all validation errors from dataview parameters.

**Comment by IagoLast** [comment]
@ivanmalagon we need to complete the list with the async methods in the dataviews.

**Comment by ivanmalagon** [comment]
Working on it

**Comment by IagoLast** [comment]
@ivanmalagon IMO we should update the possible `dataview` errors first and then follow the list order .

**Comment by ivanmalagon** [comment]
The `dataviews` error list is already updated. They capture and trigger an error when their sources have a problem, trigger their own validation errors (`bins` not being a number, f.i.) and triggers all errors that come from Windshaft. That's it.

**Comment by ivanmalagon** [comment]
#### Client

- `layer.setFeatureOverColumns(['adm0name', 'tucutu']);`: set an invalid column name. Windshaft throws a layer error.

#### Layer
- Validation errors
    - Non valid style.
    - Non valid source
    - Source with different client.
- Windshaft
    - Unrecognized rule in CartoCSS

**Comment by alonsogarciapablo** [comment]
As part of this issue, I think it would be :top: if every class that communicates with Windshaft wrapped JSON reponses from Windshaft into a WindshaftError (eg: [here](https://github.com/CartoDB/cartodb.js/blob/error-handling-3/src/windshaft/client.js#L66)). It would simplify things I think.
