### ISSUE TITLE
Get rid of internal model listeners

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb.js#1896]
As commented by @alonsogarciapablo  and discussed by @Jesus89 and the one and only @ivanmalagon we can get rid of the internal model listeners in internal dataview for properties that are being set by the wrapper object.

**Comment by IagoLast** [comment]
Let me know if im wrong.

we should remove the `_listenToInternalModelSpecificEvents` function and instead attaching a listener when the internalModel is changed we should trigger the `xxxChanged` event on the setter right?

**Comment by ivanmalagon** [comment]
We have a method called `._listenToInternalModelSpecificEvents` in every implementation of a dataview. It's listening to the same options that we can set for everyone:
- Histogram: we listen to
  - `change:bins`
- Formula: we listen to
  - `change:operation`
- Category: we listen to
  - `change:categories`
  - `change:aggregation`
  - `change:aggregation_column`

These listeners are only there to sync that internal model state with the wrapped one. But, we can only change those properties through the wrapped one, so it doesn't make any sense to listen for those specific events.

We did that being paranoid of something changing the internal models under the hood but thinking about that, it's not possible.

So we can get rid of listening to those specific changes.

Take into account that we should trigger `xxxChanged` events anyway. Now they're triggered as part of those listeners to be removed.

**Comment by IagoLast** [comment]
should we trigger the ' xxxChanged'  asynchronously?

```javascript
Formula.prototype.setOperation = function (operation) {
  this._checkOperation(operation);
  this._operation = operation;
  if (this._internalModel) {
    this._internalModel.set('operation', operation, { silent: true });
    return this._internalModel._engine.reload()
      .then(function () {
        this.trigger('operationChanged', this._operation);
      }.bind(this));
  }
  return Promise.resolve();
};
```

 or synchronous at the moment the attribute is changed?

```javascript
Formula.prototype.setOperation = function (operation) {
  this._checkOperation(operation);
  this._operation = operation;
  this.trigger('operationChanged', this._operation);
  if (this._internalModel) {
    this._internalModel.set('operation', operation);
  }
  return this;
};
```

**Comment by ivanmalagon** [comment]
Synchronous. The attributes is already changed even if the operation fails, so if other model / object wants to know if the value has changed, it should be notified anyway.
