### ISSUE TITLE
Rename error type for torque erroTile

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb.js#1903]
We made a workaround to solve this but we should use a different attribute name for that.

Commit related: https://github.com/CartoDB/cartodb.js/pull/1873/commits/100de44a24de98fb925b2c2308b29e769e6d0bc9

**Comment by matallo** [comment]
I think this goes all the way down here https://github.com/CartoDB/Windshaft-cartodb/blob/73a633ae7d19cdcfae1e45e20090483e37251e07/lib/cartodb/middleware/error-middleware.js#L150

**Comment by matallo** [comment]
closing, there's not a good remedy for this, it would imply moving the hack around to prevent a vendor library behaviour
