### ISSUE TITLE
Install cartodb using npm?

### ISSUE THREAD

**Issue by alinnert** [CartoDB/cartodb.js#1906]
Is it currently possible to install cartodb.js using npm?

I found the `@cartodb` organization on npmjs.org, but it doesn't list cartodb.js.

In the readme there's also an explanation how to install it using bower. But I'm not using bower anymore. Indeed I found it more and more uncommon to use bower instead of npm over the last years.

Ok, I just found issue #98. And I'm not 100% sure about this, but wouldn't it be possible to use `peerDependencies` to overcome the `cannot read property '...' of undefined` errors? And is this still an issue? The issues are quite old already.

If nothing has changed since back then: Sorry, that I've brought up this topic again.

**Comment by alonsogarciapablo** [comment]
Hello @alinnert. We're working on the new version of the library and we'll make sure it's available on npm when we release it. In the meantime, it's not available. Sorry!

**Comment by IagoLast** [comment]
As Pablo said, a new version will be released soon with full npm compatibility :)

meanwhile @alinnert you can manually [add a tag reference](https://github.com/CartoDB/deep-insights.js/blob/master/package.json#L31) in your `package.json`.
