### ISSUE TITLE
Get rid of moment-timezone

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb.js#1908]
As of now, we're requiring `moment-timezone` only to get the user timezone offset. It brings 418KB of weight:

![image](https://user-images.githubusercontent.com/1078228/33018877-6be70ed0-cdf8-11e7-89c6-6675a51a66cb.png)

We can use the native way of doing it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

Take into account that Windshaft doesn't support offset that are not complete hours, so we should add some logic to give a right offset.

**Comment by Jesus89** [comment]
Removed also `moment` dependency.

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartodb.js/pull/1981
