### ISSUE TITLE
V4. Layer.setSource fails when the source has not internalModel.

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb.js#1912]
### Whats happening?

When an instantiated layer is set a new source, we get a windshaft error.
If we inspect the payload the source field for the layer is empty.

### What should happen?

The layer should be rendered again with the new source.

### Steps to reproduce
1. Create a layer
2. Add the layer to the client
3. Create a new source
4. Set the new source as the layer source
5. See the error!

```javascript
var client = new carto.Client({
  apiKey: '84fdbd587e4a942510270a48e843b4c1baa11e18',
  username: 'cartojs-test'
});


const data = new carto.source.Dataset('ne_adm0_europe');
const gasStyle = new carto.style.CartoCSS('#layer { marker-fill: blue');

const layer = new carto.layer.Layer(gasData, gasStyle);

client.addLayer(layer);
client.getLeafletLayer().addTo(map);


// Add a button into the page
button.addEventListener('click', event => {
    let newData = new carto.source.SQL(`SELECT * FROM ne_adm0_europe');
    layer.setSource(newData);
});

```

**Comment by IagoLast** [comment]
Fixed [here](https://github.com/CartoDB/cartodb.js/commit/33372251b93a579c39fdf55643e3fd0d192b4828) not merged

**Comment by Jesus89** [comment]
Duplicated: https://github.com/CartoDB/cartodb.js/issues/1907

**Comment by Jesus89** [comment]
We need a PR here

**Comment by IagoLast** [comment]
It´s included in https://github.com/CartoDB/cartodb.js/pull/1919

**Comment by Jesus89** [comment]
OK!
