### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb.js#1914]
Sometimes a map triggers an error after calling `createDashboard` but we need to dig into the stack trace to know the real cause.

For instance, this map is broken

https://recuperacaomaisvalia.carto.com/builder/9f0c2a02-08c0-4eb1-afca-949b5c2d4451/embed

The error message shows:
![image](https://user-images.githubusercontent.com/1078228/33074247-c40f307e-cec5-11e7-852e-99beeb60147b.png)

but if we investigate the error returned by the API is `"column "foto" does not exist"`

On top of that, now we're getting an `Uncaught (in promise)` error as well. Perhaps we should avoid that message capturing the exception and logging it properly.

**Comment by alonsogarciapablo** [comment]
This could probably be considered part of https://github.com/CartoDB/cartodb.js/issues/1892.

**Comment by Jesus89** [comment]
Done here: https://github.com/CartoDB/cartodb.js/issues/1892
