### ISSUE TITLE
Simplify API merging methods (singular/plural)

### ISSUE THREAD

**Issue by enekid** [CartoDB/cartodb.js#1916]
There are pairs of functions that do exactly the same that differ only in the cardinality of one input parameter (single object/Array).

For example:

- addDataview(s)
- addLayer(s)
- removeLayer(s)

Solution:
Merge both functions into just one and check if the input parameter is a single object or an Array.

**Comment by Jesus89** [comment]
Not very sure about that. I think this is more explicit:

```js
addLayer(layer1);
addLayers([ layer1, layer2 ]);
...
```

But we will though about it anyway.

**Comment by ivanmalagon** [comment]
We had a discussion about this and ended up using the explicit one. Easier for documentation and more semantic.

If lots of people complain about the same thing perhaps we'll need to rethink it.

Thanks for the feedback!

**Comment by alonsogarciapablo** [comment]
I find it more explicit too. Closing for now. Thanks for your feedback @enekid!
