### ISSUE TITLE
TimeSeries with numeric values error can be clearer

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb.js#1917]
This is what I got when I used a numeric column:

`{"errors":["function date_part(unknown, integer) does not exist"],"errors_with_context":[{"type":"unknown","message":"function date_part(unknown, integer) does not exist"}]}`

I think we can be more explicit than this

**Comment by ivanmalagon** [comment]
After merging https://github.com/CartoDB/cartodb.js/pull/1932 this error is shown as:

![image](https://user-images.githubusercontent.com/1078228/33614379-86fb213a-d9d7-11e7-80fb-84aed9bb9aea.png)

![image](https://user-images.githubusercontent.com/1078228/33614428-aa98ccb4-d9d7-11e7-92af-a355a208bd57.png)

**Comment by rjimenezda** [comment]
Much better 👍
