### ISSUE TITLE
carto.dataview.Category doesn't give error if the column doesn't exist

### ISSUE THREAD

**Issue by stevelewis99** [CartoDB/cartodb.js#1920]
Feel free to rename the title :)
```javascript
var myTypesDataview = new carto.dataview.Category(myDataset, 'does_not_exist', {
  limit: 100
});
```
doesn't throw any exception in the console at this point if the column doesn't exist.

When you try to add the dataview to the `client` you get a HTTP 404 which isn't so friendly

**Comment by IagoLast** [comment]
Correct me if im wrong but when the map is instantiated in backed (including dataviews) there are no checks to ensure the column exist.

So windshaft returns a successful response, the dataview is created and the request to get the data fails.

cc @alonsogarciapablo  @ivanmalagon

**Comment by alonsogarciapablo** [comment]
I think that's how it works @IagoLast but @ivanmalagon probably knows this for sure.

**Comment by ivanmalagon** [comment]
After talking with @rochoa that should be tackled in the backend. As @IagoLast says, the dataview instantiation fails when fetching data, not in the map instantiation. For us, it'd be great that if a new map instantiation brings changes to dataviews, the API will answer with an error at that point.

Until then, I think it's advisable to put off any changes to dataviews. When that change is in place, we can tackle better async workflow with dataviews.

Summoning @rochoa here to have his approval. If so, we'll create a ticket in Engine for doing all of this.
