### ISSUE TITLE
layer.hide() not working if called before addingLayer to client

### ISSUE THREAD

**Issue by enekid** [CartoDB/cartodb.js#1921]
Hide a layer before adding it to the client/leaflet doesn't work. It's still shown.

Pseudocode:

```javascirpt
const map = L.map('map').setView(...);
const client = new carto.Client({...});
const layer1 = new carto.layer.Layer(...);
const layer2 = new carto.layer.Layer(...);

layer1.hide();
clientAddLayer(layer1);
clientAddLayer(layer2);
client.getLeafletLayer().addTo(map);
```
Online Example:
[http://bl.ocks.org/enekid/f642f66ec7ee95f81f3a4403b4a2afe2](http://bl.ocks.org/enekid/f642f66ec7ee95f81f3a4403b4a2afe2)

In the console you can check that the layer is hided before adding it to the client.

**Comment by Jesus89** [comment]
I think you are using a deprecated cdn. Please use: https://cdn.rawgit.com/CartoDB/cartodb.js/@4.0.0-alpha.28/carto.js and try again.

**Comment by enekid** [comment]
It works!
