### ISSUE TITLE
Review `Client.prototype.getLeafletLayer`

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1924]
- [x] Returns an instance of `L.TileLayer` so that devs can do things like `setZIndex`.
- [x] Document the result of `Client.prototype.getLeafletLayer`.
- [x] Leaflet Layer has the CARTO attribution: `&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attribution">CARTO</a>`

**Comment by Jesus89** [comment]
I have extended L.TileLayer to use our internalView in the addTo and removeFrom and it works!

The 3rd point is not possible now because of wax:
![selection_035](https://user-images.githubusercontent.com/2227572/33182427-41af9c3a-d074-11e7-9936-fb056ae93764.png)
