### ISSUE TITLE
sql.execute doesn't return a promise.

### ISSUE THREAD

**Issue by Eh2406** [CartoDB/cartodb.js#1927]
The docs for the [sql.execute command indicate that it returns a promise](https://carto.com/docs/carto-engine/carto-js/sql/#returns). So I assumed it returns something compatible with the [javascript promises api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) or the [JQueryPromise api](http://api.jquery.com/Types/#Promise). However neither of those api recognize the result of the sql.execute command.

I think the returned object needs to have a `then` method to be compliant with the [CommonJS Promises/A](http://wiki.commonjs.org/wiki/Promises/A) definition.

**Comment by alonsogarciapablo** [comment]
You are right @Eh2406 its not a real promise. We are currently working on a new version of the library and we will revisit this. Thanks for your feedback!

**Comment by Eh2406** [comment]
Thank you for confirming the bug I am seeing. Glad to hear that the new version will have this fixed. Do we have an eta on a release with this fixed?
