### ISSUE TITLE
Fix examples/tutorials

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb.js#193]
The following examples are not working correctly:
[Query by distance-template](https://github.com/CartoDB/cartodb.js/blob/develop/examples/tutorials/tutorial-query_by_distance-template.html)
~~[Query by distance](https://github.com/CartoDB/cartodb.js/blob/develop/examples/tutorials/tutorial-query_by_distance.html)~~ (It doesn't work in local, but works in server)
[Toggle map view template](https://github.com/CartoDB/cartodb.js/blob/develop/examples/tutorials/tutorial-toggle_map_view-template.html)

**Comment by javisantana** [comment]
@Xatpy those are templates not working examples
