### ISSUE TITLE
Map fetches grid.json for "old" maps

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1951]
Steps to reproduce

1. Open a map (eg: in BUILDER).
2. Change something (eg: the style) so that the map is recreated in the server.
3. Move your mouse over the mouse.

Expected result
- Grid.json **for the current map** (i.e: current layergroupid in grid.json files) files are fetched

Actual result:

- It seems that map keeps requesting grid.json files for "old" maps:

![screen shot 2017-12-11 at 14 03 23](https://user-images.githubusercontent.com/390398/33832358-269d9cba-de7c-11e7-8fb9-b6495c998649.png)

**Comment by IagoLast** [comment]
Fixed in https://github.com/CartoDB/zera/commit/4ad435fa359aaca9daeb37ff64e86afa20999668

Included in in https://github.com/CartoDB/cartodb.js/commit/4e8f3f5eebda0760bd033e45800ef874741248f5
