### ISSUE TITLE
BUILDER's Edit feature button not working as before

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1952]
BUILDER is only displaying the Edit button the first time a feature is clicked.

Production:

![edit-button-2](https://user-images.githubusercontent.com/390398/33837231-fe2b0c1c-de8b-11e7-8adc-7088f06d6e15.gif)

Staging:

![edit-button](https://user-images.githubusercontent.com/390398/33837238-035a105c-de8c-11e7-97de-bd40cce9cfe2.gif)

**Comment by IagoLast** [comment]
Fixed in https://github.com/CartoDB/zera/commit/317a82f61b137299f6b959b2addc65c52dd11df0

Included in https://github.com/CartoDB/cartodb.js/pull/1955/commits/ea422031891e314afd3108288db6b03dcb2cd6c4
