### ISSUE TITLE
Add fetch & Promise Polyfill to V3

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb.js#1970]
`zera` uses fetch to get the grid.json files from the server. Since fetch wont work in old browsers we need to add a polyfill.

We [added a polyfill for the v4 version](https://github.com/CartoDB/cartodb.js/blob/v4/src/api/v4/index.js#L23) but we forgot to add the polyfill in the v3 (used by builder).

At the moment @ivanmalagon fixed this situation adding the polyfill in builder but the bug is still here.

**Comment by Jesus89** [comment]
I think it would be nice to add the polyfill in `carto-zera`. Then this package will be fully-compatible with old browsers.

**Comment by IagoLast** [comment]
@ivan should we remove the polyfill from builder?

**Comment by ivan** [comment]
Wrong @ivan
