### ISSUE TITLE
Add Carto.js app example using npm bundle

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb.js#1975]
Requires a new release in npm (with this issue https://github.com/CartoDB/cartodb.js/issues/1974)

- [x] Test CARTO.js from npm
- [x] Add the `npm install carto.js` documentation to the guide (https://github.com/CartoDB/documentation/issues/80)

**Comment by Jesus89** [comment]
Tested a minimal CARTO.js boilerplate: https://github.com/Jesus89/carto-boilerplate

**Comment by rubenmoya** [comment]
Does it work for you? because its throwing me this error when using `const carto = require('carto.js');`

![screen shot 2017-12-18 at 19 55 50](https://user-images.githubusercontent.com/905225/34122700-99759f60-e42d-11e7-9041-3c3574401a5f.png)

**Comment by Jesus89** [comment]
I have just published the beta.4 release. Also I have updated the boilerplate, take it as a reference.
