### ISSUE TITLE
Prevent fetch grid.json files non-interactive layers

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb.js#1976]
Currently the `grid.json` tiles containing the interactivity information for a layer are being requested whether the layer is interactive or not.

For some reason (bug?) get a different behaviour that form embeds and builder.

- Builder:
https://cartocdn-ashbu_a.global.ssl.fastly.net/iago-carto/api/v1/map/0acefb8ae9657da337e1b8e37b79128b:1510838928849/1/7/60/48.grid.json?api_key=552dc6b016acb007acf0b9091719be8d0a37847b

- Embed:
https://cartocdn-ashbu_a.global.ssl.fastly.net/iago-carto/api/v1/map/iago-carto@f2153e54@c70f5b8a89a9d7f657e9f29bd8724126:1510838928849/1/7/62/48.grid.json

**Comment by Jesus89** [comment]
:rocket:

**Comment by ivanmalagon** [comment]
:clap: :clap: :clap: :clap: :clap: 

Now TrackJS in back on track (pun intended)
