### ISSUE TITLE
Define API for Carto layers order

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb.js#1982]
``` js
//         BOTTOM v     v TOP
client.addLayers([A, B, C]);

// 0 < 1 < 2

A.setOrder(0); // A, B, C
A.setOrder(1); // B, A, C
A.setOrder(2); // B, C, A
A.setOrder(-1); // throw error: out of range
A.setOrder(3); // throw error: out of range

A.bringToFront(); // same as A.setOrder(<layers length>);
A.brintToBack(); // same as A.setOrder(0);
```

cc @csobier @alonsogarciapablo @IagoLast

**Comment by IagoLast** [comment]
LGTM!

**Comment by alonsogarciapablo** [comment]
What happens to the order of `B` and `C` when `A.setOrder(0)` is executed?

Why do you think `A.bringToFront()` and `A.bringToBack` will be useful?

Perhaps we can see how other libraries solve this problem. 

Also, something like `client.addLayer(myLayer, { at: 1 }` might be useful.

**Comment by Jesus89** [comment]
> What happens to the order of B and C when A.setOrder(0) is executed?

Since the order is the index, B and C will have order 1 and 2 respectively.

> Why do you think A.bringToFront() and A.bringToBack will be useful?

I think these functions are more explicit and you don't need to remember the number of layers (for the `bringToFront` function).

> Also, something like client.addLayer(myLayer, { at: 1 }) might be useful.

May be we could rename this function to `client.addLayerAt(1, myLayer)` (or`client.addLayerAt(myLayer, 1)`)

**Comment by Jesus89** [comment]
Hi @alonsogarciapablo @inigomedina @ivanmalagon

Are you OK with this API functions?

**Comment by IagoLast** [comment]
- Since this functions require a new map instantiation I assume they are going to be async right? otherwise we could have concurrence issues.
- Are you sure about the layer `reordering`? how leaflet works?

**Comment by Jesus89** [comment]
Layer ordering is a required feature. It is an async task so we need to provide also Promises. Leaflet has  zIndex and bringTo functions for the Leaflet LayerGroup.

**Comment by IagoLast** [comment]
I mean `reordering`

Whats the expected behaviour? how leaflet (or any reference lib) work?
Example reordering layers?
``` javascript
// [l1, l2, l3] 
l1.setOrder(2);
// [l2, l3, l1]  --> l2 and l3 were reordered!
```

Example without reordering layers ?
``` javascript
// [l1, l2, l3] 
l1.setOrder(2);
// [ , l3, l1]  --> l2 and l3 were reordered!
```

**Comment by Jesus89** [comment]
Yes. The layers will be "reordered" if you mean that the absolute position changes, but the rest of the layers keep their relative positions as I described in the ticket definition. I think it is the expected solution.

**Comment by Jesus89** [comment]
Finally I have added the `moveLayer(layer, index)` function to the client and the `setOrder`, `bringtoBack` and `brintToFront` to the layer.

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/cartodb.js/pull/2031
