### ISSUE TITLE
Add link to CARTO.js Beta version to CartoDB.js README

### ISSUE THREAD

**Issue by dbkbali** [CartoDB/cartodb.js#1989]
Appreciate that Carto.Js v3 is no longer being developed, is there a link to carto v4 beta repository available or is this only going to be available through a cdn?

**Comment by rubenmoya** [comment]
Hello @dbkbali!

It is also available as an npm package https://www.npmjs.com/package/carto.js

You can access the documentation through https://carto.com/documentation/cartojs, I'm not sure if it's documented yet, but if it's not, it will be soon :)

**Comment by alonsogarciapablo** [comment]
Thanks for your feedback @dbkbali! We'll add a message about this in our readme.

**Comment by dbkbali** [comment]
Thanks

**Comment by alonsogarciapablo** [comment]
Done! Here's how it looks like:

![screen shot 2018-01-08 at 15 26 29](https://user-images.githubusercontent.com/390398/34675009-62b42f58-f488-11e7-99b0-5908b5dc85b8.png)

cc: @inigomedina @ivanmalagon
