### ISSUE TITLE
How to choose the source to add the lib in CDNJS

### ISSUE THREAD

**Issue by sufuf3** [CartoDB/cartodb.js#1993]
Hi CartoDB team @gfiorav,

We are cdnjs team, we're going to host this library.
CDNJS is one of the most famous free and public web front-end CDN services which is used by ~1,143,000 websites worldwide.

I met some problem when I help to add this library.
I found there are three ways can get the web front-end files.
1. From this `cartodb.js` repo: but need to generate the files by ourself, unfortunately, CDNJS provide the same files from upstream, it does not generate by itself. 
2. From npm: but the latest version from npm is `v3.15.9`, the latest stable version is different from this `cartodb.js` repo which is `v4-1.1.2` or `v3.15.12`.
3. From `cartodb.js-bower` GitHub repo: but the latest version from npm is `v3.15.10`, the latest stable version is different from this `cartodb.js` repo which is `v4-1.1.2` or `v3.15.12`.

This is hard for me to choose the source to add this awesome library. 
Would you mind giving me some suggestion about providing the web front-end files, please? Which source is good to be added by CDNJS?

Sorry for bother you.
If you have any suggestions, please let me know.
Many thanks.

cdnjs/cdnjs#6746
cdnjs/cdnjs#7812

**Comment by Jesus89** [comment]
Hi @sufuf3!

The version `v3.15.12` is deprecated and will no longer be maintained. Now we are working on the new CARTO.js v4 API. This version is BETA and now is hosted on the `v4` branch. You can find the new packages in npm: https://www.npmjs.com/package/carto.js.

The next month we will release the RC and then the final release. May be the repo name will change to `carto.js`. This will be properly announced so then you can include it in CDNJS.

Thanks!

**Comment by sufuf3** [comment]
Cool! This is a great news.
I'll add the lib from npm of `carto.js`.
Many thanks.
