### ISSUE TITLE
build step should not require user input

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#200]
`grunt`

should not need user input, should just build current version

**Comment by xavijam** [comment]
@javisantana you solved this issue, didn't you?

**Comment by javisantana** [comment]
I added a dist_js but didn't fixed this

**Comment by xavijam** [comment]
Ok, I'll take care of it.

**Comment by javisantana** [comment]
basically it should only ask when user executes "publish"

**Comment by xavijam** [comment]
ok

**Comment by javisantana** [comment]
fixed here: https://github.com/CartoDB/cartodb.js/pull/552
