### ISSUE TITLE
Make layer style optional

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb.js#2001]
Due to vector tiles changes, we need to allow layer with no style. It's now the way Windshaft has to know if a layer should be rendered as vector or not.

In the example [PR #1996] @rochoa made an Empty style module. I think it's cleaner to just simply allow layers with no style but we can discuss it. Options are:

1. Allow layers with no style: that open the can of worms of devs wanting raster layers and forgetting about the style.
2. Force layergroup to be set as vector or raster. This way we can validate that layers should bring style with them.

Tasks:
- Decide approach (1 or 2)
- Implementation.
- Update documentation.

**Comment by ivanmalagon** [comment]
Blocked. Waiting to decision on how to approach our vector strategy.

**Comment by Jesus89** [comment]
Deprecated by carto.gl
