### ISSUE TITLE
Scrollwheel not working if passed as an option

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb.js#2007]
`createVis` accepts 3 argument: element, vizjson and options. The `options` option allows overwriting the behavior specified in the vizjson. So having a vizjson with scrollWheel option set to true in it, this code should create a vis with scrollWheel disabled:

```
cartodb.createVis('map', vizjson, {
    legends: false,
    scrollWheel: false
})
```

But the result is the scrollWheel is enabled. You can reproduce it in the examples provided in the internal folder.

**Comment by nobuti** [comment]
This is kind of important in order to migrate the dashboard code to use cartodb.js v4. For instance, in the user's public feed page, there is a favorite map as a header. ScrollWheel may interfere with the page scroll causing an annoying effect and a poor user experience.

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartodb.js/pull/2024
