### ISSUE TITLE
Quickstart Documentation changes

### ISSUE THREAD

**Issue by michellemho** [CartoDB/cartodb.js#2008]
Hi Carto.js team! I ran into these issues while following the Quickstart documentation and wanted to log them here.

Quickstart Documentation issues:
```
<script src="https://cartodb-libs.global.ssl.fastly.net/carto.js/%VERSION%/carto.min.js"></script>
```
- Consider changing `%VERSION%`  to the latest carto.js version (v4.0.0-beta.10) in the code example in the Quickstart guide, or make a clear note that the user should replace the version with the latest.

- Couldn't find documentation on `carto.layer.events.FEATURE_OVER` (found in the Quickstart guide) in the References... is this the equivalent of `'featureOver'`?

- When adapting the Quickstart code to create a pop-up when mousing over contiguous polygons, I found that the pop-up content never disappears or updates! My solution was to remove the `if (!popup.isOpen())` statement in the pop-up code, which made me wonder if it was necessary in the first place?

- Finally, it would be nice to see the final map from the Quickstart guide to understand expected behavior 😄

**Comment by csubira** [comment]
Hi @michellemho! 
Thanks a lot for reporting! 
- As you said `%VERSION%` should be the latest carto.js version so, you found a bug! 
Fixed right now! 
- There's also an open ticket here -> #2013 regarding the same topic. Let's see if by tackling/ solving that issue your doubts are cleared out too.
- Maybe if you contact @IagoLast or @Jesus89 to show them what you've been working they can help you with that! 
- Yes! Done!

**Comment by ivanmalagon** [comment]
Hi Michelle!

Regarding your popup question, it's true that the code it's only updating contents when showing the popup again, which is OK with the example dataset, sparse points. Every time you hover a point you're sure that the popup has been closed before. In your case, with continuous polygons or a dense network of point, it won't work. Good catch!
