### ISSUE TITLE
Auto generate a changelog

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/cartodb.js#2011]

**Comment by inigomedina** [comment]
Ideally, we should keep the entire history of the project. I know there will be a gap in the timeline, but it's better to have all the information just in one place.

**Comment by IagoLast** [comment]
@inigomedina @ivanmalagon  Just created a script to autogenerate a changelog.

It's full automated as log as developers follow a simple rule in the merges, we can start start a changelog on the next merge 🚀 

This could be used for another projects too (think about news.md)


This is a test example of a changelog generated with this tool, (since i've used fake data all commits are the same):

## 4.0.0-beta.11 - 2018-01-09

### New features
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.10 - 2017-12-29

### New features
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.9 - 2017-12-22

### Fixes
- Allow aggregation in carto layers (#2010) 
### Improvements
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.8 - 2017-12-20

### New features
- Allow aggregation in carto layers (#2010) 
### Improvements
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.7 - 2017-12-20

### Improvements
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.6 - 2017-12-20

### New features
- Allow aggregation in carto layers (#2010) 
### Improvements
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.5 - 2017-12-19

### New features
- Allow aggregation in carto layers (#2010) 
- Allow aggregation in carto layers (#2010) 
### Improvements
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.4 - 2017-12-19

### New features
- Allow aggregation in carto layers (#2010) 
### Fixes
- Allow aggregation in carto layers (#2010) 
### Improvements
- Allow aggregation in carto layers (#2010) 
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.3 - 2017-12-15

### New features
- Allow aggregation in carto layers (#2010) 
### Improvements
- Allow aggregation in carto layers (#2010) 
- Allow aggregation in carto layers (#2010) 

## 4.0.0-beta.2 - 2017-12-14

**Comment by ivanmalagon** [comment]
After sleeping on it, I must say that this is a good automatic way of having a forensic tool of our work but it's not a good idea to autogenerate a changelog workflow-wise. I'll explain why.

We need **always** a manual step by the developer. The one where she must classify the entry in the log and provide a descriptive text. The difference between this proposed way and the one we follow in Builder is when we do that.

**Builder via NEWS.md**
- The classification and description happens within the PR. It's part of the body of work done in the PR.
- During the CR, another team member can check if the description and classification it's good enough.
- We can add whatever literature we want. We're not limited by space.
- When the PR is about to get merged, we have a visual clue to remember to include it in the changelog if it's needed. We can bypass this step if the PR is not important enough to get an entry in the log.
- What it's more important. When we merge the PR we know already how the changelog will look like. We merge and we forget about it. On to the next one.

**Automatic changelog**
- The classification and description only happens once when the PR is about to get merged.
- In our workflow this can be done by any developer, not only the one that knows the most about it, the one who did the PR.
- This step would happen with no possible supervision at all. It's not a process in our workflow, it's a particular moment in time.
- We cannot add more literature to the merge.
- The final changelog will happen directly in `master`. If we screw it up, we have to check that in `master` and make changes in it after the PR has been merged.

We've been following the NEWS.md workflow in Builder for a year and we haven't had any problem at all. The changelog It's a communication tool. Take it as part of our public documentation.

I'd keep this as a forensic tool. I see big wins of having this kind of script in the project. For example, when we get a customer support ticket and we need to know exactly when a particular feature went live. We've suffered several times this issue and we spent a lot of time digging in the commit log. For that, this will come super handy. But it's not the best tool for the changelog.

So, going for keeping it as a dev log, I'd the merge dates (not needed for public log but useful for us) and we must add the same step in the CI as in Builder with the NEWS.md

**Comment by inigomedina** [comment]
Good points, @ivanmalagon. Agree, the changelog is a communication tool. If we have a good workflow with Builder, taking it as a part of our public documentation, we should go for a similar workflow in CARTO.js and the other Engine's components.

**Comment by Jesus89** [comment]
Closed by https://github.com/CartoDB/cartodb.js/pull/2012
