### ISSUE TITLE
v4.0.0-beta.10 - Invalid layer filtering error on client removeLayers method

### ISSUE THREAD

**Issue by EmanuelN** [CartoDB/cartodb.js#2021]
I remove the existing layers from the client with the removeLayers method and the layers are successfully removed. But in the process, 29 image requests get made and return 400 with the error 'invalid layer filtering'. 
![screen shot 2018-01-19 at 2 05 31 pm](https://user-images.githubusercontent.com/9320290/35167066-14e6cfc2-fd22-11e7-8c93-c99540716a3b.png)
![screen shot 2018-01-19 at 2 05 51 pm](https://user-images.githubusercontent.com/9320290/35167069-16536352-fd22-11e7-90f0-a696b7907510.png)

I am using the latest version of the v4 beta, getting this error on both the latest Chrome and Firefox versions and my OS is the latest OSX High Sierra. 

Here is where I call the function. The layers correctly get removed from the map and the client and then I add the new ones. The error is troubling though, seems to be related to a lack of coordinates or bounds on the request (,,,)
![screen shot 2018-01-19 at 2 17 12 pm](https://user-images.githubusercontent.com/9320290/35167428-7f45735e-fd23-11e7-9772-d42ebce61408.png)

**Comment by ivanmalagon** [comment]
Thanks Emanuel for filing this issue. We'll take a look on this.

Why did you close the issue, anyway?

**Comment by EmanuelN** [comment]
I modified my code a bit and the error went away. I couldn’t replicate it with the new code.
