### ISSUE TITLE
Default server aggregation validation

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb.js#2032]
Related comment -> https://github.com/CartoDB/cartodb.js/issues/2027#issuecomment-361977849

When setting aggregations, `placement` and `columns` are optional. In those cases, Windshaft applies a [default aggregation](https://carto.com/docs/carto-engine/maps-api/tile-aggregation/#special-default-aggregation)

In the comment linked above, @alonsogarciapablo has found that Windshaft complains about `placement` not being set, while it's supposed to use a default value.

Apart from that, if `columns` are present as an option, the original dataset columns are not returned. It'd be nice to have that validation client side to avoid confusion, since everyone that has used aggregations and interactivity has tried to do it in a non-existent column.

- [x] Make `placement` and `columns` optionals (if they're not client side)
- [x] Test if both are optionals or one of them must be present.
- [ ] Develop client validations when `columns` is present, checking that columns in interactivity are the same

**Comment by alonsogarciapablo** [comment]
:+1:
