### ISSUE TITLE
CARTO.js examples feedback

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/cartodb.js#2035]
_From @ramiroaznar on December 15, 2017 10:22_

- [x] **Change the source**: replace `Europe` with `European` and `Spain` with `Spanish`.

![image](https://user-images.githubusercontent.com/5215798/34037554-801413b8-e189-11e7-813e-d13871a8efee.png)

- [x] **Change the style**: replace `9` with `7`. It is true that the title is "changing the style" but the checkbox is only related to changing the color:

![image](https://user-images.githubusercontent.com/5215798/34037631-d56e2cb8-e189-11e7-9ad3-61729ace3a4a.png)

- [x] **Legends**: I was expecting to see _dynamic_ legends in action, so I would add a new example in order to see how the legends change when the SQL/CartoCSS changes. Instead of using bubbles, we can use gradients for this one.

- [x] **Error handling**: the sidebar needs CSS love from design:

![image](https://user-images.githubusercontent.com/5215798/34037741-37221ffa-e18a-11e7-9c5f-b1d0a4cc5a8d.png)

cc @inigomedina 

_Copied from original issue: CartoDB/documentation#87_

**Comment by Jesus89** [comment]
Done here: https://github.com/CartoDB/cartodb.js/pull/2034

Please @inigomedina @ramiroaznar take a l:eyes:k

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/cartodb.js/pull/2034
