### ISSUE TITLE
"Copy link address" not working for headings

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/cartodb.js#2040]
_From @csobier on December 7, 2017 12:57_

"Copy link address" not working and/or not appearing. (This is not urgent, added to the Public Release milestone).

### Example of Full Reference API section:
Only the left-side navigation works for copying URLS- but they are not in sync with the selected heading so it's hard to find.

![image](https://user-images.githubusercontent.com/13319925/33716123-fa273904-db22-11e7-97d1-dc2e158b0096.png)

### Example of Guide section: 
They are not appearing at al. You can only copy the heading URLs from the left-side navigation menu which is mostly not visible as you scroll through the guide).

![image](https://user-images.githubusercontent.com/13319925/33716328-bc5c72be-db23-11e7-903b-852afef1622d.png)

_Copied from original issue: CartoDB/documentation#54_

**Comment by inigomedina** [comment]
#125

**Comment by inigomedina** [comment]
_From @csobier on January 9, 2018 12:16_

Is there a refresh time for this to appear? I tested the live beta version in a refreshed browser and in an incognito browser.

**Comment by inigomedina** [comment]
True. My last conversation with @csubira about this was that it was solved and could be merged. But it seems it's not working yet. I reopen it and check it to see what's wrong.

**Comment by csubira** [comment]
🤞 merged!
