### ISSUE TITLE
do not show torque time slider when the time steps is 1

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#213]
this example does not need time slider: http://bl.ocks.org/andrewxhill/020636499dde84b90f0a

Also the animation should be stopped so torque rendering optimizations can be user, see https://github.com/CartoDB/torque/pull/44

**Comment by Xatpy** [comment]
[PR #280](https://github.com/CartoDB/cartodb.js/pull/280)

**Comment by Pabloska** [comment]
can you tell me how to make the torque work but without slider? is is possible to remove the slider ?

thanks

**Comment by fdansv** [comment]
@Pabloska when you initialise the layer, you can pass the option `time_slider` and set it to false. Doing this will hide the slider :)
