### ISSUE TITLE
Errror in Firefox (v32 and v33) in torque visualizations

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#216]
[TrackJS](https://my.trackjs.com/messages/filtered?message=Index+or+size+is+negative+or+greater+than+the+allowed+amount)

"Index or size is negative or greater than the allowed amount"

**Comment by javisantana** [comment]
fixed some weeks ago in torque: https://github.com/CartoDB/torque/commit/4d73c03fee89c7c2d45e940451623a93aa9ff093
