### ISSUE TITLE
Pointer events in IE11 on touch-screen Windows laptops do not trigger popups

### ISSUE THREAD

**Issue by dankarran** [CartoDB/cartodb.js#223]
(from #202)

With IE11 on Windows 8, popups don't work at all on touch screen devices (but are ok on non touch screen devices). This is the same in cartodb.com hosted visualisations as well as ones I implement using the CartoDB.js API.

On a touch screen laptop, moving your finger on the trackpad allows the hover events to work (the profiler shows these as mousemove events), until you click something. The only event fired at that point is a blur, but no click or equivalent. Then the last hover event just gets stuck on screen. The popups never appear on click, and there are no errors logged in the debugger or console.

It looks like IE11-specific Pointer click events aren't being picked up by CartoDB.js. If I test with the profiler on a Leaflet-only map, I get a pointerdown and then pointerup event firing when clicking on a standard Leaflet marker icon to load its popup.

**Comment by dankarran** [comment]
Hi guys, have you had a chance to look into these IE issues? Let me know if there's anything I can do to help with testing etc.

**Comment by Xatpy** [comment]
I've been debugging the issue with Nokia Lumia, Internet Explorer and Microsoft Visual Studio 2013. 
The issue (when the errors are being triggered) is [here](https://github.com/CartoDB/cartodb.js/blob/develop/vendor/wax.cartodb.js#L3422) 

That function (*getBoundingClientRect()*) returns an `unespected error`. It seems to be a '[know bug](https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=getboundingclientrect%20unspecified%20error)'

**Comment by Xatpy** [comment]
[wax PR](https://github.com/CartoDB/wax/pull/6) about drag and infowindow

**Comment by Xatpy** [comment]
Fixed in **3.12.6**
