### ISSUE TITLE
 mobile layout with slides 

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#229]
current mobile layout does not support slides, it should listen for changes in layer, overlays and  other things.

Do it in branch CDB-3913

**Comment by javisantana** [comment]
hey, is this already done?

**Comment by javierarce** [comment]
No, not yet.

**Comment by javierarce** [comment]
Forgot to upload a screenshot of the mobile controls (first/quick/crappy version): 

![screen shot 2015-01-12 at 18 19 48](https://cloud.githubusercontent.com/assets/4933/5707266/a7652b92-9a87-11e4-817b-63022dc5c19b.png)

**Comment by javierarce** [comment]
Ok, the basic work is done here. I'm closing this issue and will open other to fix concrete problems with certain overlays.
