### ISSUE TITLE
a way to pass slides (desktop and mobile), design and implementation

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#230]
we need some kind of widgets to allow to pass slides, we need design for them, both mobile and desktop

@saleiva

**Comment by javierarce** [comment]
Forgot to upload a screenshot of the mobile controls (first/quick/crappy version):

![screen shot 2015-01-12 at 18 19 48](https://cloud.githubusercontent.com/assets/4933/5707317/28fafa4c-9a88-11e4-958d-2144b813c3e8.png)

**Comment by saleiva** [comment]
Thanks, will work on this ASAP

**Comment by javierarce** [comment]
:ok_hand:

**Comment by saleiva** [comment]
Closing since @javierarce already has the source files
