### ISSUE TITLE
The event change:time is not raised torque-frame-count times with v3.11.29

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb.js#263]
Steps to reproduce:

1. Use v3.11.23 of cartodb.js. Catch the event 'change:time'. This event is catched N times, being N = torque-frame-count.

2. Use v3.11.29 or cartodb.js. Catch the event 'change:time'. This event is catched N - 2 times.

**Comment by saleiva** [comment]
hey @fdansv can you confirm this is still happening?

**Comment by fdansv** [comment]
Just tested it and for a whole cycle the number of steps is equal to the number of times that the "changed:time" event is triggered. We've been modifying a number of elements in the animator since 3.11.29, so this issue was likely solved somewhen in between.
