### ISSUE TITLE
Can't disable zoomControl from createVis

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/cartodb.js#267]
I'm trying to delete the zoomControl from a visualization, by passing zoomControl: false as option to createVis function:

```
createVis('map', vizJson, {zoomControl: false})
```

But it doesn't work. I need to enter the editor and disable the zoom control using the UI. 

Using cartodb.js 3.11.29

**Comment by jorgeas80** [comment]
Same problem with search control. The option {searchControl: false} doesn't seem to work. Actually, search control should be false by default, according with the doc.

**Comment by Xatpy** [comment]
Branch: https://github.com/CartoDB/cartodb.js/tree/CDB-267-DisableControls

**Comment by Xatpy** [comment]
Nowadays, **shareable** and **fullscreen** are also options that can't be configurable by vis options. [Ref. documentation](http://docs.cartodb.com/cartodb-platform/cartodb-js.html)
@javisantana  should I add those configs options?

**Comment by Xatpy** [comment]
[PR done](https://github.com/CartoDB/cartodb.js/pull/275)

@jorgeas80 about *search control*, there was an error with naming. The flag is called **search** (and no *searchControl*). I've fixed it in this API.md ; and I'll correct doc repo when it was merged and deployed

**Comment by javisantana** [comment]
I think that flag was called searchControl in the past so we should allow both searchControl and search

**Comment by Xatpy** [comment]
The only reference about *searchControl* that I've found is in this [example](https://github.com/CartoDB/cartodb.js/blob/a3b001f6513e6fc93be6582c5886dae0f3d7c556/examples/mobile.html#L36) .

So...what do we do? If we had two flags..what would be the difference?

**Comment by Xatpy** [comment]
[PR #267](https://github.com/CartoDB/cartodb.js/pull/275)
