### ISSUE TITLE
layer selector showing hidden layers

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#282]
create a visualization and add 3 layers, hide 1.

It's not shown in the map but the layer selector says 3 layers are shown instead of two

**Comment by jaredMOH** [comment]
I'm also experiencing a similar problem. Layer 1 is enabled, 2, 3 and 4 are hidden. However on the published map it says '4 visible layers'. The legend is also no longer appearing.....

**Comment by javierarce** [comment]
Hi, @jaredMOH. We've just deployed a fix and your legend is appearing in the map. Sorry about it!
