### ISSUE TITLE
CartoDB's CSS breaks default styling for lists

### ISSUE THREAD

**Issue by JoseTomasTocino** [CartoDB/cartodb.js#291]
Loading CartoDB's CSS (`http://libs.cartocdn.com/cartodb.js/v3/3.11/themes/css/cartodb.css` as of today) wipes out default styling for unordered lists (and presumably ordered lists as well). 

[Check this fiddle](http://jsfiddle.net/svaq4brv/) for a simple testcase where you can clearly see that the padding and margin of the list items are lost.

**Comment by javierarce** [comment]
Hi, @JoseTomasTocino. Thanks for submitting the issue. We've removed the problematic CSS from the stylesheet: https://github.com/CartoDB/cartodb.js/commit/b6cc394592a7ed8dfdc8e5171d303ea729700429.

**Comment by JoseTomasTocino** [comment]
Thanks. Do you know when it will go live in the CDN?
