### ISSUE TITLE
Creating an image overlay by first time doesn't render the image

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#293]
but the sample image instead:

http://team.cartodb.com/u/iriberri/viz/944e6b2a-a0b0-11e4-8a06-0e4fddd5de28/embed_map

"Reapplying" the URL by clicking on the overlay makes it work again.

**Comment by javisantana** [comment]
I think this is a cartodb bug, the viz.json contains a rendered_text with the previous image. why do you think it's cartodb.js?
