### ISSUE TITLE
sublayer.hide() doesn't behave as expected with a multilayered named map

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb.js#303]
Neither `sublayer.toggle()` nor `sublayer.hide()` work as expected with named maps. I tried the same code with a normal map in CartoDB.js and it worked as expected. `sublayer.toggle()` returned true/false correctly but failed to hide or show the sublayer.

Here's some example code:
https://gist.github.com/ohasselblad/fc3345756fbb073aa0e7#file-index-html-L75

`layer.hide()` worked as expected.

**Comment by javisantana** [comment]
in order to make it work you need to add some template variables in your named map, just get one named map created by the UI

**Comment by ohasselblad** [comment]
ok, thanks. This feels like a workaround, but I got it to work with this:
http://bl.ocks.org/ohasselblad/663e5f8c336a05812a64

**Comment by javisantana** [comment]
opacity is not the best way because you are still fetching data from the database but works

**Comment by ohasselblad** [comment]
What's weird about that example is that the opacity is never 0, and it doesn't allow me to set the parameters/placeholders on the values. Is there something special about the name `layer0`, `layer1`, etc. that can't be changed via the template variables?

When opacity is set to 0, the interactivity should still work, but in that example it seems like sublayer.toggle() worked.
