### ISSUE TITLE
Change no-leaflet library names to no.leaflet

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#307]
http://libs.cartocdn.com/cartodb.js/v3/3.11.32/cartodb.noleaflet.js

versus

http://libs.cartocdn.com/cartodb.js/v3/3.11.32/cartodb_noleaflet.js

**Comment by javisantana** [comment]
unless you have really strong reason we will not change it since there are people using those files

**Comment by iriberri** [comment]
It's just that old versions use the '-' and some users were not able to
find this last version. @jmedina told me this was something to change,
close if not.

**Comment by xavijam** [comment]
Ok, let's keep it as it is. But I didn't change on purpose :(.
