### ISSUE TITLE
Using Torque Heatmaps on Mobile (Iphone) does continuosly pans

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb.js#311]
When trying

http://team.cartodb.com/u/saleiva/viz/2a308bb0-ab96-11e4-a5e6-0e018d66dc29/embed_map

On an iphone the map keeps panning to the center of the atlantic so i can not view the entire map. The loading icons also spins continuously and never stops.

That is regardless if the map is in "play" mode or "stop" mode.

**Comment by javisantana** [comment]
you have to slides with 6s and 3s transitions, it's not controlled by the torque timeslider

**Comment by fdansv** [comment]
This seems like it isn't to do with heatmaps but with the slides, which are configured to pan/zoom at those intervals.

**Comment by jatorre** [comment]
So the bug is on oddisey for not respecting the time slider or we have some definition problem on how slides work with time frames on a torque map. 

Also did not see controls for oddisey but I guess that is a different issue.

**Comment by javierarce** [comment]
Yeah, I'm creating a ticket to show the odyssey controls in mobile when there's a torque layer.

**Comment by javisantana** [comment]
> So the bug is on oddisey for not respecting the time slider or we have some definition problem on how slides work with time frames on a torque map.

Odyssey does not work using the animation time but the real time

**Comment by jatorre** [comment]
Right. So that might be confusing from a user perspective as there are two "timelines" going on at the same time. 

One possible way is disabling the option to do time slides entirely or in slides with torque on it. 

@saleiva what do you think?

**Comment by saleiva** [comment]
Yeah that's one of the things I had pending to thing. I spotted this last week while trying odyssey. Still thinking on a solution.

**Comment by saleiva** [comment]
Shall we close this?

**Comment by saleiva** [comment]
I think we need to think further the whole interaction when creating odyssey maps with time slide and torque...

**Comment by jatorre** [comment]
My initial suggestion. Remove the interaction of slides based on time, only allow on click. The interaction based on time I think is less useful and is confusing for this. 

Or remove it only for slides with torque. But I would remove the interactivity on time all together as a start.
