### ISSUE TITLE
Sublayer methods missing from Layer? 3.12

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb.js#326]
The following results in a JS error:

    window.onload = function() {
      cartodb.createVis('map', 'http://pramsey.cartodb.com/api/v2/viz/373759ce-b064-11e4-afcf-0e0c41326911/viz.json')
      .done(function(vis, layers) {

        var layers = vis.getLayers();
        var layer = layers[1];
        var sublayer = layer.getSubLayer(0);

      })
    }

JS says (referring to the line with "getSubLayer" in it)

    Uncaught TypeError: undefined is not a function

This also happens with getSubLayerCount()

**Comment by javisantana** [comment]
that's happening because layers[1] is a torque layer (which does not have a getSubLayer method) not a cartodb layer
