### ISSUE TITLE
cartodb.js with leaflet master

### ISSUE THREAD

**Issue by franckl** [CartoDB/cartodb.js#327]
Leaflet 0.7.3 is nearly 700 commits behind the master branch.
Would it be possible to publish a cartodb.js version with leaflet 0.8dev (= latest master) ?
Thanks

**Comment by javisantana** [comment]
I tried some time ago and cartodb code it's not compatible. I don't know what is the planned released date for leaflet 1.0.

In the meantime if you want to test you could use http://libs.cartocdn.com/cartodb.js/v3/3.11/cartodb_noleaflet.js using your own version of leaflet
