### ISSUE TITLE
IE10 fails to load data for infowindow that's already been viewed.

### ISSUE THREAD

**Issue by jlandfried** [CartoDB/cartodb.js#336]
This happens in IE10 Windows 8 (it may happen in other windows versions as well) cartodb.js 3.11.23  while viewing a map that has data added to the infowindow, it can be replicated on a cartodb provided example: http://docs.cartodb.com/tutorials/custom_interactivity.html

To replicate, in IE10:
* click a marker that opens an infowindow, then close it
* click another marker that opens an infowindow, close that.
*  click the original marker (The response generated from re-clicking the original marker should cause a response with a 304 status code to be returned)

In the example above, you'll notice that there's no city name included in the infowindow the second time that it's displayed.

In our case, we fixed this by overriding `SQL.prototype.execute`, wrapping the triggering of callbacks following an ajax callback in a setTimeout() (seen here - https://github.com/jlandfried/cartodb.js/commit/1706934388156405ad5fd3a338c0ebd6c3f3cc88).

I'm filing this as an issue, not a pull request, since I'm not that this something you even want to consider fixing since the issue seems to lie in IE10 and not the repository's code, and if you do want to fix it this may not be the approach you want to take, but I thought it should at least be brought to your attention.

Let me know if you could use any additional information.

**Comment by javisantana** [comment]
current supported versions are  3.11.36 and 3.12.0 but I don't think that fixes that issue. Thanks for the diff, we will check it

**Comment by jlandfried** [comment]
Thanks,
Fwiw, I'm just using what's being served at http://libs.cartocdn.com/cartodb.js/v3/cartodb.js
The demo that I linked to is using  cartodb.js 3.11.36

**Comment by Xatpy** [comment]
Thank you **very** much @jlandfried for your feedback.


setTimeout(…,0)

The explanation is in this [StackOverflow post](http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-so
metimes-useful) : 
Recaping: (there's a more large explanation in that post)
> what setTimeout does is add a new event to the browser event queue and the rendering engine is already in that queue (not entirely true, but close enough) so it gets executed before the setTimeout event. . 

Also, it was 'hard' to reproduce. I was using Windows 8.1 and InternetExplorer 11 **emulating IE 10**, but it was working correctly. So, I had to use a virtual machine from [modern.ie](https://www.modern.ie/) with Win8/IE10. There, I could reproduce the problem, but it wasn't happening always. I think that the Internet connection and speed in events are related.

*But*, I exectued tests and [one test failed "should call promise"](https://github.com/CartoDB/cartodb.js/blob/develop/test/spec/api/sql.spec.js#L147)

@javisantana , what do you think about this issue?

**Comment by javisantana** [comment]
I think there is no other way to manage that than deferring the calling for a tick. 

that test can be fixed increasing the timeout in that setTimeout for sure so I'd include @jlandfried 's patch including a link to this ticket.

thanks @jlandfried for you explanation, it's really good to get bug reports with this level of detail

**Comment by Xatpy** [comment]
great! 
[Pull request done](https://github.com/CartoDB/cartodb.js/pull/363)

**Comment by Xatpy** [comment]
Fix merged.
