### ISSUE TITLE
414 Request-URI Too Large when creating a sublayer with a very long SQL query

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb.js#340]
You can reproduce this with:

https://gist.github.com/danicarrion/9c1ba541219cd68517b4

You can uncomment the sql right before the big one to verify it works with a small query (look for the red polygons in Paris).

**Comment by javisantana** [comment]
use 3.12 cartodb.js version:

    <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.12/themes/css/cartodb.css" />
    <script src="http://libs.cartocdn.com/cartodb.js/v3/3.12/cartodb.js"></script>

it should be fixed

**Comment by danicarrion** [comment]
Fixed it is.

Thanks!
