### ISSUE TITLE
Uncaught ReferenceError: functionreturn_cdbc_cartodb is not defined

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#341]
cartodb.createVis with viz.json returns a JS error in the next url http://academy.cartodb.com/courses/03-cartodbjs-ground-up.html and the layers are not showing up, the basemap does, though

happening in latest Chrome for Mac

**Comment by javisantana** [comment]
use latest version of cartodb.js

**Comment by matallo** [comment]
thanks @javisantana!

**Comment by matallo** [comment]
now it mutated into 

![screen shot 2015-02-16 at 12 36 34](https://cloud.githubusercontent.com/assets/36676/6211275/881698c2-b5d8-11e4-866d-05e1d3109bfe.png)

from network request http://documentation.cartodb.com/api/v1/map?stat_tag=23f2abd6-481b-11e4-8fb1-0e4fddd5de28&config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%2223f2abd6-481b-11e4-8fb1-0e4fddd5de28%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22cartodb%22%2C%22options%22%3A%7B%22sql%22%3A%22select%20*%20from%20us_counties%22%2C%22cartocss%22%3A%22%2F**%20simple%20visualization%20*%2F%5Cn%5Cn%23us_counties%7B%5Cn%20%20polygon-fill%3A%20%23FFFFFF%3B%5Cn%20%20polygon-opacity%3A%200.8%3B%5Cn%20%20line-color%3A%20%23FFF%3B%5Cn%20%20line-width%3A%201%3B%5Cn%20%20line-opacity%3A%201%3B%5Cn%7D%22%2C%22cartocss_version%22%3A%222.1.1%22%2C%22interactivity%22%3A%5B%22cartodb_id%22%5D%7D%7D%2C%7B%22type%22%3A%22cartodb%22%2C%22options%22%3A%7B%22sql%22%3A%22select%20*%20from%20tornados_us%22%2C%22cartocss%22%3A%22%2F**%20bubble%20visualization%20*%2F%5Cn%5Cn%23tornados%7B%5Cn%20%20marker-fill-opacity%3A%200.9%3B%5Cn%20%20marker-line-color%3A%20%23FFCC00%3B%5Cn%20%20marker-line-width%3A%201%3B%5Cn%20%20marker-line-opacity%3A%201%3B%5Cn%20%20marker-placement%3A%20point%3B%5Cn%20%20marker-multi-policy%3A%20largest%3B%5Cn%20%20marker-type%3A%20ellipse%3B%5Cn%20%20marker-fill%3A%20%23F84F40%3B%5Cn%20%20marker-allow-overlap%3A%20true%3B%5Cn%20%20marker-clip%3A%20false%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%202800.1%5D%20%7B%5Cn%20%20%20marker-width%3A%2025.0%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%2053.405%5D%20%7B%5Cn%20%20%20marker-width%3A%2022.3%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%2019%5D%20%7B%5Cn%20%20%20marker-width%3A%2019.7%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%209.3%5D%20%7B%5Cn%20%20%20marker-width%3A%2017.0%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%205.015%5D%20%7B%5Cn%20%20%20marker-width%3A%2014.3%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%202.1%5D%20%7B%5Cn%20%20%20marker-width%3A%2011.7%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%200.96%5D%20%7B%5Cn%20%20%20marker-width%3A%209.0%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%200.46%5D%20%7B%5Cn%20%20%20marker-width%3A%206.3%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%200.21%5D%20%7B%5Cn%20%20%20marker-width%3A%203.7%3B%5Cn%7D%5Cn%23tornados%20%5B%20damage%20%3C%3D%200.058%5D%20%7B%5Cn%20%20%20marker-width%3A%201.0%3B%5Cn%7D%22%2C%22cartocss_version%22%3A%222.1.1%22%2C%22interactivity%22%3A%5B%22cartodb_id%22%5D%7D%7D%5D%7D&callback=function%20(){return%22_cdbc_%22+cartodb.uniqueCallbackName(JSON.stringify(t.toJSON()))}

```
functionreturn_cdbc_b._callbackName(
{
layergroupid: "478dc7b7428e59934d771bd6c8318514:1416283390111.47",
cdn_url: {
http: "ashbu.cartocdn.com",
https: "cartocdn-ashbu.global.ssl.fastly.net"
},
last_updated: "2014-11-18T04:03:10.111Z"
}
)
```

**Comment by matallo** [comment]
This doesn't apply anymore, closing then
