### ISSUE TITLE
Add null check for _d parameter in wax.cartodb.js onUp

### ISSUE THREAD

**Issue by gouldingken** [CartoDB/cartodb.js#36]
_d can be undefined in onUp if the click event contains a negative offset value. This can happen if a click even is triggered manually - e.g. through jQuery's trigger event. 

The error occurs in the  `else if (Math.round(pos.y / tol) === Math.round(_d.y / tol)` line below `interaction.click(e, _d);`

How to replicate:
e.g. 
$imgDiv is a jQuery reference to an img element.
$cb is a jQuery reference to an input element of type checkbox that is contained in a custom leaflet control.

```javascript
$imgDiv.click(function () {
	$cb.trigger('click');
});
```
A workaround is to fake out the x/y for the click event (as follows).
```javascript
$imgDiv.click(function () {
	var event = $.Event('click');
	event.clientX = 0;
	event.clientY = 0;
	$cb.trigger(event);
});
```

**Comment by javisantana** [comment]
this is a ticket for https://github.com/cartodb/wax
