### ISSUE TITLE
Bower version not built

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#367]
Installing cartodb.js from bower just provides a copy of this repo, which is pretty much useless since the point is to automate asset retrieval. I'd expect the version on bower to be a built version (the files produced by the grunt build step).

**Comment by rowanwins** [comment]
+1 please

**Comment by ElMesa** [comment]
Yep, plz solve this, Grunt+Bower haves it's audience. Me included

**Comment by matallo** [comment]
you can do now a `bower install cartodb.js`and it will install the dist files from https://github.com/CartoDB/cartodb.js-bower
