### ISSUE TITLE
Image documentation inside api.md

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#371]
We lack of cartodb.js documentation for static maps api in api.md, it's here:

https://github.com/CartoDB/cartodb.js/wiki/CartoDB-Map-API

**Comment by javierarce** [comment]
And if you need help clarifying something from that page, feel free to ask me, @ohasselblad.

**Comment by javierarce** [comment]
Moved to the docs repo.

**Comment by javierarce** [comment]
bump :dog:

**Comment by ohasselblad** [comment]
on it! will try to get it done this week
