### ISSUE TITLE
Do not send visible=false layers for static previews

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb.js#374]
See https://github.com/CartoDB/cartodb/issues/2470 for more information.

**Comment by javierarce** [comment]
@javisantana: there's something I don't understand from the [visibleLayers](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/layer_definition.js#L141) method. Using the [vizjson](https://team.cartodb.com/api/v2/viz/205862b2-1e55-11e4-a972-0e73339ffa50/viz.json) from the linked issue, `visibleLayers` returns 3 visible layers (when it should only be 1). The problem is that the method is using 'layer.options.hidden' to check the visibility, but the layers use the `visible` param instead.

**Comment by javisantana** [comment]
that method is internal and uses internal structures, it's not the same thing you have in the viz.json. It's set from sublayer https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/layer_definition.js#L1114

``visible`` is the one you want to use

**Comment by javierarce** [comment]
Ok, gotcha. So, I'll filter the layer list before and only send the visible ones to the layer definition constructor.

Thanks!
