### ISSUE TITLE
Legend shows if `legends` is unset for layer

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#380]
```js
var layer = cartodb.createLayer(map, url, {
  infowindow: false,
  tooltip: false
});
```

Where `map` is a google maps instance, the legend data shows up behind the tiles as they load. The layer isn't even enabled.

Adding `legends: false` stops the issue.

**Comment by fdansv** [comment]
@knownasilya can you point me to an example where this is happening, in order to replicate the issue? Thanks!
