### ISSUE TITLE
Torque layer with named map must request the named map

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb.js#397]
## STR
1. Create a points private table
1. Create a visualisation from it
1. Use a torque wizard

## Current result
The viz.json does not return a `namedmap` layer but only a torque layer with an associated named map.
cartodb.js tries to instantiate a layergroup through the anonymous endpoint with the torque layer.

## Expected result
As the torque layer has an associated namedmap cartodb.js should instantiate the layergroup with its associated named map instead of using the anonymous way.

Ref: https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/image.js#L162

See https://github.com/CartoDB/cartodb/issues/2705

**Comment by rochoa** [comment]
Thanks @javisantana and @Kartones for helping me understanding better the viz.json :+1:

**Comment by rochoa** [comment]
cc @saleiva

**Comment by saleiva** [comment]
@javierarce this is important since is one of the things that are more visible on the new dashboard.

**Comment by javierarce** [comment]
I know, I'm waiting for a review of this: https://github.com/CartoDB/cartodb.js/pull/398

**Comment by saleiva** [comment]
ah ok!

**Comment by javierarce** [comment]
I've released a new version of cartodb.js with the fix. I'll update CartoDB so the change appears in the editor.

**Comment by rochoa** [comment]
:heart_eyes:
