### ISSUE TITLE
featureClick is not reporting the right x,y on touch devices

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#4]

**Comment by saleiva** [comment]
Is this still happening? Assigning to @fdansv

**Comment by fdansv** [comment]
As far as i know this isn't happening anymore, but @Xatpy probably knows more.

**Comment by saleiva** [comment]
@Xatpy , if this is not happening anymore, close!

**Comment by Xatpy** [comment]
Yep! This is working! 
(Retested again with this [viz.json](http://find.cartodb.com/api/v2/viz/a9a1cf1a-761e-11e4-a8ac-0e018d66dc29/viz.json) )
