### ISSUE TITLE
cartodb.createLayer won't load data via HTTPS

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb.js#410]
I just discovered a bit of a blocking issue for the app we're developing powered by CartoDB. Our app is served over HTTPS, but by default (and in all the tutorials) `cartodb.createLayer` loads data over HTTP, which throws the following error in the browser console:

```
Mixed Content: The page at '[redacted]' was loaded over HTTPS, but requested an insecure script 'http://[usernamehere].cartodb.com/api/v1/map/named/tpl_cbaa8a164_b876_11e4_bf…bf3f-0e4fddd5de28&config=%7B%22layer0%22%3A1%7D&callback=_cdbc_910841071_1'. 
This request has been blocked; the content must be served over HTTPS.
```

Changing the URL in the cartodb.createLayer call from HTTP to HTTPS returned the same error. Ex:

```javascript
  cartodb.createLayer(this.map, 'https://[usernamehere].cartodb.com/api/v2/viz/cbaa8a164-b876-11e4-bf3f-0e4fddd5de28/viz.json')
    .addTo(this.map);
```

**CartoDB:** 3.12.13

**Comment by joeyklee** [comment]
@mnquintana Hi there - I also ran into this same issue (https://github.com/CartoDB/cartodb.js/issues/1308). Do you mind sharing the solution? Many thanks!
