### ISSUE TITLE
Variable 'i' is not defined at _createLegendView 

### ISSUE THREAD

**Issue by alasarr** [CartoDB/cartodb.js#415]
_createLegendView method at vis.js tries to set the layer.legend.index = i. It launches an exception because variable 'i' is not defined. Check this out: https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/vis.js#L818

It doesn't happen with the compressed version so I think this line could be removed by the compressor or any other tool that you're using to build CartoDB.js

I've just commented this line and it works, but I don't know if it could break other things:
https://github.com/CartoDB/cartodb.js/compare/develop...GeographicaGS:dev-fix-vis_createLegendView

**Comment by javisantana** [comment]
yes, you are totally right, could you PR that?

**Comment by alasarr** [comment]
Of course, give me one minute.
