### ISSUE TITLE
Undefined is not a function on createLayer  - probably should be a different error?

### ISSUE THREAD

**Issue by voltagex** [CartoDB/cartodb.js#422]
With the following code: (which is a variant of http://docs.cartodb.com/cartodb-platform/cartodb-js.html#creating-visualizations-at-runtime)

```javascript
        var mapOptions = {
            center: { lat: -34.397, lng: 150.644 },
            zoom: 5
        };
        map = new google.maps.Map(document.getElementById('map'),
            mapOptions);


        cartodb.createLayer(map, {
            user_name: 'adambaxter',
            type: 'cartodb',
            sublayers: [{
                sql: "SELECT * FROM sa4_paths_merge",
                cartocss: '#sa4_paths_merge {polygon-fill: #F0F0F0;}'
            }]
        }).addTo(map);
    }

    google.maps.event.addDomListener(window, 'load', init);
```

I get "undefined is not a function" on line 35499 of http://libs.cartocdn.com/cartodb.js/v3/3.12/cartodb.uncompressed.js
which corresponds to         
    var mapView = new MapType({

so probably https://github.com/CartoDB/cartodb.js/blob/0aea85812ead7e2ee0d27e451e7f6063f7747247/src/api/layers.js#L147

map is definitely a Google Maps object

**Comment by voltagex** [comment]
Also getting a similar error when using a Leaflet object.

**Comment by ohasselblad** [comment]
It might be because you need to put `map = ...` instead of `var map = ...`

**Comment by javisantana** [comment]
Is google maps javascript included before including cartodb.js?

**Comment by voltagex** [comment]
...yep, I'm an idiot. Thanks @ohasselblad. I looked at that for a day without seeing the problem. I'll add `use strict` next time
