### ISSUE TITLE
Torque controls are not removed after a torque layer is removed

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#427]
Removing a torque layer with `map.removeLayer(layer)` is not removing the torque controls. We should provide a way to remove everything torque related so that users can add more torque layers, etc.

**Comment by alonsogarciapablo** [comment]
[Here's where we supposedly clean up everything](https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/vis.js#L233).

**Comment by fdansv** [comment]
```map.removeLayer``` is a leaflet method, so it won't trigger the event you're referencing. The method that will remove the layer and the timeslider is [```layer.remove()```](http://docs.cartodb.com/cartodb-platform/cartodb-js.html#sublayerremove)

**Comment by javisantana** [comment]
removeLayer calls onRemove so it should work at some point if everything is set up properly

**Comment by fdansv** [comment]
This is a Torque issue then, and it's been resolved in https://github.com/CartoDB/torque/pull/172
