### ISSUE TITLE
SQL request from javascript

### ISSUE THREAD

**Issue by Casyfill** [CartoDB/cartodb.js#430]
I am requesting data from mysql from a webpage with a copypasted request function:

function getData(){
    
    var sql = new cartodb.SQL({ user: 'rilos', format: 'geojson', dp: 5});
    sql.execute("SELECT * FROM topdatum")
        .done(function(data) {
        console.log(data.rows);
        })
        .error(function(errors) {
        // errors contains a list of errors
        console.log("errors:" + errors);
        })
          
}

However, I always receives  "No 'Access-Control-Allow-Origin' header"  warning instead of data.
How can I fix that?

**Comment by Casyfill** [comment]
Well, I defined the problem is with my sintax - I need to use enterprise server and I dont know how to put both my login and company name in sintax

**Comment by javisantana** [comment]
'rilos' username does not exist in cartodb.com

I'd recommend you to ask in stackoverflow about this, if you confirm this is an issue, report it here with detailed steps
