### ISSUE TITLE
interactivity fails in IE11

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#443]
http://gis.stackexchange.com/questions/142647/cartodb-featureclick-event-in-ie11

**Comment by fdansv** [comment]
Just checked this and nteractivity works as expected in IE11, using the example provided.

**Comment by fdansv** [comment]
Sorry, accidentally closed

**Comment by fdansv** [comment]
I'm closing this as we're not getting a reply on SE. Reopen if necessary.

**Comment by galiya** [comment]
I am using the following sample: http://bl.ocks.org/javisantana/7200781 
I've noticed that I have "Edge (default)" in my IE by default which stops the sample from working correctly. If "10" is selected then map works as expected.

**Comment by fdansv** [comment]
I'm trying it and to me it works both in Edge and 10. Do you get any exceptions on the console? If not, can you record a video of it not working?

**Comment by galiya** [comment]
I can't see any exceptions on the console. I've recorded a small video - please check here: https://www.dropbox.com/s/a3cvaerodtvdjwp/CartoDB%20Issue%20with%20IE.WMV?dl=0
