### ISSUE TITLE
Display date ranges in timeslider only if whole range is less than a year

### ISSUE THREAD

**Issue by fdansv** [CartoDB/cartodb.js#455]
The change we introduced the other day to the timeslider --showing date ranges when steps span more than a day-- should only affect visualizations that span less than a year. Otherwise visualizations that span several years become very confusing.

cc @javisantana, @ohasselblad

**Comment by alonsogarciapablo** [comment]
@fdansv I think this issue can be closed, right?

**Comment by fdansv** [comment]
Oh, indeed! Weird that I missed this the other day, when I was doing some issue cleanup.
