### ISSUE TITLE
make sure all the default basemaps are switch to http

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#458]
https://github.com/CartoDB/cartodb-platform/pull/457

we have a mapping to convert https to http in case https is not active, be sure all the urls are converted right

https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/layers.js#L11

**Comment by santisaez** [comment]
@fdansv: we've just merged https://github.com/CartoDB/cartodb-platform/pull/457, so now we're forcing all basemap HTTP requests to always use `https://`.

**Comment by zenitraM** [comment]
That mapping is missing our recent basemaps:
`{s}.basemaps.cartocdn.com` should become `cartodb-basemaps-{s}.global.ssl.fastly.net` on SSL

**Comment by fdansv** [comment]
ACK :+1:

**Comment by fdansv** [comment]
Fixed/added URL templates in #465.
