### ISSUE TITLE
Callback or event with setSQL

### ISSUE THREAD

**Issue by Pirhoo** [CartoDB/cartodb.js#472]
Hi guys,

is there a way to detect the end of `setSQL` on a sublayer? I tried to listen the "load" event but it's never called.

Very best,

Pierre

**Comment by javisantana** [comment]
"load" event is called on the layer (not on the sublayer) when all the tiles are loaded after you change sql or cartocss, is it not working for you?

**Comment by Pirhoo** [comment]
Indeed, "load" event is working now. I was trying to bind it directly after `cartodb.createLayer()`. Thanks!
