### ISSUE TITLE
Update npm build

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb.js#495]
I'm trying to use cartodb.js (specifically the SQL module) client-side with npm as opposed to bower, but [the build is quite outdated (v3.5.6)](https://www.npmjs.com/package/cartodb.js). Note that although [this similarly-named library exists](https://www.npmjs.com/package/cartodb), it provides a very different API from what I'm looking for (and also hasn't been updated in 5 months). Could you please release an up-to-date version of cartodb.js on npm? Thanks!

**Comment by mhkeller** [comment]
+1 I'd like to rewrite [this plugin](https://github.com/mhkeller/cartodb-embeds) using browserify instead of bower and it would be great to get the most up to date package from npm.

**Comment by alonsogarciapablo** [comment]
@javisantana I've tried to publish a new version of the library but I don't have the required permissions. Would you mind adding me as a collaborator? Thanks!

**Comment by javisantana** [comment]
@alonsogarciapablo i need your npm username

**Comment by alonsogarciapablo** [comment]
I'm `alonsogarciapablo`. Thanks!

**Comment by javisantana** [comment]
done

**Comment by alonsogarciapablo** [comment]
I've published cartodb.js 3.15.1 to npmjs. It's currently not possible to use/require the library as an npm module. We will probably consider this option in the future.
