### ISSUE TITLE
document cdb.vis.Vis.addTooltip and cdb.vis.Vis.addInfowindow

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb.js#506]
In code [here](https://github.com/CartoDB/cartodb.js/blob/69b730bbcba1bdc4e5c107b6ff379f1640c22a28/src/vis/vis.js#L1122-L1131) and [here](https://github.com/CartoDB/cartodb.js/blob/69b730bbcba1bdc4e5c107b6ff379f1640c22a28/src/vis/vis.js#L1403).

Usage [here](https://github.com/CartoDB/training/blob/gh-pages/workshops_map.html#L107) on anonymous maps and [here](http://docs.cartodb.com/tutorials/named_maps.html#creating-named-maps) for named maps.

cc @javisantana

**Comment by LightGuard** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
@csobier assign this to you. Please, feel free to close it.

**Comment by csobier** [comment]
Closing, it was reported back in February that `cdb.geo.u`i code is broken and [no longer supported](https://github.com/CartoDB/cartodb.js/pull/1133) in CartoDB.js. All supported tooltip/infowindow code is doc'd [here](https://docs.cartodb.com/cartodb-platform/cartodb-js/ui-functions/).
