### ISSUE TITLE
CartoDB.js seems not to load named maps by https when required

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#517]
For example, code like:

````
 cartodb.createLayer(map, {
                user_name: user,
                type: 'namedmap',
                https: true,
                named_map: {
                    name: 'name_whatever',

````

The following error appears:

The error generated is as follows (in Chrome)...

Mixed Content: The page at '****' was loaded over HTTPS, but requested an insecure script 'http://user.cartodb.com/api/v1/map/named/name_whatever/jsonp?config=(params_here)%2C%22layer0%22%3A1%7D&callback=_cdbc_1710709996_2'. This request has been blocked; the content must be served over HTTPS.

cc @javisantana 

Further details at SB/5598085

**Comment by alonsogarciapablo** [comment]
The `https` options shouldn't be there. It's not very clear in the documentation where to put those options. I've hopefully clarified it in [#508](https://github.com/CartoDB/cartodb.js/pull/508/).

It should be something more like:

```
 cartodb.createLayer(map, {
  user_name: user,
  type: 'namedmap',
  named_map: {
    name: 'name_whatever',
    ...
  }, {
    https: true
  }
}
```

Please re-open the issue if this doesn't solve the problem. Thanks!

**Comment by derekeder** [comment]
Just ran into this issue myself. The docs are pretty unclear about where you put that `https` config variable. Could it be added to the primary layer options object?

Or better yet, HTTPS would be enabled automatically if I'm loading the cartodb.js library via HTTPS.

**Comment by javisantana** [comment]
yes, I think you are right (not sure but I remember we were doing that at some point) 

cc @alonsogarciapablo

**Comment by voltagex** [comment]
We've just been bitten by this in production - can you clarify where `https` is meant to go?
