### ISSUE TITLE
interactivity layer index is wrong with named maps where cartodb layer is not the first one

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#518]
- create a named map with these layers:
  - http
  - cartodb (with some interaction)
- using createLayer instance that named map and enable interactivity

check the requests done by the client, it tries to fetch grid.json tiles for layer 0 when it should be layer 1

THis needs to be fixed in 3.11, 3.12, 3.13, 3.14 and 3.15 branches

**Comment by knownasilya** [comment]
I seem to be having similar issues, see the working example http://stocktonca.mapgeo.alpha1.appgeo.com/ and the broken example http://gloucesterma.mapgeo.alpha1.appgeo.com/. The broken example in `gridFeature` only has one item in `keys` and it's just a blank string. The key is always `0`.

**Comment by knownasilya** [comment]
The only differences that I see between the two is that they are on different cartodb accounts.

**Comment by jsanz** [comment]
Hi @knownasilya we need a bit more of context to help you.

I can see your `grid.json` calls receive data on both examples but can't proceed to fire an interactivity so can you please give more detail on the procedure to detect the problem and the expected results?

cc @CartoDB/solutions

**Comment by knownasilya** [comment]
@jsanz so this is what I'm seeing for grid.json for each

stocktonca:
<img width="584" alt="screen shot 2016-03-08 at 1 37 48 pm" src="https://cloud.githubusercontent.com/assets/34726/13611973/267604dc-e533-11e5-9165-f2905c0e4d5a.png">

gloucesterma:
<img width="583" alt="screen shot 2016-03-08 at 1 38 30 pm" src="https://cloud.githubusercontent.com/assets/34726/13611986/2e2b67b2-e533-11e5-98c5-5963aba6c42f.png">


stocktonca uses the 'clientdemos' account, and gloucesterma uses the 'mapgeoprod' account.

**Comment by jsanz** [comment]
Well on the second example if I switch on the `Water Resource Protection` layer I get utf-grids with data

https://cartocdn-gucf.global.ssl.fastly.net/mapgeoprod/api/v1/map/mapgeoprod@2a25944e@f7f361c1da7d2f5ccedfdda7095fd38c:1438112477751/0/11/621/755.grid.json?callback=grid

Apart from receiving utf-grids with data, what else are you expecting to happen? I can't see any interaction on both examples (I mean tooltips or infowinows).

**Comment by knownasilya** [comment]
I have a `on('featureClick'` that I expect to work, but it doesn't since no feature is returned.
