### ISSUE TITLE
Allow viz.json URLs that don't start with "http"

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#519]
Right now, [we only support URLs that start with "http"](https://github.com/CartoDB/cartodb.js/blob/sandwich/src/api/layers.js#L45).

We should also be able to do things like:
```
cartodb.createLayer(map, './viz.json').addTo(map);
```

cc// @javisantana

**Comment by javisantana** [comment]
:D

**Comment by fdansv** [comment]
OK so we want to use relative addresses. Here's the thing: are we assuming that the file will always be called via jsonp? (adding a `<script>` tag to the DOM). If the file is in the same domain, as it is in this use case, there is no need for the use of jsonp, right? What do you think of this:

https://github.com/CartoDB/cartodb.js/blob/03688591d2ec70f9e66cfc77988a03f537662c42/src/core/loader.js#L24-L37

**Comment by alonsogarciapablo** [comment]
Sounds reasonable to me.

**Comment by fdansv** [comment]
Fixed in #536
