### ISSUE TITLE
Unable to make changes to torque config after first using the wizard

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb.js#529]
When applying the torque wizard, the initial torque animation runs with cartodb_id as the time column, but this error appears in the console: 

`Uncaught Error: TrackJS Caught: Cannot read property 'options' of undefined y.wrapError @ tracker.js:26 l.wrapAndCatch.d.util.hasFunction.a.(anonymous function).d.util.hasFunction.f.(anonymous function) @ tracker.js:4`

Any other attempts to modify the torque config, either in the wizardor the CartoCSS pane do not work until the page is reloaded.

**Comment by javisantana** [comment]
this is cartodb, right? cc @fdansv

**Comment by fdansv** [comment]
Yes, if it's related to the wizard or tabs it goes under cartodb/cartodb

**Comment by chriswhong** [comment]
I'll move it.
