### ISSUE TITLE
no_cdn is missing from options in createLayer

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb.js#531]
no_cdn can be used as an option to createVis, but not with createLayer. This prevents createLayer from working with a leaflet map directly on the On-premises, for instance.

**Comment by javisantana** [comment]
which cartodb version? could you post a non working example?

Basically since new onpremise version the cdn url is set from the tiler so even if you don't set no_cdn cartodb.js will not use the cdn

**Comment by danicarrion** [comment]
1.0.7, sorry. I will try with 1.0.8 and let you know if it works

**Comment by javisantana** [comment]
And cartodb.js version?

**Comment by danicarrion** [comment]
@javisantana this is still happening with 1.0.8 and 3.15.8

**Comment by danicarrion** [comment]
actually, I can't even do a createVis with 3.15, I need to revert to 3.14

**Comment by javisantana** [comment]
since 3.15 (i think) the tiler controls if cartodb.js should go through the cdn or not. What is the usecase here because this might be a tiler problem not a cartodb.js one

**Comment by danicarrion** [comment]
anyway, this should actually be backported to 3.14, as this is what people with onprem 1.0.8 (currently, practically all of our users) can work with (1.0.8 is not compatible with 3.15)

**Comment by acanimal** [comment]
Hi Dani,
although not documented it is also possible to pass the `no_cdn` option to the `createLayer` method.
