### ISSUE TITLE
Custom infowindows with image header: "Header image url not valid"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#533]
Sometimes, when creating a custom infowindow and using the image header template those images are not rendered in the embed (and CartoDB.js returns "Header image url not valid").

@xavijam has been checking with me and this seems to be a known issue caused by the fact that although the column that contains the image is set in the first position, the system is reordering the columns alphabetically.

This provokes that the image column that contains the URL is no longer the first one, so the code gets the first column (by alph. order) and tries to apply to it a Regexp for URLs that any string of text different than a URL won't match.

The work around for this would be renaming the column that contains the image so that after the reordering, it is set in the first position and the code is able to match it with the regexp and show it as a valid image.

If not, the image is indeed requested but set as display:none.

**Comment by javisantana** [comment]
umh, the system should order the column based on the order attribute, not alphabetically, where is that order? I think this is a cartodb issue

**Comment by alonsogarciapablo** [comment]
I've worked on a couple of similar issues:

- https://github.com/CartoDB/cartodb/issues/2235
- https://github.com/CartoDB/cartodb/issues/1970

@iriberri it would be great if you could provide some steps to reproduce.

**Comment by iriberri** [comment]
I'm not able to reproduce this issue with some specific steps, each time I try to replicate a scenario it works for me. It could be that some specific action is provoking the reordering of the columns, but I really have no clue for this...
