### ISSUE TITLE
Basemaps are loaded on top of GMaps when creating a visualization

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb.js#542]
When creating a visualization with `createVis` and the `gmaps_base_style` option, the original basemap of the visualization is not removed, covering the google basemap.

http://bl.ocks.org/jsanz/9fa737db4623fb54d15f

Reported at #541 also by @MuellerMatthew

**Comment by javisantana** [comment]
this needs to be fixed https://github.com/CartoDB/cartodb/pull/4154

**Comment by alonsogarciapablo** [comment]
Fixed by cartodb/cartodb#4197.
