### ISSUE TITLE
Uncaught ReferenceError: Mustache is not defined

### ISSUE THREAD

**Issue by turban** [CartoDB/cartodb.js#543]
We're not able to upgrade our mapping stack to use a later version of cartodb.js due to a conflict with mustache. Previously we've used cartodb_noleaflet.js (created with grunt build) 

This file now returns this error: 
Uncaught ReferenceError: Mustache is not defined

It seems like mustache is not included in the build file. This problem is related to this issue: https://github.com/CartoDB/cartodb.js/issues/408

We need to load our mapping components with require.js, and loading cartodb.js and/or mustache in a script tag is not an option.

**Comment by turban** [comment]
Mustache is included in the build file, but the UMD-wrapper around the library is causing trouble: 

```javascript
(function (global, factory) {
  if (typeof exports === "object" && exports) {
    factory(exports); // CommonJS
  } else if (typeof define === "function" && define.amd) {
    define(['exports'], factory); // AMD
  } else {
    factory(global.Mustache = {}); // <script>
  }
}(this, function (mustache) {
```

When we use require.js (AMD) on other parts of our site, the first else if is called, and the Mustache object is not accessible. It works if I force "script-version": 

```javascript
(function (global, factory) {
  //if (typeof exports === "object" && exports) {
  //  factory(exports); // CommonJS
  //} else if (typeof define === "function" && define.amd) {
  //  define(['exports'], factory); // AMD
  //} else {
    factory(global.Mustache = {}); // <script>
  //}
}(this, function (mustache) {
```

**Comment by turban** [comment]
Is it possible to strip/change the UMD-wrapper from Mustache.js before including it in the CartoDB.js bundle? We need to force the last else clause, as this is what Cartodb.js is expecting.

**Comment by javisantana** [comment]
could you try this: https://dl.dropboxusercontent.com/u/3913348/test/cartodb.uncompressed.js

this uses your proposed solution: https://github.com/CartoDB/cartodb.js/pull/647

**Comment by turban** [comment]
It works! 

![screen shot 2015-08-12 at 14 24 48](https://cloud.githubusercontent.com/assets/548708/9223837/0cff6892-40fe-11e5-8b03-08c5b5819def.png)

I need the fix in cartodb_noleaflet.js, please notify me when the bower repo is updated: https://github.com/CartoDB/cartodb.js-bower

**Comment by javisantana** [comment]
Ok, so we go ahead with that fix, we will release a new version with that

**Comment by javisantana** [comment]
fixed in https://github.com/CartoDB/cartodb.js/pull/647

**Comment by chriswhong** [comment]
+1, need a no mustache version in order to load cartodb.js within a splunk app. @xavijam

**Comment by turban** [comment]
@javisantana I tried to run "bower install cartodb.js" and got version 3.15.6. I still get the Mustache error with cartodb_noleaflet.js. Is it still not available in production?

**Comment by javisantana** [comment]
@matallo is the one in charge or bower stuff

**Comment by alonsogarciapablo** [comment]
Hello @turban. We're currently updating the version on CartoDB.js in bower every time we release a new version (3.15.6 is the latest). I will take a look at this.

**Comment by turban** [comment]
Thanks @alonsogarciapablo, it seem like https://github.com/CartoDB/cartodb.js/pull/647 (undefine define) is not present in the Bower repo.

**Comment by alonsogarciapablo** [comment]
Hey @turban I've released a new version (3.15.7) and this should be fixed. Could you please confirm that it's working correctly with bower? Thanks!

**Comment by turban** [comment]
Version 3.15.7 is not available in bower repo. Could you update this as well?

**Comment by alonsogarciapablo** [comment]
Sorry @turban. We've a script that does all this for us and it's still not working correctly. I just manually tagged [3.15.7](https://github.com/CartoDB/cartodb.js-bower/releases/tag/3.15.7).
