### ISSUE TITLE
Numeric columns with just the value zero raise an error

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb.js#574]
If you try to analyze such a column (ie: 0,0,0,0…0) the api sql returns this error:

```lower bound cannot equal upper bound```

(I haven't tried with different sets of values, but it probably fails too)

Can you have a look to this? We should also try to capture the exception (the `execute` method accepts an error function as a callback, although I wasn't able to use it) and return something (otherwise the analysis won't finish)

/cc Thanks for pointing us to this problem, @matallo

**Comment by fdansv** [comment]
CC'ing @ohasselblad since he might have a clue.

**Comment by matallo** [comment]
:raised_hands:
