### ISSUE TITLE
secrets.json not needed

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#618]
there are some commands such

```
make cartodb dist/cartodb.css
```

where there isn't really needed a `secrets.json`, instead of preventing the command to execute, another strategy should be followed (like having an empty `secrets.development.json` and using an `env` variable in the makefile

**Comment by viddo** [comment]
This also causes [CartoDB PR-testing](http://clinker.cartodb.net/jenkins/job/CartoDB-PR-testing/5304/consoleFull) to silently fail the cdb task (not failing tests, yet, though), seems to be warning and not error output, e..g:
```bash
...
Loading "Gruntfile.js" tasks...ERROR
14:36:38 >> Error: Unable to read "secrets.json" file (Error code: ENOENT).
14:36:38 Warning: Task "dist_js" not found. Use --force to continue.
14:36:38 
````

**Comment by alonsogarciapablo** [comment]
The `dist_js` task is also failing in the deploy:

```
 ** [out :: bch01.gewd.cartodb.net] grunt dist_js
 ** [out :: bch01.gewd.cartodb.net] Loading "Gruntfile.js" tasks...[31mERROR[39m
 ** [out :: bch01.gewd.cartodb.net] [31m>> [39mError: Unable to read "secrets.json" file (Error code: ENOENT).
 ** [out :: bch01.gewd.cartodb.net] [33mWarning: Task "dist_js" not found. Use --force to continue.[39m
 ** [out :: bch01.gewd.cartodb.net] 
 ** [out :: bch01.gewd.cartodb.net] [31mAborted due to warnings.[39m
```
