### ISSUE TITLE
subLayer.isVisible() is not a function error

### ISSUE THREAD

**Issue by TheSisb** [CartoDB/cartodb.js#632]
According to the docs, subLayer.isVisible() is something I should be able to do.  See: http://docs.cartodb.com/cartodb-platform/cartodb-js.html#sublayerisvisible

Unfortunately I'm getting an error. Working reproduction of error: http://jsfiddle.net/vc7m6ro4/
Please see console output.

Chrome latest / Mac OSX

**Comment by javisantana** [comment]
You should be using 3.15 instead of 3.11.

Also you are using gmaps 3.exp version which we didn't tested with cartodb.js (looks like it works but just in case)

**Comment by TheSisb** [comment]
Thanks.
