### ISSUE TITLE
Bug in IE and Firefox when map div is position fixed

### ISSUE THREAD

**Issue by turban** [CartoDB/cartodb.js#639]
This is the same bug as reported here: https://github.com/CartoDB/cartodb.js/issues/114

It now works in Chrome and Safari, but there is still an offset bug in Firefox and IE 8, 9, 10 and Edge. 

To reproduce the bug (using CartoDB.js 3.15.1):

1. Go to this page: http://thematicmapping.org/playground/cartodb/bugs/fixedpos.html
2. Scroll down the page (most of our maps are embedded in news articles).
3. Click the fullscreen button. We're using a fixed positioned div to show the map in fullscreen. 
4. Click on a region, the popup is shown far off the map and not where the user clicked. 
5. Popups in Leaflet works as expected in all browsers, so this is a CartoDB.js bug. 

![screen shot 2015-08-05 at 14 07 08](https://cloud.githubusercontent.com/assets/548708/9085243/50b3324a-3b7b-11e5-84d4-cbf8bbfa2914.png)
 
Hope this bug will be fixed across all browsers and devices :-)

**Comment by javisantana** [comment]
noooooo!! we will take a look @turban

**Comment by turban** [comment]
Hi, is this issue being worked on?

**Comment by turban** [comment]
We're still having trouble with this offset issue, and our CartoDB-maps is not working properly in Firefox and IE. 

![screen shot 2015-09-11 at 09 48 19](https://cloud.githubusercontent.com/assets/548708/9809636/56586254-586a-11e5-9c39-2639c0978344.png)

**Comment by alonsogarciapablo** [comment]
Thanks for providing an example @turban! I'll take a look at this!

**Comment by alonsogarciapablo** [comment]
We'll include the fix for this issue in the next release, which will happen in the next days.

**Comment by alonsogarciapablo** [comment]
Hey! This issue should be now fixed. @turban your example should work with [this new version](http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js).
