### ISSUE TITLE
the colors in the legends are not showing

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb.js#643]
A user has a case where she opens the map created with the editor, the legends are shown but they don't have the colors. This problem happens when she opens the map with Internet Explorer 11.( in other browsers it works).
![legend_not_show](https://cloud.githubusercontent.com/assets/11177693/9111848/f5f8b796-3c4a-11e5-875c-8d94cf0dae10.png)

**Comment by javierarce** [comment]
This is duplicated: https://github.com/CartoDB/cartodb.js/issues/431. I'll fix it in the current milestone.
