### ISSUE TITLE
update leaflet to 0.7.4

### ISSUE THREAD

**Issue by franckl** [CartoDB/cartodb.js#665]
The latest version has just been published
http://leafletjs.com/2015/09/01/leaflet-0.7.4-released.html

**Comment by louh** [comment]
:+1: 
Bumping to [0.7.7](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) would be fantastic. 0.7.4 onwards has better mobile detection for example.

**Comment by knownasilya** [comment]
Does 3.15.x work with 0.7.7?

**Comment by techieshark** [comment]
👍 Bumping to Leaflet v1.0 which [just came out](http://leafletjs.com/2016/09/27/leaflet-1.0-final.html) would be awesome. Maybe in cartodb.js v4?

**Comment by easherma** [comment]
+ 1 Leaflet 1.0 adds some useful features

**Comment by chriswhong** [comment]
+1 for Leaflet 1.0.1, mostly for `map.flyTo()` and Tooltips.  Issue here: https://github.com/CartoDB/cartodb.js/issues/1503

**Comment by alonsogarciapablo** [comment]
We'll be including Leaflet 1.x in the next version of the library.
