### ISSUE TITLE
JS error trying to evaluate leaflet attribution

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#676]
https://my.trackjs.com/messages/filtered?message=TypeError%3a+%27undefined%27+is+not+a+function+(evaluating+%27function(a)%7bthis.map_leaflet.attributionControl.addAttribution(a)%7d.bind(this)%27)&page=4

**Comment by xavijam** [comment]
cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
Most of the traffic causing this bug is coming from bots: AppleBot, phantomJS, cXensebot 1.1, ...

**Comment by xavijam** [comment]
Closing since the error is not happening anymore.
