### ISSUE TITLE
Can't load Torque layer from viz.json in createLayer CartoDB.js 3.15.

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#678]
Today a user reported that an application stopped working. After investigating a bit, I was able to reproduce the issue, and the code to do it is here: https://gist.github.com/iriberri/3e3761496dc83d0b312d

By using a viz.json from a Torque visualization (there are no more layers than the Torque one), createLayer and CartoDB.js 3.15, the layer is not loaded. It works with 3.14 though.

I have tried to change to several basemaps, in case this was something due to how basemaps are written in the viz.json due to sandwiching, but different basemap approaches didn't have any effect in 3.15 neither in 3.14 (in which everything worked with any basemap).

**Comment by iriberri** [comment]
@alonsogarciapablo, any idea? :)

**Comment by alonsogarciapablo** [comment]
Yes. It seems that [this commit](https://github.com/CartoDB/cartodb.js/commit/30dca98e51defe0c171a92c24f4d400d4bf87eb3) have introduced a bug. I'm working on a fix.

**Comment by iriberri** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
I just released [Cartodb.js 3.15.5](http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js) with the fix for this issue.
