### ISSUE TITLE
CartoDB.js 3.15.5: Uncaught TypeError: Cannot set property '_attributions' of undefined

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb.js#681]
If a CartoDB is used over a Leaflet map in which the `attributionsControl` (more info [here](http://leafletjs.com/reference.html#control-attribution)) is set to false:

```js
map = L.map("map", {
  zoom: 11,
  center: [28.175278, -81.370102],
  layers: [ggl2],
  zoomControl: false,
  attributionControl: false
});
````

CartoDB.js raises the following error:

`Uncaught TypeError: Cannot set property '_attributions' of undefined`

This scenario happens in a use case in which the user is using GMaps + Leaflet at the same time. As the GMaps attribution already exists, the user decided to remove the Leaflet one.

**Comment by alonsogarciapablo** [comment]
There are a couple of problems that @iriberri discovered that I'm going to fix:

- [ ] Leaflet map might have `attributionControl` set to false and CartoDB.js should still handle attributions correctly. 
- [ ] Leaflet map might have some other layers with attributions, and these shouldn't be removed.
