### ISSUE TITLE
Layers with very long CartoCSS are not working under IE9

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#692]
### STR

- Create a map in CartoDB with only a layer. 
- Add a very long CartoCSS for that layer.
- Create a new html trying to recreate that map (```...createVis()```).
- Test that map in Chrome, it should work.
- Test that map in IE9 (Win 7?).

### Happening
- The map will not show the CartoDB layer, but no error appears.
- Check the last request sent (GET), it goes to /api/vX/map and it contains javascript code on it.

### Expected
- Due to IE9 doesn't support CORS, it should use [LZMA](https://github.com/nmrugg/LZMA-JS) for compressing the request params. But in any case, that petition should not include JS vars or code on it.

**Comment by xavijam** [comment]
cc @alonsogarciapablo @rochoa

**Comment by xavijam** [comment]
Fix in lzma-issue branch

**Comment by alonsogarciapablo** [comment]
Is the fix ready then? Should we open a PR in that case?

**Comment by xavijam** [comment]
The issue is in that branch, could you open a PR and add a test over layer_definition.spec.js?
