### ISSUE TITLE
Upgrade CSS task

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#696]
- [x] Use grunt and add SCSS.
  * Removed IE folder.
  * Moved leaflet images.
- [x] Implement ```grunt watch``` for CSS.
- [x] Start new styleguide html.
- [x] Enable Hound.
- [x] Add scss-lint.

**Comment by alonsogarciapablo** [comment]
How will `grunt watch` work? Will it generate the `dist` files everytime a file (JS or SCSS) changes?

**Comment by xavijam** [comment]
Yep, I'll try to follow how it works in editor.

**Comment by alonsogarciapablo** [comment]
Perfect! How/where will test these changes? We can have an .html file with some examples or use the styleguide for that...

**Comment by xavijam** [comment]
What about:

- ```grunt watch```: will generate the ```cartodb.css``` and ```cartodb.js``` files and it will be added to ```dist``` folder.
