### ISSUE TITLE
Update jQuery to the last version

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb.js#698]
- [ ] Fix specs
- [x] Test examples:  
  - [x] annotations.html
  - [x] basemap.html
  - [x] bing.html
  - [x] bounds.html
  - [x] core.html
  - [x] cursor_interaction.html
  - [x] custom.html
  - [x] custom_infowindow.html
  - [x] easy.html
  - [x] format.html
  - [x] gmaps_driving_directions_plus_sql_api.html
  - [x] gmaps_force_basemap.html
  - [x] gmaps_heatmap_plus_sql_api.html
  - [x] gmaps_satellite.html
  - [x] gmaps_with_torque.html
  - [x] header_overlay.html
  - [x] image.html
  - [x] infowindow-on-hover.html
  - [x] infowindow-with-different-positioning.html
  - [x] infowindow_with_graph.html
  - [x] layer_definition.html
  - [x] layer_selector.html
  - [x] layer_selector_overlay.html
  - [x] layer_toggle.html
  - [x] leaflet.html
  - [x] leaflet_control_multilayer2.html
  - [x] leaflet_core_library.html
  - [x] leaflet_hover_features.html
  - [x] leaflet_multilayer.html
  - [x] leaflet_namedmap.html
  - [x] leaflet_raster.html
  - [x] leaflet_sandwich.html
  - [x] leaflet_vector.html
  - [x] leaflet_vector_hover.html
  - [x] leaflet_vector_query_distance.html
  - [x] mobile.html
  - [x] modestmaps.html
  - [x] named-maps-example.html
  - [x] named-maps-template.html
  - [x] new-infowindow.html
  - [x] odyssey_test.html
  - [x] openlayers.html
  - [x] plain-color.html
  - [x] search_with_pin.html
  - [x] single-image.html
  - [x] slider.html
  - [x] stacked.html
  - [x] sublayer.html
  - [x] time_slider.html
  - [x] torque.html
  - [x] torque_step.html
  - [x] tutorial-1.html
  - [x] tutorial-2.html
  - [x] tutorial-google-driving-2.html
  - [x] tutorial-google-driving.html
  - [x] tutorial-google-heatmap-2.html
  - [x] tutorial-google-heatmap.html
  - [x] tutorial-query_by_distance-template.html
  - [x] tutorial-query_by_distance.html
  - [x] tutorial-toggle_map_view-template.html
  - [x] tutorial-toggle_map_view.html

**Comment by javierarce** [comment]
Found a problem with mousewheel.js
![screen shot 2015-10-06 at 11 38 26](https://cloud.githubusercontent.com/assets/4933/10305140/c967fe4a-6c1e-11e5-9bd7-2dd9901e016b.png)

**Comment by javierarce** [comment]
https://github.com/bodrovis/mwheelintent-rails

**Comment by techieshark** [comment]
+1: if this means those of us using newer jQuery (which is a requirement for bootstrap's JS) could avoid sending it to browsers twice, that'd be an appreciated win.

**Comment by viddo** [comment]
@javierarce wasn't the migration finished in #704?

**Comment by javierarce** [comment]
Yes, jQuery is updated in that branch, I forgot to close this ticket.

**Comment by techieshark** [comment]
Thanks @javierarce!

It looks like this is going into CartoDB v4? I haven't seen anything about version 4 other than the commits going into that branch (and it looks quite interesting – more modular perhaps); do you or @viddo have any sense of when that might be released?

**Comment by viddo** [comment]
@techieshark yes, it was merged to v4. There's nothing announced because there is no scope/date decided. The best suggestion I can give for now is to subscribe to the repo to get updates on what's going on, until a more official announcement is done.

**Comment by techieshark** [comment]
:+1: ok, thanks @viddo.
