### ISSUE TITLE
Fix/remove broken examples

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#715]
While working on #699 I found some broken examples, they can probably just be :fire: since they seemed to have been forgotten for a long time

- [x] [examples/layer_selector_overlay.html](https://github.com/CartoDB/cartodb.js/blob/develop/examples/layer_selector_overlay.html), points to local development viz.json, and uses cdb.load that should not be used (this is the only reference).
- [x] [test/demos](https://github.com/CartoDB/cartodb.js/tree/develop/test/demos) - have not updated for +2 years, and points to non-existing files.
- [x] [src/loader.js](https://github.com/CartoDB/cartodb.js/src/loader.js) - can't find any references to it, unused?
- [x] The examples under examples/gmaps/ seem to be broken too

**Comment by alonsogarciapablo** [comment]
- [ ] The examples under `examples/gmaps/` seem to be broken too.

**Comment by viddo** [comment]
updated desc :point_up: (thx)

**Comment by viddo** [comment]
bump @javierarce where were these changes done?

**Comment by javierarce** [comment]
Here: https://github.com/CartoDB/cartodb.js/tree/715-fix-examples.

**Comment by javierarce** [comment]
I'll fix or remove the broken gmaps examples.
