### ISSUE TITLE
Re-think interactivity of list widgets

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#745]
Right now list widgets are not interactive. The design team proposed that clicking on a list item should pan the map to the feature that was clicked. I think it makes sense to have a list of categories (with no aggregation/progress bar, etc.) that you can use to show/hide features on the map (for example: a list of states).

cc/ @saleiva

**Comment by saleiva** [comment]
Thinking on it.

**Comment by alonsogarciapablo** [comment]
Any thoughts on this @saleiva?

**Comment by saleiva** [comment]
Yep, give me a few days

**Comment by saleiva** [comment]
<img width="709" alt="screen shot 2015-11-02 at 13 33 36" src="https://cloud.githubusercontent.com/assets/132149/10881839/74c4deb4-8166-11e5-9df4-30acac920012.png">

**Comment by saleiva** [comment]
@alonsogarciapablo @xavijam let me know if you need the sketch file

**Comment by alonsogarciapablo** [comment]
Hey! Not sure what's the status of this. @saleiva did you decide how this is going to work?

**Comment by saleiva** [comment]
:)
