### ISSUE TITLE
Only accept the item you click on the first time you click on a category widget

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#748]
According to @saleiva, when all items of a category widget are selected and you click on an item, instead of rejecting the one you clicked, we should only accept that one (or reject all others). I guess this should be the behaviour the first time an item is clicked.

**Comment by saleiva** [comment]
Yep, also the auxiliar controls are missing from the actual version (buttons for selectiing/unselecting all items)

**Comment by xavijam** [comment]
yep, you are right @saleiva

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb.js/issues/750

**Comment by xavijam** [comment]
Done
