### ISSUE TITLE
 layer.hide() won't hide legend

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb.js#75]
the legend is not hidden when the layer is hidden

**Comment by gagecarto** [comment]
Hey team - Is this still under development or on hold?
Thanks!
-j

**Comment by chriswhong** [comment]
Hi guys, this still appears to be a problem in v3.15.10

```
var myTileLayer

//this adds a layer to the map and its associated overlays
cartodb.createLayer(map, vizJson)
.on('done', function(layer) {
  myTileLayer = layer
})

//removes the layer from the leaflet map, but the overlay remains
myTileLayer.remove()
```

I found this example in one of the SO threads about this issue, and it appears to be showing the same behavior (the legend remains when layers are removed with `.remove()`):

http://omars.me.pn/PoSERU282014.html
