### ISSUE TITLE
Stacked legend remains hidden after setting it up

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb.js#752]
You can check it our directly in our example: https://github.com/CartoDB/cartodb.js/blob/develop/examples/legends/stacked.html

In order to make it work, you need to explicitly show it, like adding

`$(".cartodb-legend-stack").show();`

after the legend is added to the HTML element (e.g. here: https://github.com/CartoDB/cartodb.js/blob/develop/examples/legends/stacked.html#L102)

**Comment by acanimal** [comment]
Hi @danicarrion 
right know the initial CSS style applied to the legend uses `display: none;` which makes legends hidden by default, letting the user decide when to show it.

Another option to change legends visibility (more cartondb-ish) is using `show/hide` methods:

```javascript
var stackedLegend = new cdb.geo.ui.Legend.Stacked({
  legends: legendsArray
});

stackedLegend.show();
stackedLegend.hide();
```

This way you don't need to know the HTML element used for the legend neither its id or class.

**Comment by danicarrion** [comment]
But why is this the behaviour of the stacked legend _only_? Also, if this is how it's supposed to work, we should fix the example.

**Comment by xavijam** [comment]
how would it work within CartoDB in a map without legends? Does it appear an transparent element?

**Comment by acanimal** [comment]
I made test on local environment and seems there are no derived issues.

**Comment by xavijam** [comment]
:+1: then.
