### ISSUE TITLE
add a description for cartodb.geo.ui.Zoom.show() and cartodb.geo.ui.Zoom.hide()

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb.js#761]
feel free to reassign, I'm not assigning a milestone, though

**Comment by csobier** [comment]
I just closed a [duplicate issue](https://github.com/CartoDB/docs/issues/683) for this in the Docs repo. This was recently reported by a Partner to the Support team.

@alonsogarciapablo , I have searched everywhere for sample code for show/hide zoom and can't find it anywhere. Can you help me please?

**Comment by csobier** [comment]
As @javisantana confirmed for [Docs issue#686](https://github.com/CartoDB/docs/issues/686), all `cartodb.geo.ui` code is not supported in the current version. 

- [ ] I will ensure a snapshot of the doc is archived for previous versions of CartoDB.js; as this code is specific to v.3.11, 3.12, and 3.13 (@matallo, need your help for this task please)
- [ ] I will remove the related code from the API doc
- [ ] I will replace with the current UI functions for these features
