### ISSUE TITLE
Category filters should send as few ones as possible

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb.js#777]
Category filter should decide if sending accepted or rejected is better, so it can send the minimum subset of categories.

Having 100 categories:
 - If I accept 2, it should send those 2 as accepted.
 - If I accept 90 (or reject 10), it should send those 10 as rejected.

**Comment by xavijam** [comment]
On it.

**Comment by xavijam** [comment]
Working! If we find any issue, let's open a new one.
