### ISSUE TITLE
Incorrect order in categories

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb.js#780]
Categories are sorted by count ASC, they should be sorted by count DESC. Categories with more results should be first in the list.

![screen shot 2015-11-06 at 18 11 58](https://cloud.githubusercontent.com/assets/45346/11003320/06d3079c-84b2-11e5-90ad-d77ac64f81ce.png)

**Comment by xavijam** [comment]
Fixed, thanks rochoa.
