### ISSUE TITLE
Disable map panning when scrollwheel and zoom "controls" are not enabled

### ISSUE THREAD

**Issue by acanimal** [CartoDB/cartodb.js#789]
Possibility to avoid map panning when zoom overlay is not present and scrollwheel is disabled.

See: https://github.com/CartoDB/cartodb/issues/5995

**Comment by acanimal** [comment]
cc @saleiva @xavijam @alonsogarciapablo 

When the user disables the "Zoom Controls" and "Scroll wheel zoom" within the editor options the shared map has disabled the possibility of dragging.

We need to decide if the behaviour must be active too within the editor. Has it sense to have a freeze map within the editor?

**Comment by xavijam** [comment]
In my opinion we should represent the same behaviour in the two scenarios, shouldn't we?

**Comment by saleiva** [comment]
I'd not block it within the editor since the UI is not ready for that and could look like an erorr

**Comment by xavijam** [comment]
:+1:
