### ISSUE TITLE
Position of infowindows is not correct when the time slider widget is present

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#793]
Infowindows are not showing up in the right position when the time slider "widget" is present. For some reason, there's some vertical offset (approximately the height of the times slider widget).

![screen shot 2015-11-11 at 16 21 43](https://cloud.githubusercontent.com/assets/390398/11094522/823528e8-8890-11e5-9ebd-4674d5b74fb3.png)

Resizing the window seems to fix the issue.

**Comment by acanimal** [comment]
Seems the map is not well positioned the first map the page is rendered. If you slightly resize the window it is repositioned and tooltips are well located.

Looking for the issue.

**Comment by alonsogarciapablo** [comment]
Also, it seems to work fine when using `cartodb.createVis` with the `gmaps_base_type: 'satellite'` option.

**Comment by acanimal** [comment]
At least for Leaflet, map is rendered before widgets are added to the page, that means the map is initially rendered taken the whole window size to compute its center. Later widgets are added, which borrows some space, but the map is not notified about that.
We need a way to recompute (or invalidate) the map size so it must re-render again.

**Comment by acanimal** [comment]
See #815. Solved in https://github.com/CartoDB/cartodb.js/commit/b2fef44f804731c0cb38f8ea3a687d6aac2fd40e
