### ISSUE TITLE
Extract viz.json parsing and separate vis model from vis view

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#804]
Here're the tasks for this refactor:

- [x] Extract a VizJSON class that contains vizjson internally and provides methods to modify it / extract info from it.
- [x] Extract loading of vizjson file to createVis.
- [x] Create visModel class and use it internally in vis/vis.js.
- [x] Extract construction of visModel object to `createVis` and inject it to vis/vis.js.
- [x] Rename `vis.load` to `vis.render`.

**Comment by acanimal** [comment]
+1 Complex structures of object should be created through factories.

**Comment by acanimal** [comment]
Add some comments:

-  Private `vis._addLegends` and `vis._createLayerLegendView` method are called externally from `createLayer.js`.
- Vis has listeners on `this.map.layers` (where `map` is a MapModel and `layers` a backbone collection) to update legends (`Vis.addLegend()`. We need to apply SOLID principles. I think Vis.load must be only responsible to create all the objects required to have a visualization (maps, views, models, etc). It must be like a factory for creation and also have method to interact with the visualization (adding more legends given a data config, adding new layers, etc).

**Comment by alonsogarciapablo** [comment]
This was completed in https://github.com/CartoDB/cartodb.js/pull/1313 💪
