### ISSUE TITLE
Implement category search

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#808]
### PENDING

- [ ] Fix and add (new) tests (_working_).
  - [x] Search / title view.
  - [x] Options view.
  - [x] Stats view.
  - [ ] List view.
  - [ ] List item view.
  - [ ] Search item view.
  - [ ] Paginator view.
  - [x] Category model.
  - [x] Category filter.

### ENHANCEMENTS
- Animate progress bars when results come from server (do not render again cc @javisantana).
- Implement new idea about "view more" instead of current paginator.

### DONE
- ~~When a search item is selected, we should add it to the current data model, and, of course, to the accept within filter model~~.
- [x] Hide/show elements when search is enabled/disabled.
- [x] Search item CSS.
- [x] Send bounding box parameters for search request (cc @rochoa).
- [x] When a filter is with accept value is set, value when request is done, it is not returned (cc @rochoa - https://github.com/CartoDB/Windshaft/issues/403).
- [x] When bounding box changes, search should be fetched, if it is enabled.
- [x] After selecting an item from a search, it is not possible to unselect it from the search view (we should change/review accept and reject items :S).
- [x] Locked items should not be selectable/unselectable.
- [x] Implement lock/unlock stuff.
- [x] Change "filter options" (2 selected  ---  select all / unselect all) stats when locked view is enabled.
- [x] When widget is locked, all locked items should be rendered, no matter if that item doesn't come from last widget fetch.
- [x] Set properly the progress bar for search items based on max value from the non-search items.
- [x] Search pagination template is not correct.
- [x] Other background bar style (@saleiva @urbanphes).
- [x] Apply selected search items (@saleiva @urbanphes).
- [x] Review bounding box.
- [x] Make loader work when a search is launched (*REVIEW*).
- [x] Implement new CSS buttons for search functionality (new icon font?) (thanks to @josecruz :dancer: ).
- [x] If we filter by an item (ACCEPT: "ES") and we select in the search "BR" and apply (for locking), ES and BR appears in the list (bug).
- [x] When widget is locked, item progress bar should appear with the green bar + the stripes pattern.
- [x] Implement placeholder for search view when a search is not applied yet (_working_).
- [x] When search is enabled, should it show locked items selected at that point before a search is done? (cc @saleiva). -> Finally we should show the same items we see in the other view, enabled or disabled depending the locked collection.
- [x] Review apply and cancel buttons when search is applied (@josecruz @urbanphes).
- [x] No search results state (@josecruz @urbanphes).
- [x] Add search text within lens when widget is locked.
- [x] Search form styles.
- [x] Remove pagination in data view.
- [x] Enable predictive search.
- [x] Enable "set category colors" (cc @javisantana -> http://bl.ocks.org/mbostock/5577023).
- [x] Review implemented code so far.
- [x] Apply number format.
- [x] Set a color for each visible category (cc @javisantana @saleiva -> http://bl.ocks.org/mbostock/5577023).
- [x] Fix font icons (@josecruz).
- [x] Change category colors (colorbrewer d3).
- [x] Assign colors to category items per value, not per position in the data array (cc @rambo).
- [x] Collapse widget behaviour (close/open it).
- [x] When custom colors are applied to a widget, if there is any more category widget within the same layer, it should "unapply" those custom colors (cc @rambo).

**Comment by xavijam** [comment]
- GIF Progress (17/11/15)

![widgets-search-category](https://cloud.githubusercontent.com/assets/132146/11221817/6bcfa7dc-8d67-11e5-8fd7-79b84b7276e5.gif)

**Comment by xavijam** [comment]
- GIF Progress (18/11/15)

![widgets-search-category](https://cloud.githubusercontent.com/assets/132146/11255877/03036d46-8e49-11e5-880d-89f5da685080.gif)

**Comment by xavijam** [comment]
- GIF Progress (19/11/15) 
![widgets-search-category](https://cloud.githubusercontent.com/assets/132146/11295238/40a71e1e-8f6a-11e5-842b-db8ccddcf977.gif)

**Comment by xavijam** [comment]
- GIF Progress (23/11/15) 
![widgets-search-category](https://cloud.githubusercontent.com/assets/132146/11364538/479ddc64-92a1-11e5-9e7f-472da64451b0.gif)

**Comment by saleiva** [comment]
Two ideas...

- Add the prefix/sufix to the numbers on the category list. Sometimes is really useful to see if there is money or transactions for example.
- Disable the hover effect for the time being as we are trying to avoid them (so it behaves in the same way in tablet and desktop).

**Comment by xavijam** [comment]
1. https://github.com/CartoDB/cartodb.js/commit/4bbcf29c60ea67eeeca3e52695b28c8db9ea9cfe
2. https://github.com/CartoDB/cartodb.js/commit/c24addb443670966d6274fe70303bc4c26a0abd3

**Comment by xavijam** [comment]
https://github.com/CartoDB/deep-insights.js/issues/8
