### ISSUE TITLE
Clearly separate tests that depend on torque

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#817]
Right now, some tests require `torque` to have been previously loaded. As suggested [here](https://github.com/CartoDB/cartodb.js/pull/799/files#r45091920), we can create two bundles of tests (one using just cartodb.js and another using cartodb.js with torque).

cc: @viddo

**Comment by viddo** [comment]
Liked I mentioned in https://github.com/CartoDB/cartodb.js/pull/799/files#r45091920 there already exist a test bundle for _"using cartodb.js with torque"_ so I think it's just a matter of extracting the tests to be run there instead.
