### ISSUE TITLE
JSDoc integration

### ISSUE THREAD

**Issue by acanimal** [CartoDB/cartodb.js#820]
Configure task to generate JSDoc and start documenting code using jsdoc notation.

**Comment by acanimal** [comment]
### Associated tasks

- [ ] Review all TODO comments

### Conventions and nomenclature

Good for code clarification and review it.

- [ ] Name variables depending if they contain data, model or view reference. For example about layer:
  - `layerData`: contains the data passed to create a layer,
  - `layerModel`: reference to a model,
  - `layerView`: reference to a view.

**Comment by acanimal** [comment]
Some notes:

- Hierarchies are documented (thanks to the @extends tag). We can navigate through hierarchies.
- Classes contains also parent methods.
- We can document callbacks functions and its arguments.
- We can specify which events triggers classes

**Comment by viddo** [comment]
this will be very helpful :)
