### ISSUE TITLE
Add a proper Prefix(namespace) for new v4 elements

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#823]
For example:

```css
.CDBWidget-... { }
.CDBInfowindow-... { }
.CDBIcon-... { }
```

Places:
- [x] stylesheets.
- [x] javascript files.
- [x] javascript templates.
- [x] current widget examples.
- [x] styleguide examples.
- [x] tests.

@CartoDB/frontend @piensaenpixel @acanimal

**Comment by matallo** [comment]
+1 to `.CDB-*`

**Comment by xavijam** [comment]
```.CDB-Infowindow-... ```  breaks our scss lint rules :(. Does ```CDBInfowindow``` thing sound so bad?

**Comment by viddo** [comment]
I'd love to see [shadow-dom](http://webcomponents.org/polyfills/shadow-dom/) but perhaps not ready for our use-cases just yet…? 
Until then +1

**Comment by matallo** [comment]
can't be done with regex? http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#detecting-namespaces

in any case, I'm fine with that ¯\_(ツ)_/¯

**Comment by xavijam** [comment]
@matallo, we are already doing the check with RegExp (https://github.com/CartoDB/cartodb.js/blob/widgets/.scss-lint.yml#L75) :joy:, if you agree with CDB-*, ok, let's add it to the RegExp.

cc @javierarce

**Comment by matallo** [comment]
WOHOO, now that's a prefix :_D

**Comment by javierarce** [comment]
haha, let's add it to the regexp then :construction_worker:

**Comment by xavijam** [comment]
Already done in widgets branch :).
