### ISSUE TITLE
Add little transition when changing a numeric value

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb.js#862]
In formula widgets or the others (mininumbers).
It helps a lot to see that a number has changed.

**Comment by javierarce** [comment]
Ok, I'm enabling the initial animation we had in the histograms (it looks smoother and faster in the HTML) and I'll extend it to the formulas as well.

![animation](https://cloud.githubusercontent.com/assets/4933/11419857/7c4f3360-942a-11e5-84bb-12476c0c2133.gif)

**Comment by javierarce** [comment]
And a test for the formula widget:

![animation](https://cloud.githubusercontent.com/assets/4933/11420417/45b5de90-942e-11e5-8ddf-04b560f5b496.gif)
