### ISSUE TITLE
Change Torque time-series widget behavior on range selection (2nd iteration)

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#905]
edit: widget changes was moved to https://github.com/CartoDB/deep-insights.js/issues/6 but still needs some modifications here for torque layer model. 

Awaits https://github.com/CartoDB/torque/issues/246

- [x] mock cumulativeRender attr (until :point_up: is ready)
- [x] :fire: setStepsRange code (no longer needed)
- [x] bump torque.js version once released :point_up: 
- [x] replace mock with actual implementation

**Comment by viddo** [comment]
@saleiva did we get the details correct? something missing?

**Comment by viddo** [comment]
after talking with @javisantana and @rochoa this is not feasible atm, and will need more discussion before continuing.

**Comment by rochoa** [comment]
This will use: https://github.com/CartoDB/torque/issues/246

**Comment by viddo** [comment]
Moved to https://github.com/CartoDB/deep-insights.js/issues/6, since the the concerned code was extracted :wave:

**Comment by viddo** [comment]
Reopening, there's still some work TBD here (updated desc)

**Comment by viddo** [comment]
Done in #937
