### ISSUE TITLE
Review mobile layout for widget examples

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#912]

**Comment by xavijam** [comment]
Ping!

**Comment by viddo** [comment]
Just saw this issues… I'm about to merge `widgets` branch to `v4`, you'd need to merge v4 with your WIP branch to be able to finish this one I think, but I suspect that the changes should be done in https://github.com/CartoDB/deep-insights.js instead. 

Let me know when you're done @piensaenpixel and I'll help you move the changes if necessary. Sorry for the inconvenience.
