### ISSUE TITLE
Hide sublayers concept from public API?

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#917]
Even if the new deep-insights code doesn't use sub-layers concept themselves, they still rely on them to build up what layers to include in the windshaft client.
See [`deep-insights.js/src/create-dashboard.js` (L84-L87)](https://github.com/CartoDB/deep-insights.js/blob/ce29b69e9eb1e816acedf7842d8a6ea3690642c5/src/create-dashboard.js#L84-L87), which was extracted from [`vis.load` (L406-L418)](https://github.com/CartoDB/cartodb.js/blob/fcd3111f11560b94bbb43eb2be4a9e4faa71b81f/src/vis/vis.js#L406-L418)

cc @rochoa

**Comment by alonsogarciapablo** [comment]
This will be resolved once #829 is implemented.
