### ISSUE TITLE
Detect very small changes on the map to not update all the widgets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb.js#918]
Maybe an enhancement. In order to avoid unnecesary API calls, we could not refresh the data when panning the map just a few pixels.

**Comment by rochoa** [comment]
The thing is that at some zoom levels a few pixels are hundreds of meters or even a few kilometres :smiling_imp:

**Comment by saleiva** [comment]
So filtering on those by bounding box diesn't make any sense :)

**Comment by xavijam** [comment]
Moved to https://github.com/CartoDB/deep-insights.js/issues/40
