### ISSUE TITLE
3.60% IN 5 CATEGORIES should be 3.60% IN TOP 5 CATEGORIES

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb.js#920]

**Comment by xavijam** [comment]
I feel we shouldn't use that text because right now categories are based on bounding box, that doesn't mean those categories as the top 5 of the whole dataset. Could we call it ```x% from total```?

**Comment by saleiva** [comment]
But those are the top5 categories anyway, right? on that bbox, but the top 5

**Comment by xavijam** [comment]
https://github.com/CartoDB/deep-insights.js/issues/7
