### ISSUE TITLE
Replace old tiles loader element

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#941]
<img width="190" alt="screen shot 2015-12-16 at 15 54 29" src="https://cloud.githubusercontent.com/assets/132146/11844109/4e242f7a-a40d-11e5-9d0c-414c6021cefa.png">

cc @josecruz @saleiva

**Comment by saleiva** [comment]
It's already designed. Is the same blue bar you have on the widgets but on the map

**Comment by xavijam** [comment]
:clap: thanks

**Comment by xavijam** [comment]
Done by @piensaenpixel!
