### ISSUE TITLE
New infowindow does not render image properly when it is added by hand

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#945]
<img width="307" alt="screen shot 2015-12-16 at 22 07 41" src="https://cloud.githubusercontent.com/assets/132146/11854006/7d5c0496-a441-11e5-8d83-07f6d9745ec7.png">

cc @piensaenpixel

**Comment by xavijam** [comment]
![infowindow-bug](https://cloud.githubusercontent.com/assets/132146/11854066/d58bc2b4-a441-11e5-8c6d-28cdc6a96e29.gif)

**Comment by javierarce** [comment]
@xavijam what do you mean "added by hand"?

**Comment by xavijam** [comment]
Custom HTML

**Comment by javierarce** [comment]
Sure, if you already have an example I could use that to test it (I'm going to create one myself but it would be nice to test different templates).
