### ISSUE TITLE
Push some widget related stuff from dataviews to deep-insights.js

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#990]
Some follow up work from #989 and CartoDB/deep-insights.js#67:

- [x] Move logic that is specific to category widgets (e.g. knowing what categories have been accepted or rejected, etc.) from the category dataview model. See [this comment](https://github.com/CartoDB/cartodb.js/pull/989/files#r49316685) and [this comment](https://github.com/CartoDB/cartodb.js/pull/989/files#r49328887) for more context. IMO dataview models should only provide a mechanism to get the data.
- [x] ~~Move the `sync` and `bbox` options to the widget model. See [this comment](https://github.com/CartoDB/cartodb.js/pull/989/files#r49328186) for more context. Perhaps `deep-insights` can use the [`setDisabled`](https://github.com/CartoDB/cartodb.js/pull/989/files#diff-805364e485d740e26e33839755aab753R97) method.~~, not moved after discussion, but clarified their names (`syncData`, `syncBoundingBox`)

cc: @viddo

**Comment by viddo** [comment]
Done in #993
