### ISSUE TITLE
Provide a way to only trigger a request to Windshaft once dataviews have been setup 

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#991]
Part of #968.

We need to replace [this temporary fix](https://github.com/CartoDB/cartodb.js/blob/v4/src/windshaft/dashboard.js#L21-L31) by something more elegant that ensures that only one request to Windshaft is triggered when a visualization is created and we know that dataviews are going to be added right after that (as we're doing [here](https://github.com/CartoDB/deep-insights.js/blob/master/src/create-dashboard.js#L28-L44)).

Code in deep-insights.js will need to be updated to use this new mechanism.

cc: @viddo

**Comment by viddo** [comment]
:+1: Although to clarify:

> (as we're doing [here](https://github.com/CartoDB/deep-insights.js/blob/master/src/create-dashboard.js#L28-L44)).

That's the factory that defines the mapping of dataview-type => what-dataview-factory-method-to-call, the dataviews are created a little [further down in the same file](https://github.com/CartoDB/deep-insights.js/blob/master/src/create-dashboard.js#L90-L91).
