### ISSUE TITLE
CartoDB logo appearing with createLayer/createVis

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb.js#996]
The `cartodb.createLayer()` and `cartodb.createVis()` methods will add a CartoDB logo to the map. 
- The logo is created regardless of wether the option is activated or not in the Editor. 
- The layerSource is also irrelevant, the logo appears using both the `viz.json` URL or a custom Layer Source Object
- When using `cartodb.createVis()`, the `cartodb_logo:false` option will prevent this.
- For `cartodb.createLayer()`, the logo has to be removed using CSS:
  
  ```
  .cartodb-logo{
     display:none!important;
  }
  ```
  
  The expected behavior would be for the logo to appear on maps created with `createVis()`, when the visualization has the `cartodb_logo` option activated. It shouldn't appear on maps created with `createLayer()`

**Comment by ztephm** [comment]
* [ ] Notify client when fixed please S/B 7870741
